# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Repositories\QGisPlugins\Herevea\Ui_ActuacionForm.ui'
#
# Created: Sun Jun 21 10:29:42 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActuacionForm(object):
    def setupUi(self, ActuacionForm, catastroService):
        ActuacionForm.setObjectName(_fromUtf8("ActuacionForm"))
        ActuacionForm.resize(1170, 696)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Herevea.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ActuacionForm.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(ActuacionForm)
        self.buttonBox.setGeometry(QtCore.QRect(700, 650, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label_31 = QtGui.QLabel(ActuacionForm)
        self.label_31.setGeometry(QtCore.QRect(20, 20, 81, 20))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.tbxDireccion = QtGui.QLineEdit(ActuacionForm)
        self.tbxDireccion.setGeometry(QtCore.QRect(96, 20, 421, 25))
        self.tbxDireccion.setReadOnly(True)
        self.tbxDireccion.setObjectName(_fromUtf8("tbxDireccion"))
        self.tbxRefCatastral = QtGui.QLineEdit(ActuacionForm)
        self.tbxRefCatastral.setGeometry(QtCore.QRect(647, 20, 211, 25))
        self.tbxRefCatastral.setReadOnly(True)
        self.tbxRefCatastral.setObjectName(_fromUtf8("tbxRefCatastral"))
        self.label_32 = QtGui.QLabel(ActuacionForm)
        self.label_32.setGeometry(QtCore.QRect(540, 20, 101, 20))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.tabWidget = QtGui.QTabWidget(ActuacionForm)
        self.tabWidget.setGeometry(QtCore.QRect(20, 60, 1131, 561))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.cmbEncofrados = QtGui.QComboBox(self.tab)
        self.cmbEncofrados.setGeometry(QtCore.QRect(160, 37, 431, 25))
        self.cmbEncofrados.setObjectName(_fromUtf8("cmbEncofrados"))
        self.cmbEncofrados.addItem(_fromUtf8(""))
        self.cmbEncofrados.addItem(_fromUtf8(""))
        self.cmbForjados_17 = QtGui.QComboBox(self.tab)
        self.cmbForjados_17.setGeometry(QtCore.QRect(830, 36, 81, 25))
        self.cmbForjados_17.setObjectName(_fromUtf8("cmbForjados_17"))
        self.cmbForjados_17.addItem(_fromUtf8(""))
        self.cmbForjados_17.addItem(_fromUtf8(""))
        self.cmbForjados_17.addItem(_fromUtf8(""))
        self.cmbForjados_17.addItem(_fromUtf8(""))
        self.label_78 = QtGui.QLabel(self.tab)
        self.label_78.setGeometry(QtCore.QRect(660, 38, 151, 19))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(40, 37, 101, 19))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_56 = QtGui.QLabel(self.tab)
        self.label_56.setGeometry(QtCore.QRect(920, 40, 31, 19))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_58 = QtGui.QLabel(self.tab_2)
        self.label_58.setGeometry(QtCore.QRect(940, 80, 31, 19))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.cmbForjados_18 = QtGui.QComboBox(self.tab_2)
        self.cmbForjados_18.setGeometry(QtCore.QRect(850, 37, 81, 25))
        self.cmbForjados_18.setObjectName(_fromUtf8("cmbForjados_18"))
        self.cmbForjados_18.addItem(_fromUtf8(""))
        self.cmbForjados_18.addItem(_fromUtf8(""))
        self.cmbForjados_18.addItem(_fromUtf8(""))
        self.cmbForjados_18.addItem(_fromUtf8(""))
        self.label_59 = QtGui.QLabel(self.tab_2)
        self.label_59.setGeometry(QtCore.QRect(940, 120, 31, 19))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.cmbColectores = QtGui.QComboBox(self.tab_2)
        self.cmbColectores.setGeometry(QtCore.QRect(200, 77, 401, 25))
        self.cmbColectores.setObjectName(_fromUtf8("cmbColectores"))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.label_80 = QtGui.QLabel(self.tab_2)
        self.label_80.setGeometry(QtCore.QRect(680, 79, 151, 19))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.label_57 = QtGui.QLabel(self.tab_2)
        self.label_57.setGeometry(QtCore.QRect(940, 41, 31, 19))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.cmbForjados_20 = QtGui.QComboBox(self.tab_2)
        self.cmbForjados_20.setGeometry(QtCore.QRect(850, 116, 81, 25))
        self.cmbForjados_20.setObjectName(_fromUtf8("cmbForjados_20"))
        self.cmbForjados_20.addItem(_fromUtf8(""))
        self.cmbForjados_20.addItem(_fromUtf8(""))
        self.cmbForjados_20.addItem(_fromUtf8(""))
        self.cmbForjados_20.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(40, 37, 101, 19))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(40, 117, 231, 19))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.cmbForjados_19 = QtGui.QComboBox(self.tab_2)
        self.cmbForjados_19.setGeometry(QtCore.QRect(850, 76, 81, 25))
        self.cmbForjados_19.setObjectName(_fromUtf8("cmbForjados_19"))
        self.cmbForjados_19.addItem(_fromUtf8(""))
        self.cmbForjados_19.addItem(_fromUtf8(""))
        self.cmbForjados_19.addItem(_fromUtf8(""))
        self.cmbForjados_19.addItem(_fromUtf8(""))
        self.label_79 = QtGui.QLabel(self.tab_2)
        self.label_79.setGeometry(QtCore.QRect(680, 40, 151, 19))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.label_81 = QtGui.QLabel(self.tab_2)
        self.label_81.setGeometry(QtCore.QRect(680, 118, 151, 19))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.cmbBajantes = QtGui.QComboBox(self.tab_2)
        self.cmbBajantes.setGeometry(QtCore.QRect(200, 117, 401, 25))
        self.cmbBajantes.setObjectName(_fromUtf8("cmbBajantes"))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(40, 77, 231, 19))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cmbArquetas = QtGui.QComboBox(self.tab_2)
        self.cmbArquetas.setGeometry(QtCore.QRect(200, 37, 401, 25))
        self.cmbArquetas.setObjectName(_fromUtf8("cmbArquetas"))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.setItemText(4, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 80, 981, 91))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.label_18 = QtGui.QLabel(self.groupBox_11)
        self.label_18.setGeometry(QtCore.QRect(20, 55, 201, 19))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.cmbCubiertasI_2 = QtGui.QComboBox(self.groupBox_11)
        self.cmbCubiertasI_2.setGeometry(QtCore.QRect(250, 55, 351, 25))
        self.cmbCubiertasI_2.setObjectName(_fromUtf8("cmbCubiertasI_2"))
        self.cmbCubiertasI_2.addItem(_fromUtf8(""))
        self.cmbCubiertasI_2.addItem(_fromUtf8(""))
        self.cmbCubiertasI_2.addItem(_fromUtf8(""))
        self.label_33 = QtGui.QLabel(self.groupBox_11)
        self.label_33.setGeometry(QtCore.QRect(20, 25, 231, 19))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.cmbCubiertasH_2 = QtGui.QComboBox(self.groupBox_11)
        self.cmbCubiertasH_2.setGeometry(QtCore.QRect(250, 25, 351, 25))
        self.cmbCubiertasH_2.setObjectName(_fromUtf8("cmbCubiertasH_2"))
        self.cmbCubiertasH_2.addItem(_fromUtf8(""))
        self.cmbCubiertasH_2.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.groupBox_11)
        self.label_3.setGeometry(QtCore.QRect(920, 29, 31, 19))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cmbForjados_3 = QtGui.QComboBox(self.groupBox_11)
        self.cmbForjados_3.setGeometry(QtCore.QRect(830, 25, 81, 25))
        self.cmbForjados_3.setObjectName(_fromUtf8("cmbForjados_3"))
        self.cmbForjados_3.addItem(_fromUtf8(""))
        self.cmbForjados_3.addItem(_fromUtf8(""))
        self.cmbForjados_3.addItem(_fromUtf8(""))
        self.cmbForjados_3.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.groupBox_11)
        self.label_4.setGeometry(QtCore.QRect(920, 59, 31, 19))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cmbForjados_4 = QtGui.QComboBox(self.groupBox_11)
        self.cmbForjados_4.setGeometry(QtCore.QRect(830, 55, 81, 25))
        self.cmbForjados_4.setObjectName(_fromUtf8("cmbForjados_4"))
        self.cmbForjados_4.addItem(_fromUtf8(""))
        self.cmbForjados_4.addItem(_fromUtf8(""))
        self.cmbForjados_4.addItem(_fromUtf8(""))
        self.cmbForjados_4.addItem(_fromUtf8(""))
        self.label_83 = QtGui.QLabel(self.groupBox_11)
        self.label_83.setGeometry(QtCore.QRect(670, 25, 151, 19))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.label_84 = QtGui.QLabel(self.groupBox_11)
        self.label_84.setGeometry(QtCore.QRect(671, 55, 151, 19))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 350, 981, 151))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.label_38 = QtGui.QLabel(self.groupBox_13)
        self.label_38.setGeometry(QtCore.QRect(20, 60, 201, 19))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.cmbCubiertasI_5 = QtGui.QComboBox(self.groupBox_13)
        self.cmbCubiertasI_5.setGeometry(QtCore.QRect(250, 60, 351, 25))
        self.cmbCubiertasI_5.setObjectName(_fromUtf8("cmbCubiertasI_5"))
        self.cmbCubiertasI_5.addItem(_fromUtf8(""))
        self.cmbCubiertasI_5.addItem(_fromUtf8(""))
        self.cmbCubiertasI_5.addItem(_fromUtf8(""))
        self.label_39 = QtGui.QLabel(self.groupBox_13)
        self.label_39.setGeometry(QtCore.QRect(20, 30, 231, 19))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.cmbCubiertasH_5 = QtGui.QComboBox(self.groupBox_13)
        self.cmbCubiertasH_5.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbCubiertasH_5.setObjectName(_fromUtf8("cmbCubiertasH_5"))
        self.cmbCubiertasH_5.addItem(_fromUtf8(""))
        self.cmbCubiertasH_5.addItem(_fromUtf8(""))
        self.cmbCubiertasI_6 = QtGui.QComboBox(self.groupBox_13)
        self.cmbCubiertasI_6.setGeometry(QtCore.QRect(250, 120, 351, 25))
        self.cmbCubiertasI_6.setObjectName(_fromUtf8("cmbCubiertasI_6"))
        self.cmbCubiertasI_6.addItem(_fromUtf8(""))
        self.cmbCubiertasI_6.addItem(_fromUtf8(""))
        self.label_40 = QtGui.QLabel(self.groupBox_13)
        self.label_40.setGeometry(QtCore.QRect(20, 120, 221, 19))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.groupBox_13)
        self.label_41.setGeometry(QtCore.QRect(20, 90, 231, 19))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.cmbCubiertasH_6 = QtGui.QComboBox(self.groupBox_13)
        self.cmbCubiertasH_6.setGeometry(QtCore.QRect(250, 90, 351, 25))
        self.cmbCubiertasH_6.setObjectName(_fromUtf8("cmbCubiertasH_6"))
        self.cmbCubiertasH_6.addItem(_fromUtf8(""))
        self.cmbCubiertasH_6.addItem(_fromUtf8(""))
        self.cmbForjados_9 = QtGui.QComboBox(self.groupBox_13)
        self.cmbForjados_9.setGeometry(QtCore.QRect(830, 30, 81, 25))
        self.cmbForjados_9.setObjectName(_fromUtf8("cmbForjados_9"))
        self.cmbForjados_9.addItem(_fromUtf8(""))
        self.cmbForjados_9.addItem(_fromUtf8(""))
        self.cmbForjados_9.addItem(_fromUtf8(""))
        self.cmbForjados_9.addItem(_fromUtf8(""))
        self.label_14 = QtGui.QLabel(self.groupBox_13)
        self.label_14.setGeometry(QtCore.QRect(920, 34, 31, 19))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.cmbForjados_10 = QtGui.QComboBox(self.groupBox_13)
        self.cmbForjados_10.setGeometry(QtCore.QRect(830, 60, 81, 25))
        self.cmbForjados_10.setObjectName(_fromUtf8("cmbForjados_10"))
        self.cmbForjados_10.addItem(_fromUtf8(""))
        self.cmbForjados_10.addItem(_fromUtf8(""))
        self.cmbForjados_10.addItem(_fromUtf8(""))
        self.cmbForjados_10.addItem(_fromUtf8(""))
        self.label_15 = QtGui.QLabel(self.groupBox_13)
        self.label_15.setGeometry(QtCore.QRect(920, 64, 31, 19))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.cmbForjados_11 = QtGui.QComboBox(self.groupBox_13)
        self.cmbForjados_11.setGeometry(QtCore.QRect(830, 90, 81, 25))
        self.cmbForjados_11.setObjectName(_fromUtf8("cmbForjados_11"))
        self.cmbForjados_11.addItem(_fromUtf8(""))
        self.cmbForjados_11.addItem(_fromUtf8(""))
        self.cmbForjados_11.addItem(_fromUtf8(""))
        self.cmbForjados_11.addItem(_fromUtf8(""))
        self.label_16 = QtGui.QLabel(self.groupBox_13)
        self.label_16.setGeometry(QtCore.QRect(920, 94, 31, 19))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.cmbForjados_12 = QtGui.QComboBox(self.groupBox_13)
        self.cmbForjados_12.setGeometry(QtCore.QRect(830, 120, 81, 25))
        self.cmbForjados_12.setObjectName(_fromUtf8("cmbForjados_12"))
        self.cmbForjados_12.addItem(_fromUtf8(""))
        self.cmbForjados_12.addItem(_fromUtf8(""))
        self.cmbForjados_12.addItem(_fromUtf8(""))
        self.cmbForjados_12.addItem(_fromUtf8(""))
        self.label_17 = QtGui.QLabel(self.groupBox_13)
        self.label_17.setGeometry(QtCore.QRect(920, 124, 31, 19))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_89 = QtGui.QLabel(self.groupBox_13)
        self.label_89.setGeometry(QtCore.QRect(670, 32, 151, 19))
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.label_90 = QtGui.QLabel(self.groupBox_13)
        self.label_90.setGeometry(QtCore.QRect(670, 60, 151, 19))
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.label_91 = QtGui.QLabel(self.groupBox_13)
        self.label_91.setGeometry(QtCore.QRect(670, 90, 151, 19))
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.label_92 = QtGui.QLabel(self.groupBox_13)
        self.label_92.setGeometry(QtCore.QRect(670, 120, 151, 19))
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 981, 61))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(20, 26, 231, 19))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.cmbForjados = QtGui.QComboBox(self.groupBox_4)
        self.cmbForjados.setGeometry(QtCore.QRect(250, 26, 351, 25))
        self.cmbForjados.setObjectName(_fromUtf8("cmbForjados"))
        self.cmbForjados.addItem(_fromUtf8(""))
        self.cmbForjados.addItem(_fromUtf8(""))
        self.cmbForjados_2 = QtGui.QComboBox(self.groupBox_4)
        self.cmbForjados_2.setGeometry(QtCore.QRect(830, 26, 81, 25))
        self.cmbForjados_2.setObjectName(_fromUtf8("cmbForjados_2"))
        self.cmbForjados_2.addItem(_fromUtf8(""))
        self.cmbForjados_2.addItem(_fromUtf8(""))
        self.cmbForjados_2.addItem(_fromUtf8(""))
        self.cmbForjados_2.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(920, 30, 31, 19))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_82 = QtGui.QLabel(self.groupBox_4)
        self.label_82.setGeometry(QtCore.QRect(670, 27, 151, 19))
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_12.setGeometry(QtCore.QRect(20, 180, 981, 161))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.label_34 = QtGui.QLabel(self.groupBox_12)
        self.label_34.setGeometry(QtCore.QRect(20, 60, 201, 19))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.cmbCubiertasI_3 = QtGui.QComboBox(self.groupBox_12)
        self.cmbCubiertasI_3.setGeometry(QtCore.QRect(250, 60, 351, 25))
        self.cmbCubiertasI_3.setObjectName(_fromUtf8("cmbCubiertasI_3"))
        self.cmbCubiertasI_3.addItem(_fromUtf8(""))
        self.cmbCubiertasI_3.addItem(_fromUtf8(""))
        self.cmbCubiertasI_3.addItem(_fromUtf8(""))
        self.label_35 = QtGui.QLabel(self.groupBox_12)
        self.label_35.setGeometry(QtCore.QRect(20, 30, 231, 19))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.cmbCubiertasH_3 = QtGui.QComboBox(self.groupBox_12)
        self.cmbCubiertasH_3.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbCubiertasH_3.setObjectName(_fromUtf8("cmbCubiertasH_3"))
        self.cmbCubiertasH_3.addItem(_fromUtf8(""))
        self.cmbCubiertasH_3.addItem(_fromUtf8(""))
        self.cmbCubiertasI_4 = QtGui.QComboBox(self.groupBox_12)
        self.cmbCubiertasI_4.setGeometry(QtCore.QRect(250, 120, 351, 25))
        self.cmbCubiertasI_4.setObjectName(_fromUtf8("cmbCubiertasI_4"))
        self.cmbCubiertasI_4.addItem(_fromUtf8(""))
        self.cmbCubiertasI_4.addItem(_fromUtf8(""))
        self.label_36 = QtGui.QLabel(self.groupBox_12)
        self.label_36.setGeometry(QtCore.QRect(20, 120, 221, 19))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.groupBox_12)
        self.label_37.setGeometry(QtCore.QRect(20, 90, 231, 19))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.cmbCubiertasH_4 = QtGui.QComboBox(self.groupBox_12)
        self.cmbCubiertasH_4.setGeometry(QtCore.QRect(250, 90, 351, 25))
        self.cmbCubiertasH_4.setObjectName(_fromUtf8("cmbCubiertasH_4"))
        self.cmbCubiertasH_4.addItem(_fromUtf8(""))
        self.cmbCubiertasH_4.addItem(_fromUtf8(""))
        self.cmbForjados_5 = QtGui.QComboBox(self.groupBox_12)
        self.cmbForjados_5.setGeometry(QtCore.QRect(830, 30, 81, 25))
        self.cmbForjados_5.setObjectName(_fromUtf8("cmbForjados_5"))
        self.cmbForjados_5.addItem(_fromUtf8(""))
        self.cmbForjados_5.addItem(_fromUtf8(""))
        self.cmbForjados_5.addItem(_fromUtf8(""))
        self.cmbForjados_5.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.groupBox_12)
        self.label_6.setGeometry(QtCore.QRect(920, 34, 31, 19))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cmbForjados_6 = QtGui.QComboBox(self.groupBox_12)
        self.cmbForjados_6.setGeometry(QtCore.QRect(830, 60, 81, 25))
        self.cmbForjados_6.setObjectName(_fromUtf8("cmbForjados_6"))
        self.cmbForjados_6.addItem(_fromUtf8(""))
        self.cmbForjados_6.addItem(_fromUtf8(""))
        self.cmbForjados_6.addItem(_fromUtf8(""))
        self.cmbForjados_6.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.groupBox_12)
        self.label_10.setGeometry(QtCore.QRect(920, 64, 31, 19))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.cmbForjados_7 = QtGui.QComboBox(self.groupBox_12)
        self.cmbForjados_7.setGeometry(QtCore.QRect(830, 90, 81, 25))
        self.cmbForjados_7.setObjectName(_fromUtf8("cmbForjados_7"))
        self.cmbForjados_7.addItem(_fromUtf8(""))
        self.cmbForjados_7.addItem(_fromUtf8(""))
        self.cmbForjados_7.addItem(_fromUtf8(""))
        self.cmbForjados_7.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.groupBox_12)
        self.label_12.setGeometry(QtCore.QRect(920, 94, 31, 19))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.cmbForjados_8 = QtGui.QComboBox(self.groupBox_12)
        self.cmbForjados_8.setGeometry(QtCore.QRect(830, 119, 81, 25))
        self.cmbForjados_8.setObjectName(_fromUtf8("cmbForjados_8"))
        self.cmbForjados_8.addItem(_fromUtf8(""))
        self.cmbForjados_8.addItem(_fromUtf8(""))
        self.cmbForjados_8.addItem(_fromUtf8(""))
        self.cmbForjados_8.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(self.groupBox_12)
        self.label_13.setGeometry(QtCore.QRect(920, 123, 31, 19))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_85 = QtGui.QLabel(self.groupBox_12)
        self.label_85.setGeometry(QtCore.QRect(670, 30, 151, 19))
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.label_86 = QtGui.QLabel(self.groupBox_12)
        self.label_86.setGeometry(QtCore.QRect(670, 60, 151, 19))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.label_87 = QtGui.QLabel(self.groupBox_12)
        self.label_87.setGeometry(QtCore.QRect(670, 90, 151, 19))
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.label_88 = QtGui.QLabel(self.groupBox_12)
        self.label_88.setGeometry(QtCore.QRect(670, 120, 151, 19))
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_15 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_15.setGeometry(QtCore.QRect(20, 240, 981, 211))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.label_46 = QtGui.QLabel(self.groupBox_15)
        self.label_46.setGeometry(QtCore.QRect(11, 73, 201, 19))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.cmbCubiertasI_9 = QtGui.QComboBox(self.groupBox_15)
        self.cmbCubiertasI_9.setGeometry(QtCore.QRect(260, 73, 351, 25))
        self.cmbCubiertasI_9.setObjectName(_fromUtf8("cmbCubiertasI_9"))
        self.cmbCubiertasI_9.addItem(_fromUtf8(""))
        self.cmbCubiertasI_9.addItem(_fromUtf8(""))
        self.label_47 = QtGui.QLabel(self.groupBox_15)
        self.label_47.setGeometry(QtCore.QRect(11, 34, 231, 19))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.cmbCubiertasH_9 = QtGui.QComboBox(self.groupBox_15)
        self.cmbCubiertasH_9.setGeometry(QtCore.QRect(260, 34, 351, 25))
        self.cmbCubiertasH_9.setObjectName(_fromUtf8("cmbCubiertasH_9"))
        self.cmbCubiertasH_9.addItem(_fromUtf8(""))
        self.cmbCubiertasH_9.addItem(_fromUtf8(""))
        self.cmbCubiertasI_10 = QtGui.QComboBox(self.groupBox_15)
        self.cmbCubiertasI_10.setGeometry(QtCore.QRect(260, 113, 351, 25))
        self.cmbCubiertasI_10.setObjectName(_fromUtf8("cmbCubiertasI_10"))
        self.cmbCubiertasI_10.addItem(_fromUtf8(""))
        self.cmbCubiertasI_10.addItem(_fromUtf8(""))
        self.label_48 = QtGui.QLabel(self.groupBox_15)
        self.label_48.setGeometry(QtCore.QRect(11, 113, 221, 19))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_49 = QtGui.QLabel(self.groupBox_15)
        self.label_49.setGeometry(QtCore.QRect(11, 150, 241, 19))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.cmbCubiertasH_10 = QtGui.QComboBox(self.groupBox_15)
        self.cmbCubiertasH_10.setGeometry(QtCore.QRect(260, 150, 351, 25))
        self.cmbCubiertasH_10.setObjectName(_fromUtf8("cmbCubiertasH_10"))
        self.cmbCubiertasH_10.addItem(_fromUtf8(""))
        self.cmbCubiertasH_10.addItem(_fromUtf8(""))
        self.cmbForjados_21 = QtGui.QComboBox(self.groupBox_15)
        self.cmbForjados_21.setGeometry(QtCore.QRect(850, 34, 81, 25))
        self.cmbForjados_21.setObjectName(_fromUtf8("cmbForjados_21"))
        self.cmbForjados_21.addItem(_fromUtf8(""))
        self.cmbForjados_21.addItem(_fromUtf8(""))
        self.cmbForjados_21.addItem(_fromUtf8(""))
        self.cmbForjados_21.addItem(_fromUtf8(""))
        self.label_60 = QtGui.QLabel(self.groupBox_15)
        self.label_60.setGeometry(QtCore.QRect(940, 38, 31, 19))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.cmbForjados_22 = QtGui.QComboBox(self.groupBox_15)
        self.cmbForjados_22.setGeometry(QtCore.QRect(850, 73, 81, 25))
        self.cmbForjados_22.setObjectName(_fromUtf8("cmbForjados_22"))
        self.cmbForjados_22.addItem(_fromUtf8(""))
        self.cmbForjados_22.addItem(_fromUtf8(""))
        self.cmbForjados_22.addItem(_fromUtf8(""))
        self.cmbForjados_22.addItem(_fromUtf8(""))
        self.label_61 = QtGui.QLabel(self.groupBox_15)
        self.label_61.setGeometry(QtCore.QRect(940, 77, 31, 19))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.cmbForjados_23 = QtGui.QComboBox(self.groupBox_15)
        self.cmbForjados_23.setGeometry(QtCore.QRect(850, 113, 81, 25))
        self.cmbForjados_23.setObjectName(_fromUtf8("cmbForjados_23"))
        self.cmbForjados_23.addItem(_fromUtf8(""))
        self.cmbForjados_23.addItem(_fromUtf8(""))
        self.cmbForjados_23.addItem(_fromUtf8(""))
        self.cmbForjados_23.addItem(_fromUtf8(""))
        self.label_62 = QtGui.QLabel(self.groupBox_15)
        self.label_62.setGeometry(QtCore.QRect(940, 117, 31, 19))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.cmbForjados_24 = QtGui.QComboBox(self.groupBox_15)
        self.cmbForjados_24.setGeometry(QtCore.QRect(850, 150, 81, 25))
        self.cmbForjados_24.setObjectName(_fromUtf8("cmbForjados_24"))
        self.cmbForjados_24.addItem(_fromUtf8(""))
        self.cmbForjados_24.addItem(_fromUtf8(""))
        self.cmbForjados_24.addItem(_fromUtf8(""))
        self.cmbForjados_24.addItem(_fromUtf8(""))
        self.label_63 = QtGui.QLabel(self.groupBox_15)
        self.label_63.setGeometry(QtCore.QRect(940, 154, 31, 19))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_97 = QtGui.QLabel(self.groupBox_15)
        self.label_97.setGeometry(QtCore.QRect(680, 34, 151, 19))
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.label_98 = QtGui.QLabel(self.groupBox_15)
        self.label_98.setGeometry(QtCore.QRect(680, 73, 151, 19))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.label_99 = QtGui.QLabel(self.groupBox_15)
        self.label_99.setGeometry(QtCore.QRect(680, 113, 151, 19))
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.label_100 = QtGui.QLabel(self.groupBox_15)
        self.label_100.setGeometry(QtCore.QRect(680, 150, 151, 19))
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_16.setGeometry(QtCore.QRect(20, 30, 981, 191))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.label_52 = QtGui.QLabel(self.groupBox_16)
        self.label_52.setGeometry(QtCore.QRect(11, 77, 201, 19))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.cmbCubiertasI_11 = QtGui.QComboBox(self.groupBox_16)
        self.cmbCubiertasI_11.setGeometry(QtCore.QRect(260, 77, 351, 25))
        self.cmbCubiertasI_11.setObjectName(_fromUtf8("cmbCubiertasI_11"))
        self.cmbCubiertasI_11.addItem(_fromUtf8(""))
        self.cmbCubiertasI_11.addItem(_fromUtf8(""))
        self.label_53 = QtGui.QLabel(self.groupBox_16)
        self.label_53.setGeometry(QtCore.QRect(11, 40, 231, 19))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.cmbCubiertasH_11 = QtGui.QComboBox(self.groupBox_16)
        self.cmbCubiertasH_11.setGeometry(QtCore.QRect(260, 40, 351, 25))
        self.cmbCubiertasH_11.setObjectName(_fromUtf8("cmbCubiertasH_11"))
        self.cmbCubiertasH_11.addItem(_fromUtf8(""))
        self.cmbCubiertasH_11.addItem(_fromUtf8(""))
        self.cmbCubiertasI_12 = QtGui.QComboBox(self.groupBox_16)
        self.cmbCubiertasI_12.setGeometry(QtCore.QRect(260, 148, 351, 25))
        self.cmbCubiertasI_12.setObjectName(_fromUtf8("cmbCubiertasI_12"))
        self.cmbCubiertasI_12.addItem(_fromUtf8(""))
        self.cmbCubiertasI_12.addItem(_fromUtf8(""))
        self.label_54 = QtGui.QLabel(self.groupBox_16)
        self.label_54.setGeometry(QtCore.QRect(11, 148, 221, 19))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_55 = QtGui.QLabel(self.groupBox_16)
        self.label_55.setGeometry(QtCore.QRect(11, 114, 241, 19))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.cmbCubiertasH_12 = QtGui.QComboBox(self.groupBox_16)
        self.cmbCubiertasH_12.setGeometry(QtCore.QRect(260, 114, 351, 25))
        self.cmbCubiertasH_12.setObjectName(_fromUtf8("cmbCubiertasH_12"))
        self.cmbCubiertasH_12.addItem(_fromUtf8(""))
        self.cmbCubiertasH_12.addItem(_fromUtf8(""))
        self.cmbForjados_13 = QtGui.QComboBox(self.groupBox_16)
        self.cmbForjados_13.setGeometry(QtCore.QRect(850, 40, 81, 25))
        self.cmbForjados_13.setObjectName(_fromUtf8("cmbForjados_13"))
        self.cmbForjados_13.addItem(_fromUtf8(""))
        self.cmbForjados_13.addItem(_fromUtf8(""))
        self.cmbForjados_13.addItem(_fromUtf8(""))
        self.cmbForjados_13.addItem(_fromUtf8(""))
        self.label_42 = QtGui.QLabel(self.groupBox_16)
        self.label_42.setGeometry(QtCore.QRect(940, 44, 31, 19))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.cmbForjados_14 = QtGui.QComboBox(self.groupBox_16)
        self.cmbForjados_14.setGeometry(QtCore.QRect(850, 77, 81, 25))
        self.cmbForjados_14.setObjectName(_fromUtf8("cmbForjados_14"))
        self.cmbForjados_14.addItem(_fromUtf8(""))
        self.cmbForjados_14.addItem(_fromUtf8(""))
        self.cmbForjados_14.addItem(_fromUtf8(""))
        self.cmbForjados_14.addItem(_fromUtf8(""))
        self.label_43 = QtGui.QLabel(self.groupBox_16)
        self.label_43.setGeometry(QtCore.QRect(940, 81, 31, 19))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.cmbForjados_15 = QtGui.QComboBox(self.groupBox_16)
        self.cmbForjados_15.setGeometry(QtCore.QRect(850, 114, 81, 25))
        self.cmbForjados_15.setObjectName(_fromUtf8("cmbForjados_15"))
        self.cmbForjados_15.addItem(_fromUtf8(""))
        self.cmbForjados_15.addItem(_fromUtf8(""))
        self.cmbForjados_15.addItem(_fromUtf8(""))
        self.cmbForjados_15.addItem(_fromUtf8(""))
        self.label_44 = QtGui.QLabel(self.groupBox_16)
        self.label_44.setGeometry(QtCore.QRect(940, 118, 31, 19))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.groupBox_16)
        self.label_45.setGeometry(QtCore.QRect(940, 152, 31, 19))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.cmbForjados_16 = QtGui.QComboBox(self.groupBox_16)
        self.cmbForjados_16.setGeometry(QtCore.QRect(850, 148, 81, 25))
        self.cmbForjados_16.setObjectName(_fromUtf8("cmbForjados_16"))
        self.cmbForjados_16.addItem(_fromUtf8(""))
        self.cmbForjados_16.addItem(_fromUtf8(""))
        self.cmbForjados_16.addItem(_fromUtf8(""))
        self.cmbForjados_16.addItem(_fromUtf8(""))
        self.label_93 = QtGui.QLabel(self.groupBox_16)
        self.label_93.setGeometry(QtCore.QRect(680, 42, 151, 19))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.label_95 = QtGui.QLabel(self.groupBox_16)
        self.label_95.setGeometry(QtCore.QRect(680, 115, 151, 19))
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.label_96 = QtGui.QLabel(self.groupBox_16)
        self.label_96.setGeometry(QtCore.QRect(680, 148, 151, 19))
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.label_114 = QtGui.QLabel(self.groupBox_16)
        self.label_114.setGeometry(QtCore.QRect(680, 77, 151, 19))
        self.label_114.setObjectName(_fromUtf8("label_114"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.Instalaciones = QtGui.QWidget()
        self.Instalaciones.setObjectName(_fromUtf8("Instalaciones"))
        self.label_66 = QtGui.QLabel(self.Instalaciones)
        self.label_66.setGeometry(QtCore.QRect(950, 110, 31, 19))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_73 = QtGui.QLabel(self.Instalaciones)
        self.label_73.setGeometry(QtCore.QRect(950, 390, 31, 19))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.label_24 = QtGui.QLabel(self.Instalaciones)
        self.label_24.setGeometry(QtCore.QRect(30, 348, 191, 19))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.cmbForjados_25 = QtGui.QComboBox(self.Instalaciones)
        self.cmbForjados_25.setGeometry(QtCore.QRect(860, 26, 81, 25))
        self.cmbForjados_25.setObjectName(_fromUtf8("cmbForjados_25"))
        self.cmbForjados_25.addItem(_fromUtf8(""))
        self.cmbForjados_25.addItem(_fromUtf8(""))
        self.cmbForjados_25.addItem(_fromUtf8(""))
        self.cmbForjados_25.addItem(_fromUtf8(""))
        self.label_110 = QtGui.QLabel(self.Instalaciones)
        self.label_110.setGeometry(QtCore.QRect(680, 431, 151, 19))
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.label_26 = QtGui.QLabel(self.Instalaciones)
        self.label_26.setGeometry(QtCore.QRect(30, 147, 191, 19))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_21 = QtGui.QLabel(self.Instalaciones)
        self.label_21.setGeometry(QtCore.QRect(30, 66, 211, 19))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.cmbCanalizacionesC_3 = QtGui.QComboBox(self.Instalaciones)
        self.cmbCanalizacionesC_3.setGeometry(QtCore.QRect(260, 389, 351, 25))
        self.cmbCanalizacionesC_3.setObjectName(_fromUtf8("cmbCanalizacionesC_3"))
        self.cmbCanalizacionesC_3.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_3.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_3.addItem(_fromUtf8(""))
        self.label_25 = QtGui.QLabel(self.Instalaciones)
        self.label_25.setGeometry(QtCore.QRect(30, 389, 191, 19))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_72 = QtGui.QLabel(self.Instalaciones)
        self.label_72.setGeometry(QtCore.QRect(950, 349, 31, 19))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.cmbForjados_35 = QtGui.QComboBox(self.Instalaciones)
        self.cmbForjados_35.setGeometry(QtCore.QRect(860, 429, 81, 25))
        self.cmbForjados_35.setObjectName(_fromUtf8("cmbForjados_35"))
        self.cmbForjados_35.addItem(_fromUtf8(""))
        self.cmbForjados_35.addItem(_fromUtf8(""))
        self.cmbForjados_35.addItem(_fromUtf8(""))
        self.cmbForjados_35.addItem(_fromUtf8(""))
        self.label_71 = QtGui.QLabel(self.Instalaciones)
        self.label_71.setGeometry(QtCore.QRect(950, 313, 31, 19))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.label_22 = QtGui.QLabel(self.Instalaciones)
        self.label_22.setGeometry(QtCore.QRect(30, 106, 191, 19))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_30 = QtGui.QLabel(self.Instalaciones)
        self.label_30.setGeometry(QtCore.QRect(30, 431, 191, 19))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.cmbCanalizacionesC_8 = QtGui.QComboBox(self.Instalaciones)
        self.cmbCanalizacionesC_8.setGeometry(QtCore.QRect(260, 188, 351, 25))
        self.cmbCanalizacionesC_8.setObjectName(_fromUtf8("cmbCanalizacionesC_8"))
        self.cmbCanalizacionesC_8.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_8.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_8.addItem(_fromUtf8(""))
        self.label_74 = QtGui.QLabel(self.Instalaciones)
        self.label_74.setGeometry(QtCore.QRect(950, 433, 31, 19))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.cmbCanalizacionesC_9 = QtGui.QComboBox(self.Instalaciones)
        self.cmbCanalizacionesC_9.setGeometry(QtCore.QRect(260, 271, 351, 25))
        self.cmbCanalizacionesC_9.setObjectName(_fromUtf8("cmbCanalizacionesC_9"))
        self.cmbCanalizacionesC_9.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_9.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_9.addItem(_fromUtf8(""))
        self.cmbForjados_32 = QtGui.QComboBox(self.Instalaciones)
        self.cmbForjados_32.setGeometry(QtCore.QRect(860, 309, 81, 25))
        self.cmbForjados_32.setObjectName(_fromUtf8("cmbForjados_32"))
        self.cmbForjados_32.addItem(_fromUtf8(""))
        self.cmbForjados_32.addItem(_fromUtf8(""))
        self.cmbForjados_32.addItem(_fromUtf8(""))
        self.cmbForjados_32.addItem(_fromUtf8(""))
        self.label_20 = QtGui.QLabel(self.Instalaciones)
        self.label_20.setGeometry(QtCore.QRect(30, 26, 171, 19))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_108 = QtGui.QLabel(self.Instalaciones)
        self.label_108.setGeometry(QtCore.QRect(680, 348, 151, 19))
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.cmbForjados_34 = QtGui.QComboBox(self.Instalaciones)
        self.cmbForjados_34.setGeometry(QtCore.QRect(860, 386, 81, 25))
        self.cmbForjados_34.setObjectName(_fromUtf8("cmbForjados_34"))
        self.cmbForjados_34.addItem(_fromUtf8(""))
        self.cmbForjados_34.addItem(_fromUtf8(""))
        self.cmbForjados_34.addItem(_fromUtf8(""))
        self.cmbForjados_34.addItem(_fromUtf8(""))
        self.label_103 = QtGui.QLabel(self.Instalaciones)
        self.label_103.setGeometry(QtCore.QRect(680, 147, 151, 19))
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.cmbForjados_30 = QtGui.QComboBox(self.Instalaciones)
        self.cmbForjados_30.setGeometry(QtCore.QRect(860, 225, 81, 25))
        self.cmbForjados_30.setObjectName(_fromUtf8("cmbForjados_30"))
        self.cmbForjados_30.addItem(_fromUtf8(""))
        self.cmbForjados_30.addItem(_fromUtf8(""))
        self.cmbForjados_30.addItem(_fromUtf8(""))
        self.cmbForjados_30.addItem(_fromUtf8(""))
        self.label_68 = QtGui.QLabel(self.Instalaciones)
        self.label_68.setGeometry(QtCore.QRect(950, 190, 31, 19))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.label_64 = QtGui.QLabel(self.Instalaciones)
        self.label_64.setGeometry(QtCore.QRect(950, 30, 31, 19))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_67 = QtGui.QLabel(self.Instalaciones)
        self.label_67.setGeometry(QtCore.QRect(950, 150, 31, 19))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_29 = QtGui.QLabel(self.Instalaciones)
        self.label_29.setGeometry(QtCore.QRect(30, 311, 211, 19))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.cmbCanalizacionesC_10 = QtGui.QComboBox(self.Instalaciones)
        self.cmbCanalizacionesC_10.setGeometry(QtCore.QRect(260, 431, 351, 25))
        self.cmbCanalizacionesC_10.setObjectName(_fromUtf8("cmbCanalizacionesC_10"))
        self.cmbCanalizacionesC_10.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_10.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_10.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_6 = QtGui.QComboBox(self.Instalaciones)
        self.cmbCanalizacionesC_6.setGeometry(QtCore.QRect(260, 147, 351, 25))
        self.cmbCanalizacionesC_6.setObjectName(_fromUtf8("cmbCanalizacionesC_6"))
        self.cmbCanalizacionesC_6.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_6.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_6.addItem(_fromUtf8(""))
        self.label_104 = QtGui.QLabel(self.Instalaciones)
        self.label_104.setGeometry(QtCore.QRect(680, 188, 151, 19))
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.cmbForjados_26 = QtGui.QComboBox(self.Instalaciones)
        self.cmbForjados_26.setGeometry(QtCore.QRect(860, 66, 81, 25))
        self.cmbForjados_26.setObjectName(_fromUtf8("cmbForjados_26"))
        self.cmbForjados_26.addItem(_fromUtf8(""))
        self.cmbForjados_26.addItem(_fromUtf8(""))
        self.cmbForjados_26.addItem(_fromUtf8(""))
        self.cmbForjados_26.addItem(_fromUtf8(""))
        self.label_106 = QtGui.QLabel(self.Instalaciones)
        self.label_106.setGeometry(QtCore.QRect(680, 271, 151, 19))
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.label_94 = QtGui.QLabel(self.Instalaciones)
        self.label_94.setGeometry(QtCore.QRect(680, 26, 151, 19))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.cmbCanalizacionesC_7 = QtGui.QComboBox(self.Instalaciones)
        self.cmbCanalizacionesC_7.setGeometry(QtCore.QRect(260, 228, 351, 25))
        self.cmbCanalizacionesC_7.setObjectName(_fromUtf8("cmbCanalizacionesC_7"))
        self.cmbCanalizacionesC_7.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_7.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_7.addItem(_fromUtf8(""))
        self.cmbForjados_28 = QtGui.QComboBox(self.Instalaciones)
        self.cmbForjados_28.setGeometry(QtCore.QRect(860, 146, 81, 25))
        self.cmbForjados_28.setObjectName(_fromUtf8("cmbForjados_28"))
        self.cmbForjados_28.addItem(_fromUtf8(""))
        self.cmbForjados_28.addItem(_fromUtf8(""))
        self.cmbForjados_28.addItem(_fromUtf8(""))
        self.cmbForjados_28.addItem(_fromUtf8(""))
        self.label_28 = QtGui.QLabel(self.Instalaciones)
        self.label_28.setGeometry(QtCore.QRect(30, 228, 211, 19))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.cmbForjados_27 = QtGui.QComboBox(self.Instalaciones)
        self.cmbForjados_27.setGeometry(QtCore.QRect(860, 106, 81, 25))
        self.cmbForjados_27.setObjectName(_fromUtf8("cmbForjados_27"))
        self.cmbForjados_27.addItem(_fromUtf8(""))
        self.cmbForjados_27.addItem(_fromUtf8(""))
        self.cmbForjados_27.addItem(_fromUtf8(""))
        self.cmbForjados_27.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_4 = QtGui.QComboBox(self.Instalaciones)
        self.cmbCanalizacionesC_4.setGeometry(QtCore.QRect(260, 348, 351, 25))
        self.cmbCanalizacionesC_4.setObjectName(_fromUtf8("cmbCanalizacionesC_4"))
        self.cmbCanalizacionesC_4.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_4.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_4.addItem(_fromUtf8(""))
        self.label_105 = QtGui.QLabel(self.Instalaciones)
        self.label_105.setGeometry(QtCore.QRect(680, 228, 151, 19))
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.label_109 = QtGui.QLabel(self.Instalaciones)
        self.label_109.setGeometry(QtCore.QRect(680, 389, 151, 19))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.label_107 = QtGui.QLabel(self.Instalaciones)
        self.label_107.setGeometry(QtCore.QRect(680, 311, 151, 19))
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.cmbCanalizacionesC_2 = QtGui.QComboBox(self.Instalaciones)
        self.cmbCanalizacionesC_2.setGeometry(QtCore.QRect(260, 106, 351, 25))
        self.cmbCanalizacionesC_2.setObjectName(_fromUtf8("cmbCanalizacionesC_2"))
        self.cmbCanalizacionesC_2.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_2.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_2.addItem(_fromUtf8(""))
        self.label_101 = QtGui.QLabel(self.Instalaciones)
        self.label_101.setGeometry(QtCore.QRect(679, 66, 151, 19))
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.label_27 = QtGui.QLabel(self.Instalaciones)
        self.label_27.setGeometry(QtCore.QRect(30, 188, 211, 19))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_23 = QtGui.QLabel(self.Instalaciones)
        self.label_23.setGeometry(QtCore.QRect(30, 271, 191, 19))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_69 = QtGui.QLabel(self.Instalaciones)
        self.label_69.setGeometry(QtCore.QRect(950, 229, 31, 19))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.label_102 = QtGui.QLabel(self.Instalaciones)
        self.label_102.setGeometry(QtCore.QRect(680, 106, 151, 19))
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.cmbCanalizacionesC = QtGui.QComboBox(self.Instalaciones)
        self.cmbCanalizacionesC.setGeometry(QtCore.QRect(260, 66, 351, 25))
        self.cmbCanalizacionesC.setObjectName(_fromUtf8("cmbCanalizacionesC"))
        self.cmbCanalizacionesC.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC.addItem(_fromUtf8(""))
        self.cmbForjados_33 = QtGui.QComboBox(self.Instalaciones)
        self.cmbForjados_33.setGeometry(QtCore.QRect(860, 345, 81, 25))
        self.cmbForjados_33.setObjectName(_fromUtf8("cmbForjados_33"))
        self.cmbForjados_33.addItem(_fromUtf8(""))
        self.cmbForjados_33.addItem(_fromUtf8(""))
        self.cmbForjados_33.addItem(_fromUtf8(""))
        self.cmbForjados_33.addItem(_fromUtf8(""))
        self.cmbLineas = QtGui.QComboBox(self.Instalaciones)
        self.cmbLineas.setGeometry(QtCore.QRect(260, 26, 351, 25))
        self.cmbLineas.setObjectName(_fromUtf8("cmbLineas"))
        self.cmbLineas.addItem(_fromUtf8(""))
        self.cmbLineas.addItem(_fromUtf8(""))
        self.cmbForjados_31 = QtGui.QComboBox(self.Instalaciones)
        self.cmbForjados_31.setGeometry(QtCore.QRect(860, 269, 81, 25))
        self.cmbForjados_31.setObjectName(_fromUtf8("cmbForjados_31"))
        self.cmbForjados_31.addItem(_fromUtf8(""))
        self.cmbForjados_31.addItem(_fromUtf8(""))
        self.cmbForjados_31.addItem(_fromUtf8(""))
        self.cmbForjados_31.addItem(_fromUtf8(""))
        self.label_70 = QtGui.QLabel(self.Instalaciones)
        self.label_70.setGeometry(QtCore.QRect(950, 273, 31, 19))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.cmbForjados_29 = QtGui.QComboBox(self.Instalaciones)
        self.cmbForjados_29.setGeometry(QtCore.QRect(860, 186, 81, 25))
        self.cmbForjados_29.setObjectName(_fromUtf8("cmbForjados_29"))
        self.cmbForjados_29.addItem(_fromUtf8(""))
        self.cmbForjados_29.addItem(_fromUtf8(""))
        self.cmbForjados_29.addItem(_fromUtf8(""))
        self.cmbForjados_29.addItem(_fromUtf8(""))
        self.label_65 = QtGui.QLabel(self.Instalaciones)
        self.label_65.setGeometry(QtCore.QRect(950, 70, 31, 19))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.cmbCanalizacionesC_5 = QtGui.QComboBox(self.Instalaciones)
        self.cmbCanalizacionesC_5.setGeometry(QtCore.QRect(260, 311, 351, 25))
        self.cmbCanalizacionesC_5.setObjectName(_fromUtf8("cmbCanalizacionesC_5"))
        self.cmbCanalizacionesC_5.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_5.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC_5.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.Instalaciones, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_50 = QtGui.QLabel(self.tab_5)
        self.label_50.setGeometry(QtCore.QRect(40, 80, 231, 19))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.cmbForjados_37 = QtGui.QComboBox(self.tab_5)
        self.cmbForjados_37.setGeometry(QtCore.QRect(870, 79, 81, 25))
        self.cmbForjados_37.setObjectName(_fromUtf8("cmbForjados_37"))
        self.cmbForjados_37.addItem(_fromUtf8(""))
        self.cmbForjados_37.addItem(_fromUtf8(""))
        self.cmbForjados_37.addItem(_fromUtf8(""))
        self.cmbForjados_37.addItem(_fromUtf8(""))
        self.label_113 = QtGui.QLabel(self.tab_5)
        self.label_113.setGeometry(QtCore.QRect(700, 120, 151, 19))
        self.label_113.setObjectName(_fromUtf8("label_113"))
        self.label_77 = QtGui.QLabel(self.tab_5)
        self.label_77.setGeometry(QtCore.QRect(960, 123, 31, 19))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.cmbForjados_38 = QtGui.QComboBox(self.tab_5)
        self.cmbForjados_38.setGeometry(QtCore.QRect(870, 119, 81, 25))
        self.cmbForjados_38.setObjectName(_fromUtf8("cmbForjados_38"))
        self.cmbForjados_38.addItem(_fromUtf8(""))
        self.cmbForjados_38.addItem(_fromUtf8(""))
        self.cmbForjados_38.addItem(_fromUtf8(""))
        self.cmbForjados_38.addItem(_fromUtf8(""))
        self.label_112 = QtGui.QLabel(self.tab_5)
        self.label_112.setGeometry(QtCore.QRect(700, 80, 151, 19))
        self.label_112.setObjectName(_fromUtf8("label_112"))
        self.label_51 = QtGui.QLabel(self.tab_5)
        self.label_51.setGeometry(QtCore.QRect(40, 120, 231, 19))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.cmbBarandillas_3 = QtGui.QComboBox(self.tab_5)
        self.cmbBarandillas_3.setGeometry(QtCore.QRect(200, 120, 421, 25))
        self.cmbBarandillas_3.setObjectName(_fromUtf8("cmbBarandillas_3"))
        self.cmbBarandillas_3.addItem(_fromUtf8(""))
        self.cmbBarandillas_3.addItem(_fromUtf8(""))
        self.cmbBarandillas_3.addItem(_fromUtf8(""))
        self.cmbForjados_36 = QtGui.QComboBox(self.tab_5)
        self.cmbForjados_36.setGeometry(QtCore.QRect(870, 40, 81, 25))
        self.cmbForjados_36.setObjectName(_fromUtf8("cmbForjados_36"))
        self.cmbForjados_36.addItem(_fromUtf8(""))
        self.cmbForjados_36.addItem(_fromUtf8(""))
        self.cmbForjados_36.addItem(_fromUtf8(""))
        self.cmbForjados_36.addItem(_fromUtf8(""))
        self.label_75 = QtGui.QLabel(self.tab_5)
        self.label_75.setGeometry(QtCore.QRect(960, 44, 31, 19))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.cmbBarandillas = QtGui.QComboBox(self.tab_5)
        self.cmbBarandillas.setGeometry(QtCore.QRect(200, 40, 421, 25))
        self.cmbBarandillas.setObjectName(_fromUtf8("cmbBarandillas"))
        self.cmbBarandillas.addItem(_fromUtf8(""))
        self.cmbBarandillas.addItem(_fromUtf8(""))
        self.cmbBarandillas.addItem(_fromUtf8(""))
        self.label_19 = QtGui.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(40, 40, 231, 19))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_111 = QtGui.QLabel(self.tab_5)
        self.label_111.setGeometry(QtCore.QRect(700, 40, 151, 19))
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.cmbBarandillas_2 = QtGui.QComboBox(self.tab_5)
        self.cmbBarandillas_2.setGeometry(QtCore.QRect(200, 80, 421, 25))
        self.cmbBarandillas_2.setObjectName(_fromUtf8("cmbBarandillas_2"))
        self.cmbBarandillas_2.addItem(_fromUtf8(""))
        self.cmbBarandillas_2.addItem(_fromUtf8(""))
        self.label_76 = QtGui.QLabel(self.tab_5)
        self.label_76.setGeometry(QtCore.QRect(960, 83, 31, 19))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        
        self.tbxDireccion.setText(catastroService.getDireccion())
        self.tbxRefCatastral.setText(catastroService.getNumCatastro())

        self.retranslateUi(ActuacionForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ActuacionForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ActuacionForm.reject)
        QtCore.QMetaObject.connectSlotsByName(ActuacionForm)

    def retranslateUi(self, ActuacionForm):
        ActuacionForm.setWindowTitle(_translate("ActuacionForm", "Herevea", None))
        self.label_31.setText(_translate("ActuacionForm", "Direccion", None))
        self.label_32.setText(_translate("ActuacionForm", "Ref. Catastral", None))
        self.cmbEncofrados.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbEncofrados.setItemText(1, _translate("ActuacionForm", "Recalce de zapata mediante pilotes", None))
        self.cmbForjados_17.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_17.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_17.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_17.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_78.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_5.setText(_translate("ActuacionForm", "Pilotes", None))
        self.label_56.setText(_translate("ActuacionForm", "%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ActuacionForm", "Cimentaciones", None))
        self.label_58.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_18.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_18.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_18.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_18.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_59.setText(_translate("ActuacionForm", "%", None))
        self.cmbColectores.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbColectores.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición en polietileno", None))
        self.cmbColectores.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición en hormigón", None))
        self.cmbColectores.setItemText(3, _translate("ActuacionForm", "Sustitución y reposición en fibrocemento NT", None))
        self.label_80.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_57.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_20.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_20.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_20.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_20.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_7.setText(_translate("ActuacionForm", "Arquetas", None))
        self.label_9.setText(_translate("ActuacionForm", "Bajantes", None))
        self.cmbForjados_19.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_19.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_19.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_19.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_79.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_81.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbBajantes.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbBajantes.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición en polipropileno", None))
        self.cmbBajantes.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición en fibrocemento NT", None))
        self.label_8.setText(_translate("ActuacionForm", "Colectores", None))
        self.cmbArquetas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbArquetas.setItemText(1, _translate("ActuacionForm", "Reparación de impermeabilización", None))
        self.cmbArquetas.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.cmbArquetas.setItemText(3, _translate("ActuacionForm", "Arqueta nueva", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ActuacionForm", "Saneamiento", None))
        self.groupBox_11.setTitle(_translate("ActuacionForm", "Distr. Tabiquería (Partic.)", None))
        self.label_18.setText(_translate("ActuacionForm", "Reparación grietas", None))
        self.cmbCubiertasI_2.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasI_2.setItemText(1, _translate("ActuacionForm", "Reparación grietas en superficie ≤60%", None))
        self.cmbCubiertasI_2.setItemText(2, _translate("ActuacionForm", "Reparación grietas en superficie >60% (sustitución y reposición)", None))
        self.label_33.setText(_translate("ActuacionForm", "Repación fisuras", None))
        self.cmbCubiertasH_2.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasH_2.setItemText(1, _translate("ActuacionForm", "Reparación de fisuras", None))
        self.label_3.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_3.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_3.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_3.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_3.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_4.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_4.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_4.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_4.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_4.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_83.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_84.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.groupBox_13.setTitle(_translate("ActuacionForm", "Fcas. Interiores de Ladrillo", None))
        self.label_38.setText(_translate("ActuacionForm", "Reparación grietas", None))
        self.cmbCubiertasI_5.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasI_5.setItemText(1, _translate("ActuacionForm", "Reparación grietas en superficie ≤60%", None))
        self.cmbCubiertasI_5.setItemText(2, _translate("ActuacionForm", "Reparación grietas en superficie >60% (sustitución y reposición)", None))
        self.label_39.setText(_translate("ActuacionForm", "Repación fisuras", None))
        self.cmbCubiertasH_5.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasH_5.setItemText(1, _translate("ActuacionForm", "Reparación de fisuras", None))
        self.cmbCubiertasI_6.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasI_6.setItemText(1, _translate("ActuacionForm", "Reparación humedades filtraciones encuentro de forjado con cerramiento", None))
        self.label_40.setText(_translate("ActuacionForm", "Reparación humedades techo", None))
        self.label_41.setText(_translate("ActuacionForm", "Reparación humedades suelo", None))
        self.cmbCubiertasH_6.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasH_6.setItemText(1, _translate("ActuacionForm", "Reparación humedades capilaridad", None))
        self.cmbForjados_9.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_9.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_9.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_9.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_14.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_10.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_10.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_10.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_10.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_15.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_11.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_11.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_11.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_11.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_16.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_12.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_12.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_12.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_12.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_17.setText(_translate("ActuacionForm", "%", None))
        self.label_89.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_90.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_91.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_92.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.groupBox_4.setTitle(_translate("ActuacionForm", "Estructuras", None))
        self.label_11.setText(_translate("ActuacionForm", "Forjados", None))
        self.cmbForjados.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbForjados.setItemText(1, _translate("ActuacionForm", "Reparación capa compresión", None))
        self.cmbForjados_2.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_2.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_2.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_2.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_2.setText(_translate("ActuacionForm", "%", None))
        self.label_82.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.groupBox_12.setTitle(_translate("ActuacionForm", "Cerramientos de Ladrillo", None))
        self.label_34.setText(_translate("ActuacionForm", "Reparación grietas", None))
        self.cmbCubiertasI_3.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasI_3.setItemText(1, _translate("ActuacionForm", "Reparación grietas en superficie ≤60%", None))
        self.cmbCubiertasI_3.setItemText(2, _translate("ActuacionForm", "Reparación grietas en superficie >60% (sustitución y reposición)", None))
        self.label_35.setText(_translate("ActuacionForm", "Repación fisuras", None))
        self.cmbCubiertasH_3.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasH_3.setItemText(1, _translate("ActuacionForm", "Reparación de fisuras", None))
        self.cmbCubiertasI_4.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasI_4.setItemText(1, _translate("ActuacionForm", "Reparación humedades filtraciones encuentro de forjado con cerramiento", None))
        self.label_36.setText(_translate("ActuacionForm", "Reparación humedades techo", None))
        self.label_37.setText(_translate("ActuacionForm", "Reparación humedades suelo", None))
        self.cmbCubiertasH_4.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasH_4.setItemText(1, _translate("ActuacionForm", "Reparación humedades capilaridad", None))
        self.cmbForjados_5.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_5.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_5.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_5.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_6.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_6.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_6.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_6.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_6.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_10.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_7.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_7.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_7.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_7.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_12.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_8.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_8.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_8.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_8.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_13.setText(_translate("ActuacionForm", "%", None))
        self.label_85.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_86.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_87.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_88.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ActuacionForm", "Albañilería", None))
        self.groupBox_15.setTitle(_translate("ActuacionForm", "Cubiertas inclinadas", None))
        self.label_46.setText(_translate("ActuacionForm", "Faldón", None))
        self.cmbCubiertasI_9.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasI_9.setItemText(1, _translate("ActuacionForm", "Reparación faldón <60%\n"
"", None))
        self.label_47.setText(_translate("ActuacionForm", "Completa", None))
        self.cmbCubiertasH_9.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasH_9.setItemText(1, _translate("ActuacionForm", "Reparación faldón ≥60%, sustitución y reposición con mejora energética.", None))
        self.cmbCubiertasI_10.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasI_10.setItemText(1, _translate("ActuacionForm", "Reparación remates", None))
        self.label_48.setText(_translate("ActuacionForm", "Remates", None))
        self.label_49.setText(_translate("ActuacionForm", "Encuentros paramentos verticales", None))
        self.cmbCubiertasH_10.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasH_10.setItemText(1, _translate("ActuacionForm", "Reparación encuentros paramentos verticales", None))
        self.cmbForjados_21.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_21.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_21.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_21.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_60.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_22.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_22.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_22.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_22.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_61.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_23.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_23.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_23.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_23.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_62.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_24.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_24.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_24.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_24.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_63.setText(_translate("ActuacionForm", "%", None))
        self.label_97.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_98.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_99.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_100.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.groupBox_16.setTitle(_translate("ActuacionForm", "Cubiertas horizontales", None))
        self.label_52.setText(_translate("ActuacionForm", "Faldón", None))
        self.cmbCubiertasI_11.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasI_11.setItemText(1, _translate("ActuacionForm", "Reparación faldón <60%\n"
"", None))
        self.label_53.setText(_translate("ActuacionForm", "Completa", None))
        self.cmbCubiertasH_11.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasH_11.setItemText(1, _translate("ActuacionForm", "Reparación faldón ≥60%, sustitución y reposición con mejora energética.", None))
        self.cmbCubiertasI_12.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasI_12.setItemText(1, _translate("ActuacionForm", "Reparación encuentros cazoletas", None))
        self.label_54.setText(_translate("ActuacionForm", "Encuentros cazoletas", None))
        self.label_55.setText(_translate("ActuacionForm", "Encuentros paramentos verticales", None))
        self.cmbCubiertasH_12.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubiertasH_12.setItemText(1, _translate("ActuacionForm", "Reparación encuentros paramentos verticales", None))
        self.cmbForjados_13.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_13.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_13.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_13.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_42.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_14.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_14.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_14.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_14.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_43.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_15.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_15.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_15.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_15.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_44.setText(_translate("ActuacionForm", "%", None))
        self.label_45.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_16.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_16.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_16.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_16.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_93.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_95.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_96.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_114.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ActuacionForm", "Cubiertas", None))
        self.label_66.setText(_translate("ActuacionForm", "%", None))
        self.label_73.setText(_translate("ActuacionForm", "%", None))
        self.label_24.setText(_translate("ActuacionForm", "Griferías", None))
        self.cmbForjados_25.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_25.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_25.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_25.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_110.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_26.setText(_translate("ActuacionForm", "Toma de corriente", None))
        self.label_21.setText(_translate("ActuacionForm", "Líneas y derivaciones", None))
        self.cmbCanalizacionesC_3.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesC_3.setItemText(1, _translate("ActuacionForm", "Aparatos sanitarios", None))
        self.cmbCanalizacionesC_3.setItemText(2, _translate("ActuacionForm", "Termos/calentadores", None))
        self.label_25.setText(_translate("ActuacionForm", "Aparatos sanitarios", None))
        self.label_72.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_35.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_35.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_35.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_35.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_71.setText(_translate("ActuacionForm", "%", None))
        self.label_22.setText(_translate("ActuacionForm", "Puntos de luz", None))
        self.label_30.setText(_translate("ActuacionForm", "Termos/calentadores", None))
        self.cmbCanalizacionesC_8.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesC_8.setItemText(1, _translate("ActuacionForm", "Aparatos sanitarios", None))
        self.cmbCanalizacionesC_8.setItemText(2, _translate("ActuacionForm", "Termos/calentadores", None))
        self.label_74.setText(_translate("ActuacionForm", "%", None))
        self.cmbCanalizacionesC_9.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesC_9.setItemText(1, _translate("ActuacionForm", "Aparatos sanitarios", None))
        self.cmbCanalizacionesC_9.setItemText(2, _translate("ActuacionForm", "Termos/calentadores", None))
        self.cmbForjados_32.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_32.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_32.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_32.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_20.setText(_translate("ActuacionForm", "Circuitos", None))
        self.label_108.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbForjados_34.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_34.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_34.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_34.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_103.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbForjados_30.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_30.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_30.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_30.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_68.setText(_translate("ActuacionForm", "%", None))
        self.label_64.setText(_translate("ActuacionForm", "%", None))
        self.label_67.setText(_translate("ActuacionForm", "%", None))
        self.label_29.setText(_translate("ActuacionForm", "Canalizaciones agua fría", None))
        self.cmbCanalizacionesC_10.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesC_10.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición con energa solar térmica apoyo con gas", None))
        self.cmbCanalizacionesC_10.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición con energía solar térmica apoyo con electricidad", None))
        self.cmbCanalizacionesC_6.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesC_6.setItemText(1, _translate("ActuacionForm", "Aparatos sanitarios", None))
        self.cmbCanalizacionesC_6.setItemText(2, _translate("ActuacionForm", "Termos/calentadores", None))
        self.label_104.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbForjados_26.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_26.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_26.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_26.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_106.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_94.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbCanalizacionesC_7.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesC_7.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición cobre", None))
        self.cmbCanalizacionesC_7.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición PVC/polietileno", None))
        self.cmbForjados_28.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_28.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_28.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_28.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_28.setText(_translate("ActuacionForm", "Canalizaciones agua caliente", None))
        self.cmbForjados_27.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_27.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_27.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_27.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbCanalizacionesC_4.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesC_4.setItemText(1, _translate("ActuacionForm", "Aparatos sanitarios", None))
        self.cmbCanalizacionesC_4.setItemText(2, _translate("ActuacionForm", "Termos/calentadores", None))
        self.label_105.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_109.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_107.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbCanalizacionesC_2.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesC_2.setItemText(1, _translate("ActuacionForm", "Aparatos sanitarios", None))
        self.cmbCanalizacionesC_2.setItemText(2, _translate("ActuacionForm", "Termos/calentadores", None))
        self.label_101.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_27.setText(_translate("ActuacionForm", "Conductor de puesta a tierra", None))
        self.label_23.setText(_translate("ActuacionForm", "Desagües", None))
        self.label_69.setText(_translate("ActuacionForm", "%", None))
        self.label_102.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbCanalizacionesC.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesC.setItemText(1, _translate("ActuacionForm", "Aparatos sanitarios", None))
        self.cmbCanalizacionesC.setItemText(2, _translate("ActuacionForm", "Termos/calentadores", None))
        self.cmbForjados_33.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_33.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_33.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_33.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbLineas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbLineas.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.cmbForjados_31.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_31.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_31.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_31.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_70.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_29.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_29.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_29.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_29.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_65.setText(_translate("ActuacionForm", "%", None))
        self.cmbCanalizacionesC_5.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesC_5.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición cobre", None))
        self.cmbCanalizacionesC_5.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición PVC/polietileno", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Instalaciones), _translate("ActuacionForm", "Instalaciones", None))
        self.label_50.setText(_translate("ActuacionForm", "Puertas madera", None))
        self.cmbForjados_37.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_37.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_37.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_37.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_113.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_77.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjados_38.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_38.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_38.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_38.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_112.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_51.setText(_translate("ActuacionForm", "Rejas", None))
        self.cmbBarandillas_3.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbBarandillas_3.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.cmbBarandillas_3.setItemText(2, _translate("ActuacionForm", "Desmontado y reutilización", None))
        self.cmbForjados_36.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjados_36.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjados_36.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjados_36.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_75.setText(_translate("ActuacionForm", "%", None))
        self.cmbBarandillas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbBarandillas.setItemText(1, _translate("ActuacionForm", "Ventana abatible+Aluminio RPT+vidrio doble acristalamiento", None))
        self.cmbBarandillas.setItemText(2, _translate("ActuacionForm", "Ventana abatible+PVC+vidrio doble acristalamiento", None))
        self.label_19.setText(_translate("ActuacionForm", "Carpintería ligera", None))
        self.label_111.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbBarandillas_2.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbBarandillas_2.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.label_76.setText(_translate("ActuacionForm", "%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("ActuacionForm", "Carpintería y elementos de seguridad y protección", None))

