# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ActuacionForm.ui'
#
# Created: Wed Sep 23 09:09:12 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActuacionForm(object):
    def setupUi(self, ActuacionForm):
        ActuacionForm.setObjectName(_fromUtf8("ActuacionForm"))
        ActuacionForm.resize(1209, 712)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Herevea.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ActuacionForm.setWindowIcon(icon)
        self.label_31 = QtGui.QLabel(ActuacionForm)
        self.label_31.setGeometry(QtCore.QRect(20, 20, 81, 20))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.tbxDireccion = QtGui.QLineEdit(ActuacionForm)
        self.tbxDireccion.setGeometry(QtCore.QRect(96, 20, 561, 25))
        self.tbxDireccion.setReadOnly(True)
        self.tbxDireccion.setObjectName(_fromUtf8("tbxDireccion"))
        self.tbxRefCatastral = QtGui.QLineEdit(ActuacionForm)
        self.tbxRefCatastral.setGeometry(QtCore.QRect(807, 20, 211, 25))
        self.tbxRefCatastral.setReadOnly(True)
        self.tbxRefCatastral.setObjectName(_fromUtf8("tbxRefCatastral"))
        self.label_32 = QtGui.QLabel(ActuacionForm)
        self.label_32.setGeometry(QtCore.QRect(700, 20, 101, 20))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.groupBox_6 = QtGui.QGroupBox(ActuacionForm)
        self.groupBox_6.setGeometry(QtCore.QRect(9, 69, 1191, 581))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.tabWidget = QtGui.QTabWidget(self.groupBox_6)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 1171, 541))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.cmbPilotes = QtGui.QComboBox(self.tab)
        self.cmbPilotes.setGeometry(QtCore.QRect(240, 35, 521, 25))
        self.cmbPilotes.setObjectName(_fromUtf8("cmbPilotes"))
        self.cmbPilotes.addItem(_fromUtf8(""))
        self.cmbPilotes.addItem(_fromUtf8(""))
        self.cmbPilotesAct = QtGui.QComboBox(self.tab)
        self.cmbPilotesAct.setGeometry(QtCore.QRect(930, 36, 81, 25))
        self.cmbPilotesAct.setObjectName(_fromUtf8("cmbPilotesAct"))
        self.cmbPilotesAct.addItem(_fromUtf8(""))
        self.cmbPilotesAct.addItem(_fromUtf8(""))
        self.cmbPilotesAct.addItem(_fromUtf8(""))
        self.cmbPilotesAct.addItem(_fromUtf8(""))
        self.label_78 = QtGui.QLabel(self.tab)
        self.label_78.setGeometry(QtCore.QRect(780, 38, 151, 19))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 37, 211, 19))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_56 = QtGui.QLabel(self.tab)
        self.label_56.setGeometry(QtCore.QRect(1020, 40, 31, 19))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_58 = QtGui.QLabel(self.tab_2)
        self.label_58.setGeometry(QtCore.QRect(940, 80, 31, 19))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.cmbArquetasAct = QtGui.QComboBox(self.tab_2)
        self.cmbArquetasAct.setGeometry(QtCore.QRect(850, 37, 81, 25))
        self.cmbArquetasAct.setObjectName(_fromUtf8("cmbArquetasAct"))
        self.cmbArquetasAct.addItem(_fromUtf8(""))
        self.cmbArquetasAct.addItem(_fromUtf8(""))
        self.cmbArquetasAct.addItem(_fromUtf8(""))
        self.cmbArquetasAct.addItem(_fromUtf8(""))
        self.label_59 = QtGui.QLabel(self.tab_2)
        self.label_59.setGeometry(QtCore.QRect(940, 120, 31, 19))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.cmbColectores = QtGui.QComboBox(self.tab_2)
        self.cmbColectores.setGeometry(QtCore.QRect(140, 77, 511, 25))
        self.cmbColectores.setObjectName(_fromUtf8("cmbColectores"))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.label_80 = QtGui.QLabel(self.tab_2)
        self.label_80.setGeometry(QtCore.QRect(690, 79, 151, 19))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.label_57 = QtGui.QLabel(self.tab_2)
        self.label_57.setGeometry(QtCore.QRect(940, 41, 31, 19))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.cmbBajantesAct = QtGui.QComboBox(self.tab_2)
        self.cmbBajantesAct.setGeometry(QtCore.QRect(850, 116, 81, 25))
        self.cmbBajantesAct.setObjectName(_fromUtf8("cmbBajantesAct"))
        self.cmbBajantesAct.addItem(_fromUtf8(""))
        self.cmbBajantesAct.addItem(_fromUtf8(""))
        self.cmbBajantesAct.addItem(_fromUtf8(""))
        self.cmbBajantesAct.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(40, 37, 101, 19))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(40, 117, 231, 19))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.cmbColectoresAct = QtGui.QComboBox(self.tab_2)
        self.cmbColectoresAct.setGeometry(QtCore.QRect(850, 76, 81, 25))
        self.cmbColectoresAct.setObjectName(_fromUtf8("cmbColectoresAct"))
        self.cmbColectoresAct.addItem(_fromUtf8(""))
        self.cmbColectoresAct.addItem(_fromUtf8(""))
        self.cmbColectoresAct.addItem(_fromUtf8(""))
        self.cmbColectoresAct.addItem(_fromUtf8(""))
        self.label_79 = QtGui.QLabel(self.tab_2)
        self.label_79.setGeometry(QtCore.QRect(690, 40, 151, 19))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.label_81 = QtGui.QLabel(self.tab_2)
        self.label_81.setGeometry(QtCore.QRect(690, 118, 151, 19))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.cmbBajantes = QtGui.QComboBox(self.tab_2)
        self.cmbBajantes.setGeometry(QtCore.QRect(140, 117, 511, 25))
        self.cmbBajantes.setObjectName(_fromUtf8("cmbBajantes"))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(40, 77, 231, 19))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cmbArquetas = QtGui.QComboBox(self.tab_2)
        self.cmbArquetas.setGeometry(QtCore.QRect(140, 37, 511, 25))
        self.cmbArquetas.setObjectName(_fromUtf8("cmbArquetas"))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.Estructuras = QtGui.QWidget()
        self.Estructuras.setObjectName(_fromUtf8("Estructuras"))
        self.groupBox_4 = QtGui.QGroupBox(self.Estructuras)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 1111, 91))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(20, 36, 231, 19))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.cmbForjados = QtGui.QComboBox(self.groupBox_4)
        self.cmbForjados.setGeometry(QtCore.QRect(250, 36, 531, 25))
        self.cmbForjados.setObjectName(_fromUtf8("cmbForjados"))
        self.cmbForjados.addItem(_fromUtf8(""))
        self.cmbForjados.addItem(_fromUtf8(""))
        self.cmbForjadosAct = QtGui.QComboBox(self.groupBox_4)
        self.cmbForjadosAct.setGeometry(QtCore.QRect(970, 36, 81, 25))
        self.cmbForjadosAct.setObjectName(_fromUtf8("cmbForjadosAct"))
        self.cmbForjadosAct.addItem(_fromUtf8(""))
        self.cmbForjadosAct.addItem(_fromUtf8(""))
        self.cmbForjadosAct.addItem(_fromUtf8(""))
        self.cmbForjadosAct.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(1060, 40, 31, 19))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_82 = QtGui.QLabel(self.groupBox_4)
        self.label_82.setGeometry(QtCore.QRect(819, 38, 151, 19))
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.tabWidget.addTab(self.Estructuras, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 20, 1111, 101))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.label_18 = QtGui.QLabel(self.groupBox_11)
        self.label_18.setGeometry(QtCore.QRect(20, 65, 201, 19))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.cmbGrietas = QtGui.QComboBox(self.groupBox_11)
        self.cmbGrietas.setGeometry(QtCore.QRect(250, 63, 531, 25))
        self.cmbGrietas.setObjectName(_fromUtf8("cmbGrietas"))
        self.cmbGrietas.addItem(_fromUtf8(""))
        self.cmbGrietas.addItem(_fromUtf8(""))
        self.cmbGrietas.addItem(_fromUtf8(""))
        self.label_33 = QtGui.QLabel(self.groupBox_11)
        self.label_33.setGeometry(QtCore.QRect(20, 35, 231, 19))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.cmbFisuras = QtGui.QComboBox(self.groupBox_11)
        self.cmbFisuras.setGeometry(QtCore.QRect(250, 33, 531, 25))
        self.cmbFisuras.setObjectName(_fromUtf8("cmbFisuras"))
        self.cmbFisuras.addItem(_fromUtf8(""))
        self.cmbFisuras.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.groupBox_11)
        self.label_3.setGeometry(QtCore.QRect(1060, 40, 31, 19))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cmbFisurasAct = QtGui.QComboBox(self.groupBox_11)
        self.cmbFisurasAct.setGeometry(QtCore.QRect(970, 36, 81, 25))
        self.cmbFisurasAct.setObjectName(_fromUtf8("cmbFisurasAct"))
        self.cmbFisurasAct.addItem(_fromUtf8(""))
        self.cmbFisurasAct.addItem(_fromUtf8(""))
        self.cmbFisurasAct.addItem(_fromUtf8(""))
        self.cmbFisurasAct.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.groupBox_11)
        self.label_4.setGeometry(QtCore.QRect(1060, 70, 31, 19))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cmbGrietasAct = QtGui.QComboBox(self.groupBox_11)
        self.cmbGrietasAct.setGeometry(QtCore.QRect(970, 66, 81, 25))
        self.cmbGrietasAct.setObjectName(_fromUtf8("cmbGrietasAct"))
        self.cmbGrietasAct.addItem(_fromUtf8(""))
        self.cmbGrietasAct.addItem(_fromUtf8(""))
        self.cmbGrietasAct.addItem(_fromUtf8(""))
        self.cmbGrietasAct.addItem(_fromUtf8(""))
        self.label_83 = QtGui.QLabel(self.groupBox_11)
        self.label_83.setGeometry(QtCore.QRect(819, 37, 151, 19))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.label_84 = QtGui.QLabel(self.groupBox_11)
        self.label_84.setGeometry(QtCore.QRect(820, 67, 151, 19))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 310, 1111, 161))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.label_38 = QtGui.QLabel(self.groupBox_13)
        self.label_38.setGeometry(QtCore.QRect(20, 60, 201, 19))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.cmbIntGrietas = QtGui.QComboBox(self.groupBox_13)
        self.cmbIntGrietas.setGeometry(QtCore.QRect(250, 56, 531, 25))
        self.cmbIntGrietas.setObjectName(_fromUtf8("cmbIntGrietas"))
        self.cmbIntGrietas.addItem(_fromUtf8(""))
        self.cmbIntGrietas.addItem(_fromUtf8(""))
        self.cmbIntGrietas.addItem(_fromUtf8(""))
        self.label_39 = QtGui.QLabel(self.groupBox_13)
        self.label_39.setGeometry(QtCore.QRect(20, 30, 231, 19))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.cmbIntFisuras = QtGui.QComboBox(self.groupBox_13)
        self.cmbIntFisuras.setGeometry(QtCore.QRect(250, 26, 531, 25))
        self.cmbIntFisuras.setObjectName(_fromUtf8("cmbIntFisuras"))
        self.cmbIntFisuras.addItem(_fromUtf8(""))
        self.cmbIntFisuras.addItem(_fromUtf8(""))
        self.cmbHumTecho = QtGui.QComboBox(self.groupBox_13)
        self.cmbHumTecho.setGeometry(QtCore.QRect(250, 116, 531, 25))
        self.cmbHumTecho.setObjectName(_fromUtf8("cmbHumTecho"))
        self.cmbHumTecho.addItem(_fromUtf8(""))
        self.cmbHumTecho.addItem(_fromUtf8(""))
        self.label_40 = QtGui.QLabel(self.groupBox_13)
        self.label_40.setGeometry(QtCore.QRect(20, 120, 221, 19))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.groupBox_13)
        self.label_41.setGeometry(QtCore.QRect(20, 90, 231, 19))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.cmbHumSuelo = QtGui.QComboBox(self.groupBox_13)
        self.cmbHumSuelo.setGeometry(QtCore.QRect(250, 86, 531, 25))
        self.cmbHumSuelo.setObjectName(_fromUtf8("cmbHumSuelo"))
        self.cmbHumSuelo.addItem(_fromUtf8(""))
        self.cmbHumSuelo.addItem(_fromUtf8(""))
        self.cmbIntFisurasAct = QtGui.QComboBox(self.groupBox_13)
        self.cmbIntFisurasAct.setGeometry(QtCore.QRect(970, 26, 81, 25))
        self.cmbIntFisurasAct.setObjectName(_fromUtf8("cmbIntFisurasAct"))
        self.cmbIntFisurasAct.addItem(_fromUtf8(""))
        self.cmbIntFisurasAct.addItem(_fromUtf8(""))
        self.cmbIntFisurasAct.addItem(_fromUtf8(""))
        self.cmbIntFisurasAct.addItem(_fromUtf8(""))
        self.label_14 = QtGui.QLabel(self.groupBox_13)
        self.label_14.setGeometry(QtCore.QRect(1060, 30, 31, 19))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.cmbIntGrietasAct = QtGui.QComboBox(self.groupBox_13)
        self.cmbIntGrietasAct.setGeometry(QtCore.QRect(970, 56, 81, 25))
        self.cmbIntGrietasAct.setObjectName(_fromUtf8("cmbIntGrietasAct"))
        self.cmbIntGrietasAct.addItem(_fromUtf8(""))
        self.cmbIntGrietasAct.addItem(_fromUtf8(""))
        self.cmbIntGrietasAct.addItem(_fromUtf8(""))
        self.cmbIntGrietasAct.addItem(_fromUtf8(""))
        self.label_15 = QtGui.QLabel(self.groupBox_13)
        self.label_15.setGeometry(QtCore.QRect(1060, 60, 31, 19))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.cmbHumSueloAct = QtGui.QComboBox(self.groupBox_13)
        self.cmbHumSueloAct.setGeometry(QtCore.QRect(970, 86, 81, 25))
        self.cmbHumSueloAct.setObjectName(_fromUtf8("cmbHumSueloAct"))
        self.cmbHumSueloAct.addItem(_fromUtf8(""))
        self.cmbHumSueloAct.addItem(_fromUtf8(""))
        self.cmbHumSueloAct.addItem(_fromUtf8(""))
        self.cmbHumSueloAct.addItem(_fromUtf8(""))
        self.label_16 = QtGui.QLabel(self.groupBox_13)
        self.label_16.setGeometry(QtCore.QRect(1060, 90, 31, 19))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.cmbHumTechoAct = QtGui.QComboBox(self.groupBox_13)
        self.cmbHumTechoAct.setGeometry(QtCore.QRect(970, 116, 81, 25))
        self.cmbHumTechoAct.setObjectName(_fromUtf8("cmbHumTechoAct"))
        self.cmbHumTechoAct.addItem(_fromUtf8(""))
        self.cmbHumTechoAct.addItem(_fromUtf8(""))
        self.cmbHumTechoAct.addItem(_fromUtf8(""))
        self.cmbHumTechoAct.addItem(_fromUtf8(""))
        self.label_17 = QtGui.QLabel(self.groupBox_13)
        self.label_17.setGeometry(QtCore.QRect(1060, 120, 31, 19))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_89 = QtGui.QLabel(self.groupBox_13)
        self.label_89.setGeometry(QtCore.QRect(820, 28, 151, 19))
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.label_90 = QtGui.QLabel(self.groupBox_13)
        self.label_90.setGeometry(QtCore.QRect(820, 56, 151, 19))
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.label_91 = QtGui.QLabel(self.groupBox_13)
        self.label_91.setGeometry(QtCore.QRect(820, 86, 151, 19))
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.label_92 = QtGui.QLabel(self.groupBox_13)
        self.label_92.setGeometry(QtCore.QRect(820, 116, 151, 19))
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_12.setGeometry(QtCore.QRect(20, 130, 1111, 171))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.label_34 = QtGui.QLabel(self.groupBox_12)
        self.label_34.setGeometry(QtCore.QRect(20, 60, 201, 19))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.cmbLadGrietas = QtGui.QComboBox(self.groupBox_12)
        self.cmbLadGrietas.setGeometry(QtCore.QRect(250, 60, 531, 25))
        self.cmbLadGrietas.setObjectName(_fromUtf8("cmbLadGrietas"))
        self.cmbLadGrietas.addItem(_fromUtf8(""))
        self.cmbLadGrietas.addItem(_fromUtf8(""))
        self.cmbLadGrietas.addItem(_fromUtf8(""))
        self.label_35 = QtGui.QLabel(self.groupBox_12)
        self.label_35.setGeometry(QtCore.QRect(20, 30, 231, 19))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.cmbLadFisuras = QtGui.QComboBox(self.groupBox_12)
        self.cmbLadFisuras.setGeometry(QtCore.QRect(250, 30, 531, 25))
        self.cmbLadFisuras.setObjectName(_fromUtf8("cmbLadFisuras"))
        self.cmbLadFisuras.addItem(_fromUtf8(""))
        self.cmbLadFisuras.addItem(_fromUtf8(""))
        self.cmbLadHumTecho = QtGui.QComboBox(self.groupBox_12)
        self.cmbLadHumTecho.setGeometry(QtCore.QRect(250, 120, 531, 25))
        self.cmbLadHumTecho.setObjectName(_fromUtf8("cmbLadHumTecho"))
        self.cmbLadHumTecho.addItem(_fromUtf8(""))
        self.cmbLadHumTecho.addItem(_fromUtf8(""))
        self.label_36 = QtGui.QLabel(self.groupBox_12)
        self.label_36.setGeometry(QtCore.QRect(20, 120, 221, 19))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.groupBox_12)
        self.label_37.setGeometry(QtCore.QRect(20, 90, 231, 19))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.cmbLadHumSuelo = QtGui.QComboBox(self.groupBox_12)
        self.cmbLadHumSuelo.setGeometry(QtCore.QRect(250, 90, 531, 25))
        self.cmbLadHumSuelo.setObjectName(_fromUtf8("cmbLadHumSuelo"))
        self.cmbLadHumSuelo.addItem(_fromUtf8(""))
        self.cmbLadHumSuelo.addItem(_fromUtf8(""))
        self.cmbLadFisurasAct = QtGui.QComboBox(self.groupBox_12)
        self.cmbLadFisurasAct.setGeometry(QtCore.QRect(970, 31, 81, 25))
        self.cmbLadFisurasAct.setObjectName(_fromUtf8("cmbLadFisurasAct"))
        self.cmbLadFisurasAct.addItem(_fromUtf8(""))
        self.cmbLadFisurasAct.addItem(_fromUtf8(""))
        self.cmbLadFisurasAct.addItem(_fromUtf8(""))
        self.cmbLadFisurasAct.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.groupBox_12)
        self.label_6.setGeometry(QtCore.QRect(1060, 35, 31, 19))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cmbLadGrietasAct = QtGui.QComboBox(self.groupBox_12)
        self.cmbLadGrietasAct.setGeometry(QtCore.QRect(970, 61, 81, 25))
        self.cmbLadGrietasAct.setObjectName(_fromUtf8("cmbLadGrietasAct"))
        self.cmbLadGrietasAct.addItem(_fromUtf8(""))
        self.cmbLadGrietasAct.addItem(_fromUtf8(""))
        self.cmbLadGrietasAct.addItem(_fromUtf8(""))
        self.cmbLadGrietasAct.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.groupBox_12)
        self.label_10.setGeometry(QtCore.QRect(1060, 65, 31, 19))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.cmbLadHumSueloAct = QtGui.QComboBox(self.groupBox_12)
        self.cmbLadHumSueloAct.setGeometry(QtCore.QRect(970, 91, 81, 25))
        self.cmbLadHumSueloAct.setObjectName(_fromUtf8("cmbLadHumSueloAct"))
        self.cmbLadHumSueloAct.addItem(_fromUtf8(""))
        self.cmbLadHumSueloAct.addItem(_fromUtf8(""))
        self.cmbLadHumSueloAct.addItem(_fromUtf8(""))
        self.cmbLadHumSueloAct.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.groupBox_12)
        self.label_12.setGeometry(QtCore.QRect(1060, 95, 31, 19))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.cmbLadHumTechoAct = QtGui.QComboBox(self.groupBox_12)
        self.cmbLadHumTechoAct.setGeometry(QtCore.QRect(970, 120, 81, 25))
        self.cmbLadHumTechoAct.setObjectName(_fromUtf8("cmbLadHumTechoAct"))
        self.cmbLadHumTechoAct.addItem(_fromUtf8(""))
        self.cmbLadHumTechoAct.addItem(_fromUtf8(""))
        self.cmbLadHumTechoAct.addItem(_fromUtf8(""))
        self.cmbLadHumTechoAct.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(self.groupBox_12)
        self.label_13.setGeometry(QtCore.QRect(1060, 124, 31, 19))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_85 = QtGui.QLabel(self.groupBox_12)
        self.label_85.setGeometry(QtCore.QRect(820, 31, 151, 19))
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.label_86 = QtGui.QLabel(self.groupBox_12)
        self.label_86.setGeometry(QtCore.QRect(820, 61, 151, 19))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.label_87 = QtGui.QLabel(self.groupBox_12)
        self.label_87.setGeometry(QtCore.QRect(820, 91, 151, 19))
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.label_88 = QtGui.QLabel(self.groupBox_12)
        self.label_88.setGeometry(QtCore.QRect(820, 121, 151, 19))
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupCubInc = QtGui.QGroupBox(self.tab_4)
        self.groupCubInc.setGeometry(QtCore.QRect(20, 240, 1121, 211))
        self.groupCubInc.setObjectName(_fromUtf8("groupCubInc"))
        self.label_46 = QtGui.QLabel(self.groupCubInc)
        self.label_46.setGeometry(QtCore.QRect(11, 73, 201, 19))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.cmbCubIncFaldon = QtGui.QComboBox(self.groupCubInc)
        self.cmbCubIncFaldon.setGeometry(QtCore.QRect(270, 73, 521, 25))
        self.cmbCubIncFaldon.setObjectName(_fromUtf8("cmbCubIncFaldon"))
        self.cmbCubIncFaldon.addItem(_fromUtf8(""))
        self.cmbCubIncFaldon.addItem(_fromUtf8(""))
        self.label_47 = QtGui.QLabel(self.groupCubInc)
        self.label_47.setGeometry(QtCore.QRect(11, 34, 231, 19))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.cmbCubIncCompleta = QtGui.QComboBox(self.groupCubInc)
        self.cmbCubIncCompleta.setGeometry(QtCore.QRect(270, 34, 521, 25))
        self.cmbCubIncCompleta.setObjectName(_fromUtf8("cmbCubIncCompleta"))
        self.cmbCubIncCompleta.addItem(_fromUtf8(""))
        self.cmbCubIncCompleta.addItem(_fromUtf8(""))
        self.cmbCubIncRemates = QtGui.QComboBox(self.groupCubInc)
        self.cmbCubIncRemates.setGeometry(QtCore.QRect(270, 113, 521, 25))
        self.cmbCubIncRemates.setObjectName(_fromUtf8("cmbCubIncRemates"))
        self.cmbCubIncRemates.addItem(_fromUtf8(""))
        self.cmbCubIncRemates.addItem(_fromUtf8(""))
        self.label_48 = QtGui.QLabel(self.groupCubInc)
        self.label_48.setGeometry(QtCore.QRect(11, 113, 221, 19))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_49 = QtGui.QLabel(self.groupCubInc)
        self.label_49.setGeometry(QtCore.QRect(11, 150, 241, 19))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.cmbCubIncEncParamVer = QtGui.QComboBox(self.groupCubInc)
        self.cmbCubIncEncParamVer.setGeometry(QtCore.QRect(270, 150, 521, 25))
        self.cmbCubIncEncParamVer.setObjectName(_fromUtf8("cmbCubIncEncParamVer"))
        self.cmbCubIncEncParamVer.addItem(_fromUtf8(""))
        self.cmbCubIncEncParamVer.addItem(_fromUtf8(""))
        self.cmbCubIncCompletaAct = QtGui.QComboBox(self.groupCubInc)
        self.cmbCubIncCompletaAct.setGeometry(QtCore.QRect(1000, 40, 81, 25))
        self.cmbCubIncCompletaAct.setObjectName(_fromUtf8("cmbCubIncCompletaAct"))
        self.cmbCubIncCompletaAct.addItem(_fromUtf8(""))
        self.cmbCubIncCompletaAct.addItem(_fromUtf8(""))
        self.label_60 = QtGui.QLabel(self.groupCubInc)
        self.label_60.setGeometry(QtCore.QRect(1090, 44, 31, 19))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.cmbCubIncFaldonAct = QtGui.QComboBox(self.groupCubInc)
        self.cmbCubIncFaldonAct.setGeometry(QtCore.QRect(1000, 79, 81, 25))
        self.cmbCubIncFaldonAct.setObjectName(_fromUtf8("cmbCubIncFaldonAct"))
        self.cmbCubIncFaldonAct.addItem(_fromUtf8(""))
        self.cmbCubIncFaldonAct.addItem(_fromUtf8(""))
        self.cmbCubIncFaldonAct.addItem(_fromUtf8(""))
        self.cmbCubIncFaldonAct.addItem(_fromUtf8(""))
        self.label_61 = QtGui.QLabel(self.groupCubInc)
        self.label_61.setGeometry(QtCore.QRect(1090, 83, 31, 19))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.cmbCubIncRematesAct = QtGui.QComboBox(self.groupCubInc)
        self.cmbCubIncRematesAct.setGeometry(QtCore.QRect(1000, 119, 81, 25))
        self.cmbCubIncRematesAct.setObjectName(_fromUtf8("cmbCubIncRematesAct"))
        self.cmbCubIncRematesAct.addItem(_fromUtf8(""))
        self.cmbCubIncRematesAct.addItem(_fromUtf8(""))
        self.cmbCubIncRematesAct.addItem(_fromUtf8(""))
        self.cmbCubIncRematesAct.addItem(_fromUtf8(""))
        self.label_62 = QtGui.QLabel(self.groupCubInc)
        self.label_62.setGeometry(QtCore.QRect(1090, 123, 31, 19))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.cmbCubIncEncParamVerAct = QtGui.QComboBox(self.groupCubInc)
        self.cmbCubIncEncParamVerAct.setGeometry(QtCore.QRect(1000, 156, 81, 25))
        self.cmbCubIncEncParamVerAct.setObjectName(_fromUtf8("cmbCubIncEncParamVerAct"))
        self.cmbCubIncEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubIncEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubIncEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubIncEncParamVerAct.addItem(_fromUtf8(""))
        self.label_63 = QtGui.QLabel(self.groupCubInc)
        self.label_63.setGeometry(QtCore.QRect(1090, 160, 31, 19))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_97 = QtGui.QLabel(self.groupCubInc)
        self.label_97.setGeometry(QtCore.QRect(830, 40, 151, 19))
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.label_98 = QtGui.QLabel(self.groupCubInc)
        self.label_98.setGeometry(QtCore.QRect(830, 79, 151, 19))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.label_99 = QtGui.QLabel(self.groupCubInc)
        self.label_99.setGeometry(QtCore.QRect(830, 119, 151, 19))
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.label_100 = QtGui.QLabel(self.groupCubInc)
        self.label_100.setGeometry(QtCore.QRect(830, 156, 151, 19))
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.groupCubHor = QtGui.QGroupBox(self.tab_4)
        self.groupCubHor.setGeometry(QtCore.QRect(20, 30, 1121, 191))
        self.groupCubHor.setObjectName(_fromUtf8("groupCubHor"))
        self.label_52 = QtGui.QLabel(self.groupCubHor)
        self.label_52.setGeometry(QtCore.QRect(11, 77, 201, 19))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.cmbCubHorFaldon = QtGui.QComboBox(self.groupCubHor)
        self.cmbCubHorFaldon.setGeometry(QtCore.QRect(270, 77, 521, 25))
        self.cmbCubHorFaldon.setObjectName(_fromUtf8("cmbCubHorFaldon"))
        self.cmbCubHorFaldon.addItem(_fromUtf8(""))
        self.cmbCubHorFaldon.addItem(_fromUtf8(""))
        self.label_53 = QtGui.QLabel(self.groupCubHor)
        self.label_53.setGeometry(QtCore.QRect(11, 40, 231, 19))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.cmbCubHorCom = QtGui.QComboBox(self.groupCubHor)
        self.cmbCubHorCom.setGeometry(QtCore.QRect(270, 40, 521, 25))
        self.cmbCubHorCom.setObjectName(_fromUtf8("cmbCubHorCom"))
        self.cmbCubHorCom.addItem(_fromUtf8(""))
        self.cmbCubHorCom.addItem(_fromUtf8(""))
        self.cmbCubHorEncCazoletas = QtGui.QComboBox(self.groupCubHor)
        self.cmbCubHorEncCazoletas.setGeometry(QtCore.QRect(270, 148, 521, 25))
        self.cmbCubHorEncCazoletas.setObjectName(_fromUtf8("cmbCubHorEncCazoletas"))
        self.cmbCubHorEncCazoletas.addItem(_fromUtf8(""))
        self.cmbCubHorEncCazoletas.addItem(_fromUtf8(""))
        self.label_54 = QtGui.QLabel(self.groupCubHor)
        self.label_54.setGeometry(QtCore.QRect(11, 148, 221, 19))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_55 = QtGui.QLabel(self.groupCubHor)
        self.label_55.setGeometry(QtCore.QRect(11, 114, 241, 19))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.cmbCubHorEncParamVer = QtGui.QComboBox(self.groupCubHor)
        self.cmbCubHorEncParamVer.setGeometry(QtCore.QRect(270, 114, 521, 25))
        self.cmbCubHorEncParamVer.setObjectName(_fromUtf8("cmbCubHorEncParamVer"))
        self.cmbCubHorEncParamVer.addItem(_fromUtf8(""))
        self.cmbCubHorEncParamVer.addItem(_fromUtf8(""))
        self.cmbCubHorComAct = QtGui.QComboBox(self.groupCubHor)
        self.cmbCubHorComAct.setGeometry(QtCore.QRect(1000, 46, 81, 25))
        self.cmbCubHorComAct.setObjectName(_fromUtf8("cmbCubHorComAct"))
        self.cmbCubHorComAct.addItem(_fromUtf8(""))
        self.cmbCubHorComAct.addItem(_fromUtf8(""))
        self.label_42 = QtGui.QLabel(self.groupCubHor)
        self.label_42.setGeometry(QtCore.QRect(1090, 50, 31, 19))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.cmbCubHorFaldonAct = QtGui.QComboBox(self.groupCubHor)
        self.cmbCubHorFaldonAct.setGeometry(QtCore.QRect(1000, 83, 81, 25))
        self.cmbCubHorFaldonAct.setObjectName(_fromUtf8("cmbCubHorFaldonAct"))
        self.cmbCubHorFaldonAct.addItem(_fromUtf8(""))
        self.cmbCubHorFaldonAct.addItem(_fromUtf8(""))
        self.cmbCubHorFaldonAct.addItem(_fromUtf8(""))
        self.cmbCubHorFaldonAct.addItem(_fromUtf8(""))
        self.label_43 = QtGui.QLabel(self.groupCubHor)
        self.label_43.setGeometry(QtCore.QRect(1090, 87, 31, 19))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.cmbCubHorEncParamVerAct = QtGui.QComboBox(self.groupCubHor)
        self.cmbCubHorEncParamVerAct.setGeometry(QtCore.QRect(1000, 120, 81, 25))
        self.cmbCubHorEncParamVerAct.setObjectName(_fromUtf8("cmbCubHorEncParamVerAct"))
        self.cmbCubHorEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncParamVerAct.addItem(_fromUtf8(""))
        self.label_44 = QtGui.QLabel(self.groupCubHor)
        self.label_44.setGeometry(QtCore.QRect(1090, 124, 31, 19))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.groupCubHor)
        self.label_45.setGeometry(QtCore.QRect(1090, 158, 31, 19))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.cmbCubHorEncCazoletasAct = QtGui.QComboBox(self.groupCubHor)
        self.cmbCubHorEncCazoletasAct.setGeometry(QtCore.QRect(1000, 154, 81, 25))
        self.cmbCubHorEncCazoletasAct.setObjectName(_fromUtf8("cmbCubHorEncCazoletasAct"))
        self.cmbCubHorEncCazoletasAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncCazoletasAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncCazoletasAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncCazoletasAct.addItem(_fromUtf8(""))
        self.label_93 = QtGui.QLabel(self.groupCubHor)
        self.label_93.setGeometry(QtCore.QRect(830, 48, 151, 19))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.label_95 = QtGui.QLabel(self.groupCubHor)
        self.label_95.setGeometry(QtCore.QRect(830, 121, 151, 19))
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.label_96 = QtGui.QLabel(self.groupCubHor)
        self.label_96.setGeometry(QtCore.QRect(830, 154, 151, 19))
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.label_114 = QtGui.QLabel(self.groupCubHor)
        self.label_114.setGeometry(QtCore.QRect(830, 83, 151, 19))
        self.label_114.setObjectName(_fromUtf8("label_114"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.Instalaciones = QtGui.QWidget()
        self.Instalaciones.setObjectName(_fromUtf8("Instalaciones"))
        self.groupBox = QtGui.QGroupBox(self.Instalaciones)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 1131, 171))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.cmbClimatizacion = QtGui.QComboBox(self.groupBox)
        self.cmbClimatizacion.setGeometry(QtCore.QRect(250, 40, 541, 25))
        self.cmbClimatizacion.setObjectName(_fromUtf8("cmbClimatizacion"))
        self.cmbClimatizacion.addItem(_fromUtf8(""))
        self.cmbClimatizacion.addItem(_fromUtf8(""))
        self.cmbClimatizacionAct = QtGui.QComboBox(self.groupBox)
        self.cmbClimatizacionAct.setGeometry(QtCore.QRect(1000, 46, 81, 25))
        self.cmbClimatizacionAct.setObjectName(_fromUtf8("cmbClimatizacionAct"))
        self.cmbClimatizacionAct.addItem(_fromUtf8(""))
        self.cmbClimatizacionAct.addItem(_fromUtf8(""))
        self.cmbClimatizacionAct.addItem(_fromUtf8(""))
        self.cmbClimatizacionAct.addItem(_fromUtf8(""))
        self.label_115 = QtGui.QLabel(self.groupBox)
        self.label_115.setGeometry(QtCore.QRect(1090, 50, 31, 19))
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.label_116 = QtGui.QLabel(self.groupBox)
        self.label_116.setGeometry(QtCore.QRect(30, 40, 171, 19))
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.label_117 = QtGui.QLabel(self.groupBox)
        self.label_117.setGeometry(QtCore.QRect(820, 46, 151, 19))
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.label_118 = QtGui.QLabel(self.groupBox)
        self.label_118.setGeometry(QtCore.QRect(30, 80, 171, 19))
        self.label_118.setObjectName(_fromUtf8("label_118"))
        self.label_119 = QtGui.QLabel(self.groupBox)
        self.label_119.setGeometry(QtCore.QRect(30, 120, 171, 19))
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.label_120 = QtGui.QLabel(self.groupBox)
        self.label_120.setGeometry(QtCore.QRect(1090, 90, 31, 19))
        self.label_120.setObjectName(_fromUtf8("label_120"))
        self.label_121 = QtGui.QLabel(self.groupBox)
        self.label_121.setGeometry(QtCore.QRect(820, 86, 151, 19))
        self.label_121.setObjectName(_fromUtf8("label_121"))
        self.cmbConductosAct = QtGui.QComboBox(self.groupBox)
        self.cmbConductosAct.setGeometry(QtCore.QRect(1000, 86, 81, 25))
        self.cmbConductosAct.setObjectName(_fromUtf8("cmbConductosAct"))
        self.cmbConductosAct.addItem(_fromUtf8(""))
        self.cmbConductosAct.addItem(_fromUtf8(""))
        self.cmbConductosAct.addItem(_fromUtf8(""))
        self.cmbConductosAct.addItem(_fromUtf8(""))
        self.cmbConductos = QtGui.QComboBox(self.groupBox)
        self.cmbConductos.setGeometry(QtCore.QRect(250, 80, 541, 25))
        self.cmbConductos.setObjectName(_fromUtf8("cmbConductos"))
        self.cmbConductos.addItem(_fromUtf8(""))
        self.cmbConductos.addItem(_fromUtf8(""))
        self.label_122 = QtGui.QLabel(self.groupBox)
        self.label_122.setGeometry(QtCore.QRect(1090, 130, 31, 19))
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.label_123 = QtGui.QLabel(self.groupBox)
        self.label_123.setGeometry(QtCore.QRect(820, 126, 151, 19))
        self.label_123.setObjectName(_fromUtf8("label_123"))
        self.cmbRadiadoresAct = QtGui.QComboBox(self.groupBox)
        self.cmbRadiadoresAct.setGeometry(QtCore.QRect(1000, 126, 81, 25))
        self.cmbRadiadoresAct.setObjectName(_fromUtf8("cmbRadiadoresAct"))
        self.cmbRadiadoresAct.addItem(_fromUtf8(""))
        self.cmbRadiadoresAct.addItem(_fromUtf8(""))
        self.cmbRadiadoresAct.addItem(_fromUtf8(""))
        self.cmbRadiadoresAct.addItem(_fromUtf8(""))
        self.cmbRadiadores = QtGui.QComboBox(self.groupBox)
        self.cmbRadiadores.setGeometry(QtCore.QRect(250, 120, 541, 25))
        self.cmbRadiadores.setObjectName(_fromUtf8("cmbRadiadores"))
        self.cmbRadiadores.addItem(_fromUtf8(""))
        self.cmbRadiadores.addItem(_fromUtf8(""))
        self.groupBox_5 = QtGui.QGroupBox(self.Instalaciones)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 230, 1131, 251))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_64 = QtGui.QLabel(self.groupBox_5)
        self.label_64.setGeometry(QtCore.QRect(1090, 40, 31, 19))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_26 = QtGui.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(30, 157, 191, 19))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_102 = QtGui.QLabel(self.groupBox_5)
        self.label_102.setGeometry(QtCore.QRect(820, 116, 151, 19))
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.cmbTomaCorrienteAct = QtGui.QComboBox(self.groupBox_5)
        self.cmbTomaCorrienteAct.setGeometry(QtCore.QRect(1000, 156, 81, 25))
        self.cmbTomaCorrienteAct.setObjectName(_fromUtf8("cmbTomaCorrienteAct"))
        self.cmbTomaCorrienteAct.addItem(_fromUtf8(""))
        self.cmbTomaCorrienteAct.addItem(_fromUtf8(""))
        self.cmbTomaCorrienteAct.addItem(_fromUtf8(""))
        self.cmbTomaCorrienteAct.addItem(_fromUtf8(""))
        self.cmbLineasYDerivaciones = QtGui.QComboBox(self.groupBox_5)
        self.cmbLineasYDerivaciones.setGeometry(QtCore.QRect(250, 76, 541, 25))
        self.cmbLineasYDerivaciones.setObjectName(_fromUtf8("cmbLineasYDerivaciones"))
        self.cmbLineasYDerivaciones.addItem(_fromUtf8(""))
        self.cmbLineasYDerivaciones.addItem(_fromUtf8(""))
        self.cmbTomaCorriente = QtGui.QComboBox(self.groupBox_5)
        self.cmbTomaCorriente.setGeometry(QtCore.QRect(250, 157, 541, 25))
        self.cmbTomaCorriente.setObjectName(_fromUtf8("cmbTomaCorriente"))
        self.cmbTomaCorriente.addItem(_fromUtf8(""))
        self.cmbTomaCorriente.addItem(_fromUtf8(""))
        self.label_101 = QtGui.QLabel(self.groupBox_5)
        self.label_101.setGeometry(QtCore.QRect(819, 76, 151, 19))
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.label_20 = QtGui.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(30, 36, 171, 19))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_103 = QtGui.QLabel(self.groupBox_5)
        self.label_103.setGeometry(QtCore.QRect(820, 157, 151, 19))
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.cmbCircuitos = QtGui.QComboBox(self.groupBox_5)
        self.cmbCircuitos.setGeometry(QtCore.QRect(250, 36, 541, 25))
        self.cmbCircuitos.setObjectName(_fromUtf8("cmbCircuitos"))
        self.cmbCircuitos.addItem(_fromUtf8(""))
        self.cmbCircuitos.addItem(_fromUtf8(""))
        self.cmbConductorPuestaTierraAct = QtGui.QComboBox(self.groupBox_5)
        self.cmbConductorPuestaTierraAct.setGeometry(QtCore.QRect(1000, 196, 81, 25))
        self.cmbConductorPuestaTierraAct.setObjectName(_fromUtf8("cmbConductorPuestaTierraAct"))
        self.cmbConductorPuestaTierraAct.addItem(_fromUtf8(""))
        self.cmbConductorPuestaTierraAct.addItem(_fromUtf8(""))
        self.cmbConductorPuestaTierraAct.addItem(_fromUtf8(""))
        self.cmbConductorPuestaTierraAct.addItem(_fromUtf8(""))
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(30, 116, 191, 19))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.cmbLineasYDerivacionesAct = QtGui.QComboBox(self.groupBox_5)
        self.cmbLineasYDerivacionesAct.setGeometry(QtCore.QRect(1000, 76, 81, 25))
        self.cmbLineasYDerivacionesAct.setObjectName(_fromUtf8("cmbLineasYDerivacionesAct"))
        self.cmbLineasYDerivacionesAct.addItem(_fromUtf8(""))
        self.cmbLineasYDerivacionesAct.addItem(_fromUtf8(""))
        self.cmbLineasYDerivacionesAct.addItem(_fromUtf8(""))
        self.cmbLineasYDerivacionesAct.addItem(_fromUtf8(""))
        self.label_104 = QtGui.QLabel(self.groupBox_5)
        self.label_104.setGeometry(QtCore.QRect(820, 198, 151, 19))
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.label_66 = QtGui.QLabel(self.groupBox_5)
        self.label_66.setGeometry(QtCore.QRect(1090, 120, 31, 19))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(30, 76, 211, 19))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_27 = QtGui.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(30, 198, 211, 19))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.cmbConductorPuestaTierra = QtGui.QComboBox(self.groupBox_5)
        self.cmbConductorPuestaTierra.setGeometry(QtCore.QRect(250, 198, 541, 25))
        self.cmbConductorPuestaTierra.setObjectName(_fromUtf8("cmbConductorPuestaTierra"))
        self.cmbConductorPuestaTierra.addItem(_fromUtf8(""))
        self.cmbConductorPuestaTierra.addItem(_fromUtf8(""))
        self.label_94 = QtGui.QLabel(self.groupBox_5)
        self.label_94.setGeometry(QtCore.QRect(820, 36, 151, 19))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.label_67 = QtGui.QLabel(self.groupBox_5)
        self.label_67.setGeometry(QtCore.QRect(1090, 160, 31, 19))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.cmbPuntosLuz = QtGui.QComboBox(self.groupBox_5)
        self.cmbPuntosLuz.setGeometry(QtCore.QRect(250, 116, 541, 25))
        self.cmbPuntosLuz.setObjectName(_fromUtf8("cmbPuntosLuz"))
        self.cmbPuntosLuz.addItem(_fromUtf8(""))
        self.cmbPuntosLuz.addItem(_fromUtf8(""))
        self.label_68 = QtGui.QLabel(self.groupBox_5)
        self.label_68.setGeometry(QtCore.QRect(1090, 200, 31, 19))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.label_65 = QtGui.QLabel(self.groupBox_5)
        self.label_65.setGeometry(QtCore.QRect(1090, 80, 31, 19))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.cmbCircuitosAct = QtGui.QComboBox(self.groupBox_5)
        self.cmbCircuitosAct.setGeometry(QtCore.QRect(1000, 36, 81, 25))
        self.cmbCircuitosAct.setObjectName(_fromUtf8("cmbCircuitosAct"))
        self.cmbCircuitosAct.addItem(_fromUtf8(""))
        self.cmbCircuitosAct.addItem(_fromUtf8(""))
        self.cmbCircuitosAct.addItem(_fromUtf8(""))
        self.cmbCircuitosAct.addItem(_fromUtf8(""))
        self.cmbPuntosLuzAct = QtGui.QComboBox(self.groupBox_5)
        self.cmbPuntosLuzAct.setGeometry(QtCore.QRect(1000, 116, 81, 25))
        self.cmbPuntosLuzAct.setObjectName(_fromUtf8("cmbPuntosLuzAct"))
        self.cmbPuntosLuzAct.addItem(_fromUtf8(""))
        self.cmbPuntosLuzAct.addItem(_fromUtf8(""))
        self.cmbPuntosLuzAct.addItem(_fromUtf8(""))
        self.cmbPuntosLuzAct.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.Instalaciones, _fromUtf8(""))
        self.InstalacionesII = QtGui.QWidget()
        self.InstalacionesII.setObjectName(_fromUtf8("InstalacionesII"))
        self.groupBox_2 = QtGui.QGroupBox(self.InstalacionesII)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 1111, 301))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_109 = QtGui.QLabel(self.groupBox_2)
        self.label_109.setGeometry(QtCore.QRect(770, 171, 151, 19))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.cmbCanalizacionesAguaFriaAct = QtGui.QComboBox(self.groupBox_2)
        self.cmbCanalizacionesAguaFriaAct.setGeometry(QtCore.QRect(950, 127, 81, 25))
        self.cmbCanalizacionesAguaFriaAct.setObjectName(_fromUtf8("cmbCanalizacionesAguaFriaAct"))
        self.cmbCanalizacionesAguaFriaAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFriaAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFriaAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFriaAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFria = QtGui.QComboBox(self.groupBox_2)
        self.cmbCanalizacionesAguaFria.setGeometry(QtCore.QRect(250, 128, 491, 25))
        self.cmbCanalizacionesAguaFria.setObjectName(_fromUtf8("cmbCanalizacionesAguaFria"))
        self.cmbCanalizacionesAguaFria.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFria.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFria.addItem(_fromUtf8(""))
        self.label_105 = QtGui.QLabel(self.groupBox_2)
        self.label_105.setGeometry(QtCore.QRect(770, 46, 151, 19))
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.label_71 = QtGui.QLabel(self.groupBox_2)
        self.label_71.setGeometry(QtCore.QRect(1040, 131, 31, 19))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.cmbCanalizacionesCal = QtGui.QComboBox(self.groupBox_2)
        self.cmbCanalizacionesCal.setGeometry(QtCore.QRect(250, 45, 491, 25))
        self.cmbCanalizacionesCal.setObjectName(_fromUtf8("cmbCanalizacionesCal"))
        self.cmbCanalizacionesCal.addItem(_fromUtf8(""))
        self.cmbCanalizacionesCal.addItem(_fromUtf8(""))
        self.cmbCanalizacionesCal.addItem(_fromUtf8(""))
        self.label_30 = QtGui.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(30, 212, 191, 19))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(30, 170, 191, 19))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.cmbDesaguesAct = QtGui.QComboBox(self.groupBox_2)
        self.cmbDesaguesAct.setGeometry(QtCore.QRect(950, 87, 81, 25))
        self.cmbDesaguesAct.setObjectName(_fromUtf8("cmbDesaguesAct"))
        self.cmbDesaguesAct.addItem(_fromUtf8(""))
        self.cmbDesaguesAct.addItem(_fromUtf8(""))
        self.cmbDesaguesAct.addItem(_fromUtf8(""))
        self.cmbDesaguesAct.addItem(_fromUtf8(""))
        self.cmbTermosAct = QtGui.QComboBox(self.groupBox_2)
        self.cmbTermosAct.setGeometry(QtCore.QRect(950, 211, 81, 25))
        self.cmbTermosAct.setObjectName(_fromUtf8("cmbTermosAct"))
        self.cmbTermosAct.addItem(_fromUtf8(""))
        self.cmbTermosAct.addItem(_fromUtf8(""))
        self.cmbTermosAct.addItem(_fromUtf8(""))
        self.cmbTermosAct.addItem(_fromUtf8(""))
        self.cmbDesagues = QtGui.QComboBox(self.groupBox_2)
        self.cmbDesagues.setGeometry(QtCore.QRect(250, 88, 491, 25))
        self.cmbDesagues.setObjectName(_fromUtf8("cmbDesagues"))
        self.cmbDesagues.addItem(_fromUtf8(""))
        self.cmbDesagues.addItem(_fromUtf8(""))
        self.label_73 = QtGui.QLabel(self.groupBox_2)
        self.label_73.setGeometry(QtCore.QRect(1040, 172, 31, 19))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.label_74 = QtGui.QLabel(self.groupBox_2)
        self.label_74.setGeometry(QtCore.QRect(1040, 215, 31, 19))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(30, 128, 211, 19))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_110 = QtGui.QLabel(self.groupBox_2)
        self.label_110.setGeometry(QtCore.QRect(770, 213, 151, 19))
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.cmbSanitariosAct = QtGui.QComboBox(self.groupBox_2)
        self.cmbSanitariosAct.setGeometry(QtCore.QRect(950, 168, 81, 25))
        self.cmbSanitariosAct.setObjectName(_fromUtf8("cmbSanitariosAct"))
        self.cmbSanitariosAct.addItem(_fromUtf8(""))
        self.cmbSanitariosAct.addItem(_fromUtf8(""))
        self.cmbSanitariosAct.addItem(_fromUtf8(""))
        self.cmbSanitariosAct.addItem(_fromUtf8(""))
        self.label_106 = QtGui.QLabel(self.groupBox_2)
        self.label_106.setGeometry(QtCore.QRect(770, 89, 151, 19))
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(30, 88, 191, 19))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.cmbTermos = QtGui.QComboBox(self.groupBox_2)
        self.cmbTermos.setGeometry(QtCore.QRect(250, 212, 491, 25))
        self.cmbTermos.setObjectName(_fromUtf8("cmbTermos"))
        self.cmbTermos.addItem(_fromUtf8(""))
        self.cmbTermos.addItem(_fromUtf8(""))
        self.cmbTermos.addItem(_fromUtf8(""))
        self.label_28 = QtGui.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(30, 45, 211, 19))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_107 = QtGui.QLabel(self.groupBox_2)
        self.label_107.setGeometry(QtCore.QRect(770, 129, 151, 19))
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.cmbCanalizacionesCalAct = QtGui.QComboBox(self.groupBox_2)
        self.cmbCanalizacionesCalAct.setGeometry(QtCore.QRect(950, 43, 81, 25))
        self.cmbCanalizacionesCalAct.setObjectName(_fromUtf8("cmbCanalizacionesCalAct"))
        self.cmbCanalizacionesCalAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesCalAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesCalAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesCalAct.addItem(_fromUtf8(""))
        self.label_69 = QtGui.QLabel(self.groupBox_2)
        self.label_69.setGeometry(QtCore.QRect(1040, 47, 31, 19))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.cmbSanitarios = QtGui.QComboBox(self.groupBox_2)
        self.cmbSanitarios.setGeometry(QtCore.QRect(250, 170, 491, 25))
        self.cmbSanitarios.setObjectName(_fromUtf8("cmbSanitarios"))
        self.cmbSanitarios.addItem(_fromUtf8(""))
        self.cmbSanitarios.addItem(_fromUtf8(""))
        self.label_70 = QtGui.QLabel(self.groupBox_2)
        self.label_70.setGeometry(QtCore.QRect(1040, 91, 31, 19))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.tabWidget.addTab(self.InstalacionesII, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_113 = QtGui.QLabel(self.tab_5)
        self.label_113.setGeometry(QtCore.QRect(830, 87, 151, 19))
        self.label_113.setObjectName(_fromUtf8("label_113"))
        self.label_77 = QtGui.QLabel(self.tab_5)
        self.label_77.setGeometry(QtCore.QRect(1090, 90, 31, 19))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.cmbRejasAct = QtGui.QComboBox(self.tab_5)
        self.cmbRejasAct.setGeometry(QtCore.QRect(1000, 86, 81, 25))
        self.cmbRejasAct.setObjectName(_fromUtf8("cmbRejasAct"))
        self.cmbRejasAct.addItem(_fromUtf8(""))
        self.cmbRejasAct.addItem(_fromUtf8(""))
        self.cmbRejasAct.addItem(_fromUtf8(""))
        self.cmbRejasAct.addItem(_fromUtf8(""))
        self.label_51 = QtGui.QLabel(self.tab_5)
        self.label_51.setGeometry(QtCore.QRect(40, 87, 231, 19))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.cmbRejas = QtGui.QComboBox(self.tab_5)
        self.cmbRejas.setGeometry(QtCore.QRect(200, 87, 601, 25))
        self.cmbRejas.setObjectName(_fromUtf8("cmbRejas"))
        self.cmbRejas.addItem(_fromUtf8(""))
        self.cmbRejas.addItem(_fromUtf8(""))
        self.cmbRejas.addItem(_fromUtf8(""))
        self.cmbCarpLigeraAct = QtGui.QComboBox(self.tab_5)
        self.cmbCarpLigeraAct.setGeometry(QtCore.QRect(1000, 40, 81, 25))
        self.cmbCarpLigeraAct.setObjectName(_fromUtf8("cmbCarpLigeraAct"))
        self.cmbCarpLigeraAct.addItem(_fromUtf8(""))
        self.cmbCarpLigeraAct.addItem(_fromUtf8(""))
        self.cmbCarpLigeraAct.addItem(_fromUtf8(""))
        self.cmbCarpLigeraAct.addItem(_fromUtf8(""))
        self.label_75 = QtGui.QLabel(self.tab_5)
        self.label_75.setGeometry(QtCore.QRect(1090, 44, 31, 19))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.cmbCarpLigera = QtGui.QComboBox(self.tab_5)
        self.cmbCarpLigera.setGeometry(QtCore.QRect(200, 40, 601, 25))
        self.cmbCarpLigera.setObjectName(_fromUtf8("cmbCarpLigera"))
        self.cmbCarpLigera.addItem(_fromUtf8(""))
        self.cmbCarpLigera.addItem(_fromUtf8(""))
        self.label_19 = QtGui.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(40, 40, 231, 19))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_111 = QtGui.QLabel(self.tab_5)
        self.label_111.setGeometry(QtCore.QRect(830, 40, 151, 19))
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.spbNumAscensores_4 = QtGui.QSpinBox(self.tab_7)
        self.spbNumAscensores_4.setGeometry(QtCore.QRect(680, 189, 71, 25))
        self.spbNumAscensores_4.setObjectName(_fromUtf8("spbNumAscensores_4"))
        self.label_124 = QtGui.QLabel(self.tab_7)
        self.label_124.setGeometry(QtCore.QRect(640, 56, 31, 19))
        self.label_124.setObjectName(_fromUtf8("label_124"))
        self.spbNumAscensores_3 = QtGui.QSpinBox(self.tab_7)
        self.spbNumAscensores_3.setGeometry(QtCore.QRect(680, 142, 71, 25))
        self.spbNumAscensores_3.setObjectName(_fromUtf8("spbNumAscensores_3"))
        self.label = QtGui.QLabel(self.tab_7)
        self.label.setGeometry(QtCore.QRect(60, 56, 181, 19))
        self.label.setObjectName(_fromUtf8("label"))
        self.spbNumAscensores = QtGui.QSpinBox(self.tab_7)
        self.spbNumAscensores.setGeometry(QtCore.QRect(680, 53, 71, 25))
        self.spbNumAscensores.setObjectName(_fromUtf8("spbNumAscensores"))
        self.spbNumAscensores_2 = QtGui.QSpinBox(self.tab_7)
        self.spbNumAscensores_2.setGeometry(QtCore.QRect(680, 97, 71, 25))
        self.spbNumAscensores_2.setObjectName(_fromUtf8("spbNumAscensores_2"))
        self.label_72 = QtGui.QLabel(self.tab_7)
        self.label_72.setGeometry(QtCore.QRect(60, 192, 261, 19))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.cmbAscensores_3 = QtGui.QComboBox(self.tab_7)
        self.cmbAscensores_3.setGeometry(QtCore.QRect(340, 141, 221, 25))
        self.cmbAscensores_3.setObjectName(_fromUtf8("cmbAscensores_3"))
        self.cmbAscensores_3.addItem(_fromUtf8(""))
        self.cmbAscensores_3.addItem(_fromUtf8(""))
        self.label_127 = QtGui.QLabel(self.tab_7)
        self.label_127.setGeometry(QtCore.QRect(640, 192, 31, 19))
        self.label_127.setObjectName(_fromUtf8("label_127"))
        self.cmbAscensores = QtGui.QComboBox(self.tab_7)
        self.cmbAscensores.setGeometry(QtCore.QRect(340, 52, 221, 25))
        self.cmbAscensores.setObjectName(_fromUtf8("cmbAscensores"))
        self.cmbAscensores.addItem(_fromUtf8(""))
        self.cmbAscensores.addItem(_fromUtf8(""))
        self.label_125 = QtGui.QLabel(self.tab_7)
        self.label_125.setGeometry(QtCore.QRect(640, 100, 31, 19))
        self.label_125.setObjectName(_fromUtf8("label_125"))
        self.label_126 = QtGui.QLabel(self.tab_7)
        self.label_126.setGeometry(QtCore.QRect(640, 145, 31, 19))
        self.label_126.setObjectName(_fromUtf8("label_126"))
        self.cmbAscensores_2 = QtGui.QComboBox(self.tab_7)
        self.cmbAscensores_2.setGeometry(QtCore.QRect(340, 96, 221, 25))
        self.cmbAscensores_2.setObjectName(_fromUtf8("cmbAscensores_2"))
        self.cmbAscensores_2.addItem(_fromUtf8(""))
        self.cmbAscensores_2.addItem(_fromUtf8(""))
        self.label_50 = QtGui.QLabel(self.tab_7)
        self.label_50.setGeometry(QtCore.QRect(60, 145, 261, 19))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.cmbAscensores_4 = QtGui.QComboBox(self.tab_7)
        self.cmbAscensores_4.setGeometry(QtCore.QRect(340, 188, 221, 25))
        self.cmbAscensores_4.setObjectName(_fromUtf8("cmbAscensores_4"))
        self.cmbAscensores_4.addItem(_fromUtf8(""))
        self.cmbAscensores_4.addItem(_fromUtf8(""))
        self.label_24 = QtGui.QLabel(self.tab_7)
        self.label_24.setGeometry(QtCore.QRect(60, 100, 181, 19))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.horizontalLayoutWidget = QtGui.QWidget(ActuacionForm)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(860, 660, 331, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.btnAccept = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnAccept.setDefault(True)
        self.btnAccept.setObjectName(_fromUtf8("btnAccept"))
        self.horizontalLayout.addWidget(self.btnAccept)

        self.retranslateUi(ActuacionForm)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(ActuacionForm)

    def retranslateUi(self, ActuacionForm):
        ActuacionForm.setWindowTitle(_translate("ActuacionForm", "Herevea", None))
        self.label_31.setText(_translate("ActuacionForm", "Direccion", None))
        self.label_32.setText(_translate("ActuacionForm", "Ref. Catastral", None))
        self.groupBox_6.setTitle(_translate("ActuacionForm", "Actuaciones a realizar", None))
        self.cmbPilotes.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbPilotes.setItemText(1, _translate("ActuacionForm", "Recalce de zapata mediante micropilotes", None))
        self.cmbPilotesAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbPilotesAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbPilotesAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbPilotesAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_78.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_5.setText(_translate("ActuacionForm", "Reparación por micropilotes", None))
        self.label_56.setText(_translate("ActuacionForm", "%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ActuacionForm", "Cimentaciones", None))
        self.label_58.setText(_translate("ActuacionForm", "%", None))
        self.cmbArquetasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbArquetasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbArquetasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbArquetasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_59.setText(_translate("ActuacionForm", "%", None))
        self.cmbColectores.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbColectores.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición en polietileno", None))
        self.cmbColectores.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición en hormigón", None))
        self.cmbColectores.setItemText(3, _translate("ActuacionForm", "Sustitución y reposición en fibrocemento NT", None))
        self.label_80.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_57.setText(_translate("ActuacionForm", "%", None))
        self.cmbBajantesAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbBajantesAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbBajantesAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbBajantesAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_7.setText(_translate("ActuacionForm", "Arquetas", None))
        self.label_9.setText(_translate("ActuacionForm", "Bajantes", None))
        self.cmbColectoresAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbColectoresAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbColectoresAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbColectoresAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_79.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_81.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbBajantes.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbBajantes.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición en polipropileno", None))
        self.cmbBajantes.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición en fibrocemento NT", None))
        self.label_8.setText(_translate("ActuacionForm", "Colectores", None))
        self.cmbArquetas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbArquetas.setItemText(1, _translate("ActuacionForm", "Reparación de impermeabilización", None))
        self.cmbArquetas.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.cmbArquetas.setItemText(3, _translate("ActuacionForm", "Arqueta nueva", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ActuacionForm", "Saneamiento", None))
        self.groupBox_4.setTitle(_translate("ActuacionForm", "Estructuras", None))
        self.label_11.setText(_translate("ActuacionForm", "Forjados", None))
        self.cmbForjados.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbForjados.setItemText(1, _translate("ActuacionForm", "Reparación capa compresión", None))
        self.cmbForjadosAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjadosAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjadosAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjadosAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_2.setText(_translate("ActuacionForm", "%", None))
        self.label_82.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Estructuras), _translate("ActuacionForm", "Estructuras", None))
        self.groupBox_11.setTitle(_translate("ActuacionForm", "Distr. Tabiquería (Partic.)", None))
        self.label_18.setText(_translate("ActuacionForm", "Reparación grietas", None))
        self.cmbGrietas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbGrietas.setItemText(1, _translate("ActuacionForm", "Reparación grietas en superficie ≤60%", None))
        self.cmbGrietas.setItemText(2, _translate("ActuacionForm", "Reparación grietas en superficie >60% (sustitución y reposición)", None))
        self.label_33.setText(_translate("ActuacionForm", "Reparación fisuras", None))
        self.cmbFisuras.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbFisuras.setItemText(1, _translate("ActuacionForm", "Reparación de fisuras", None))
        self.label_3.setText(_translate("ActuacionForm", "%", None))
        self.cmbFisurasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbFisurasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbFisurasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbFisurasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_4.setText(_translate("ActuacionForm", "%", None))
        self.cmbGrietasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbGrietasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbGrietasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbGrietasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_83.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_84.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.groupBox_13.setTitle(_translate("ActuacionForm", "Fcas. Interiores de Ladrillo", None))
        self.label_38.setText(_translate("ActuacionForm", "Reparación grietas", None))
        self.cmbIntGrietas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbIntGrietas.setItemText(1, _translate("ActuacionForm", "Reparación grietas en superficie ≤60%", None))
        self.cmbIntGrietas.setItemText(2, _translate("ActuacionForm", "Reparación grietas en superficie >60% (sustitución y reposición)", None))
        self.label_39.setText(_translate("ActuacionForm", "Reparación fisuras", None))
        self.cmbIntFisuras.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbIntFisuras.setItemText(1, _translate("ActuacionForm", "Reparación de fisuras", None))
        self.cmbHumTecho.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbHumTecho.setItemText(1, _translate("ActuacionForm", "Reparación humedades filtraciones encuentro de forjado con cerramiento", None))
        self.label_40.setText(_translate("ActuacionForm", "Reparación humedades techo", None))
        self.label_41.setText(_translate("ActuacionForm", "Reparación humedades suelo", None))
        self.cmbHumSuelo.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbHumSuelo.setItemText(1, _translate("ActuacionForm", "Reparación humedades capilaridad", None))
        self.cmbIntFisurasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbIntFisurasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbIntFisurasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbIntFisurasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_14.setText(_translate("ActuacionForm", "%", None))
        self.cmbIntGrietasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbIntGrietasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbIntGrietasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbIntGrietasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_15.setText(_translate("ActuacionForm", "%", None))
        self.cmbHumSueloAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbHumSueloAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbHumSueloAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbHumSueloAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_16.setText(_translate("ActuacionForm", "%", None))
        self.cmbHumTechoAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbHumTechoAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbHumTechoAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbHumTechoAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_17.setText(_translate("ActuacionForm", "%", None))
        self.label_89.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_90.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_91.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_92.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.groupBox_12.setTitle(_translate("ActuacionForm", "Cerramientos de Ladrillo", None))
        self.label_34.setText(_translate("ActuacionForm", "Reparación grietas", None))
        self.cmbLadGrietas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbLadGrietas.setItemText(1, _translate("ActuacionForm", "Reparación grietas en superficie ≤60%", None))
        self.cmbLadGrietas.setItemText(2, _translate("ActuacionForm", "Reparación grietas en superficie >60% (sustitución y reposición)", None))
        self.label_35.setText(_translate("ActuacionForm", "Reparación fisuras", None))
        self.cmbLadFisuras.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbLadFisuras.setItemText(1, _translate("ActuacionForm", "Reparación de fisuras", None))
        self.cmbLadHumTecho.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbLadHumTecho.setItemText(1, _translate("ActuacionForm", "Reparación humedades filtraciones encuentro de forjado con cerramiento", None))
        self.label_36.setText(_translate("ActuacionForm", "Reparación humedades techo", None))
        self.label_37.setText(_translate("ActuacionForm", "Reparación humedades suelo", None))
        self.cmbLadHumSuelo.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbLadHumSuelo.setItemText(1, _translate("ActuacionForm", "Reparación humedades capilaridad", None))
        self.cmbLadFisurasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbLadFisurasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbLadFisurasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbLadFisurasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_6.setText(_translate("ActuacionForm", "%", None))
        self.cmbLadGrietasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbLadGrietasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbLadGrietasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbLadGrietasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_10.setText(_translate("ActuacionForm", "%", None))
        self.cmbLadHumSueloAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbLadHumSueloAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbLadHumSueloAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbLadHumSueloAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_12.setText(_translate("ActuacionForm", "%", None))
        self.cmbLadHumTechoAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbLadHumTechoAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbLadHumTechoAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbLadHumTechoAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_13.setText(_translate("ActuacionForm", "%", None))
        self.label_85.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_86.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_87.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_88.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ActuacionForm", "Albañilería", None))
        self.groupCubInc.setTitle(_translate("ActuacionForm", "Cubiertas inclinadas", None))
        self.label_46.setText(_translate("ActuacionForm", "Faldón", None))
        self.cmbCubIncFaldon.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubIncFaldon.setItemText(1, _translate("ActuacionForm", "Reparación faldón <60%\n"
"", None))
        self.label_47.setText(_translate("ActuacionForm", "Completa", None))
        self.cmbCubIncCompleta.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubIncCompleta.setItemText(1, _translate("ActuacionForm", "Reparación faldón ≥60%, sustitución y reposición con mejora energética.", None))
        self.cmbCubIncRemates.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubIncRemates.setItemText(1, _translate("ActuacionForm", "Reparación remates", None))
        self.label_48.setText(_translate("ActuacionForm", "Remates", None))
        self.label_49.setText(_translate("ActuacionForm", "Encuentros paramentos verticales", None))
        self.cmbCubIncEncParamVer.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubIncEncParamVer.setItemText(1, _translate("ActuacionForm", "Reparación encuentros paramentos verticales", None))
        self.cmbCubIncCompletaAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubIncCompletaAct.setItemText(1, _translate("ActuacionForm", "61 a 100", None))
        self.label_60.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubIncFaldonAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubIncFaldonAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCubIncFaldonAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCubIncFaldonAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_61.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubIncRematesAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubIncRematesAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCubIncRematesAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCubIncRematesAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_62.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubIncEncParamVerAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubIncEncParamVerAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCubIncEncParamVerAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCubIncEncParamVerAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_63.setText(_translate("ActuacionForm", "%", None))
        self.label_97.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_98.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_99.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_100.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.groupCubHor.setTitle(_translate("ActuacionForm", "Cubiertas horizontales", None))
        self.label_52.setText(_translate("ActuacionForm", "Faldón", None))
        self.cmbCubHorFaldon.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubHorFaldon.setItemText(1, _translate("ActuacionForm", "Reparación faldón <60%\n"
"", None))
        self.label_53.setText(_translate("ActuacionForm", "Completa", None))
        self.cmbCubHorCom.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubHorCom.setItemText(1, _translate("ActuacionForm", "Reparación faldón ≥60%, sustitución y reposición con mejora energética.", None))
        self.cmbCubHorEncCazoletas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubHorEncCazoletas.setItemText(1, _translate("ActuacionForm", "Reparación encuentros cazoletas", None))
        self.label_54.setText(_translate("ActuacionForm", "Encuentros cazoletas", None))
        self.label_55.setText(_translate("ActuacionForm", "Encuentros paramentos verticales", None))
        self.cmbCubHorEncParamVer.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubHorEncParamVer.setItemText(1, _translate("ActuacionForm", "Reparación encuentros paramentos verticales", None))
        self.cmbCubHorComAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubHorComAct.setItemText(1, _translate("ActuacionForm", "61 a 100", None))
        self.label_42.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubHorFaldonAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubHorFaldonAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCubHorFaldonAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCubHorFaldonAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_43.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubHorEncParamVerAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubHorEncParamVerAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCubHorEncParamVerAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCubHorEncParamVerAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_44.setText(_translate("ActuacionForm", "%", None))
        self.label_45.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubHorEncCazoletasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubHorEncCazoletasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCubHorEncCazoletasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCubHorEncCazoletasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_93.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_95.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_96.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_114.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ActuacionForm", "Cubiertas", None))
        self.groupBox.setTitle(_translate("ActuacionForm", "Climatización", None))
        self.cmbClimatizacion.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbClimatizacion.setItemText(1, _translate("ActuacionForm", "Nueva instalación", None))
        self.cmbClimatizacionAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbClimatizacionAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbClimatizacionAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbClimatizacionAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_115.setText(_translate("ActuacionForm", "%", None))
        self.label_116.setText(_translate("ActuacionForm", "Aparatos climatización", None))
        self.label_117.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_118.setText(_translate("ActuacionForm", "Conductos", None))
        self.label_119.setText(_translate("ActuacionForm", "Radiadores", None))
        self.label_120.setText(_translate("ActuacionForm", "%", None))
        self.label_121.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbConductosAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbConductosAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbConductosAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbConductosAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbConductos.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbConductos.setItemText(1, _translate("ActuacionForm", "Nueva instalación", None))
        self.label_122.setText(_translate("ActuacionForm", "%", None))
        self.label_123.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbRadiadoresAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbRadiadoresAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbRadiadoresAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbRadiadoresAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbRadiadores.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbRadiadores.setItemText(1, _translate("ActuacionForm", "Nueva instalación", None))
        self.groupBox_5.setTitle(_translate("ActuacionForm", "Electricidad", None))
        self.label_64.setText(_translate("ActuacionForm", "%", None))
        self.label_26.setText(_translate("ActuacionForm", "Toma de corriente", None))
        self.label_102.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbTomaCorrienteAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbTomaCorrienteAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbTomaCorrienteAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbTomaCorrienteAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbLineasYDerivaciones.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbLineasYDerivaciones.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.cmbTomaCorriente.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbTomaCorriente.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.label_101.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_20.setText(_translate("ActuacionForm", "Circuitos", None))
        self.label_103.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbCircuitos.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCircuitos.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.cmbConductorPuestaTierraAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbConductorPuestaTierraAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbConductorPuestaTierraAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbConductorPuestaTierraAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_22.setText(_translate("ActuacionForm", "Puntos de luz", None))
        self.cmbLineasYDerivacionesAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbLineasYDerivacionesAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbLineasYDerivacionesAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbLineasYDerivacionesAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_104.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_66.setText(_translate("ActuacionForm", "%", None))
        self.label_21.setText(_translate("ActuacionForm", "Líneas y derivaciones", None))
        self.label_27.setText(_translate("ActuacionForm", "Conductor de puesta a tierra", None))
        self.cmbConductorPuestaTierra.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbConductorPuestaTierra.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.label_94.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_67.setText(_translate("ActuacionForm", "%", None))
        self.cmbPuntosLuz.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbPuntosLuz.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.label_68.setText(_translate("ActuacionForm", "%", None))
        self.label_65.setText(_translate("ActuacionForm", "%", None))
        self.cmbCircuitosAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCircuitosAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCircuitosAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCircuitosAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbPuntosLuzAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbPuntosLuzAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbPuntosLuzAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbPuntosLuzAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Instalaciones), _translate("ActuacionForm", "Instalaciones I", None))
        self.groupBox_2.setTitle(_translate("ActuacionForm", "Fontanería", None))
        self.label_109.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbCanalizacionesAguaFriaAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCanalizacionesAguaFriaAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCanalizacionesAguaFriaAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCanalizacionesAguaFriaAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbCanalizacionesAguaFria.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesAguaFria.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición cobre", None))
        self.cmbCanalizacionesAguaFria.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición PVC/polietileno", None))
        self.label_105.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_71.setText(_translate("ActuacionForm", "%", None))
        self.cmbCanalizacionesCal.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesCal.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición cobre", None))
        self.cmbCanalizacionesCal.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición PVC/polietileno", None))
        self.label_30.setText(_translate("ActuacionForm", "Termos/calentadores", None))
        self.label_25.setText(_translate("ActuacionForm", "Aparatos sanitarios", None))
        self.cmbDesaguesAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbDesaguesAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbDesaguesAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbDesaguesAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbTermosAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbTermosAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbTermosAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbTermosAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbDesagues.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbDesagues.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.label_73.setText(_translate("ActuacionForm", "%", None))
        self.label_74.setText(_translate("ActuacionForm", "%", None))
        self.label_29.setText(_translate("ActuacionForm", "Canalizaciones agua fría", None))
        self.label_110.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbSanitariosAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbSanitariosAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbSanitariosAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbSanitariosAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_106.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_23.setText(_translate("ActuacionForm", "Desagües", None))
        self.cmbTermos.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbTermos.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición con energa solar térmica apoyo con gas", None))
        self.cmbTermos.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición con energía solar térmica apoyo con electricidad", None))
        self.label_28.setText(_translate("ActuacionForm", "Canalizaciones agua caliente", None))
        self.label_107.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbCanalizacionesCalAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCanalizacionesCalAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCanalizacionesCalAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCanalizacionesCalAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_69.setText(_translate("ActuacionForm", "%", None))
        self.cmbSanitarios.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbSanitarios.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.label_70.setText(_translate("ActuacionForm", "%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InstalacionesII), _translate("ActuacionForm", "Instalaciones II", None))
        self.label_113.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_77.setText(_translate("ActuacionForm", "%", None))
        self.cmbRejasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbRejasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbRejasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbRejasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_51.setText(_translate("ActuacionForm", "Rejas", None))
        self.cmbRejas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbRejas.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.cmbRejas.setItemText(2, _translate("ActuacionForm", "Desmontado y reutilización", None))
        self.cmbCarpLigeraAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCarpLigeraAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCarpLigeraAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCarpLigeraAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_75.setText(_translate("ActuacionForm", "%", None))
        self.cmbCarpLigera.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCarpLigera.setItemText(1, _translate("ActuacionForm", "Ventana abatible+Aluminio RPT+vidrio doble acristalamiento", None))
        self.label_19.setText(_translate("ActuacionForm", "Carpintería ligera", None))
        self.label_111.setText(_translate("ActuacionForm", "Grado de actuación", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("ActuacionForm", "Carpintería y elem. de seguridad y protección", None))
        self.label_124.setText(_translate("ActuacionForm", "Nº", None))
        self.label.setText(_translate("ActuacionForm", "Ascensores nuevos", None))
        self.label_72.setText(_translate("ActuacionForm", "Instalación de portero automático", None))
        self.cmbAscensores_3.setItemText(0, _translate("ActuacionForm", "No", None))
        self.cmbAscensores_3.setItemText(1, _translate("ActuacionForm", "Sí", None))
        self.label_127.setText(_translate("ActuacionForm", "Nº", None))
        self.cmbAscensores.setItemText(0, _translate("ActuacionForm", "No", None))
        self.cmbAscensores.setItemText(1, _translate("ActuacionForm", "Sí", None))
        self.label_125.setText(_translate("ActuacionForm", "Nº", None))
        self.label_126.setText(_translate("ActuacionForm", "Nº", None))
        self.cmbAscensores_2.setItemText(0, _translate("ActuacionForm", "No", None))
        self.cmbAscensores_2.setItemText(1, _translate("ActuacionForm", "Sí", None))
        self.label_50.setText(_translate("ActuacionForm", "Rampa de acceso a minusválidos", None))
        self.cmbAscensores_4.setItemText(0, _translate("ActuacionForm", "No", None))
        self.cmbAscensores_4.setItemText(1, _translate("ActuacionForm", "Sí", None))
        self.label_24.setText(_translate("ActuacionForm", "Escalera", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("ActuacionForm", "Accesibilidad", None))
        self.pushButton.setText(_translate("ActuacionForm", "< Atrás", None))
        self.btnAccept.setText(_translate("ActuacionForm", "Calculo de Huella Ecológica", None))

