# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ActuacionForm.ui'
#
# Created: Sat Sep 26 18:21:44 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActuacionForm(object):
    def setupUi(self, ActuacionForm):
        ActuacionForm.setObjectName(_fromUtf8("ActuacionForm"))
        ActuacionForm.resize(1209, 712)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Herevea.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ActuacionForm.setWindowIcon(icon)
        self.label_31 = QtGui.QLabel(ActuacionForm)
        self.label_31.setGeometry(QtCore.QRect(20, 20, 81, 20))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.tbxDireccion = QtGui.QLineEdit(ActuacionForm)
        self.tbxDireccion.setGeometry(QtCore.QRect(96, 20, 561, 25))
        self.tbxDireccion.setReadOnly(True)
        self.tbxDireccion.setObjectName(_fromUtf8("tbxDireccion"))
        self.tbxRefCatastral = QtGui.QLineEdit(ActuacionForm)
        self.tbxRefCatastral.setGeometry(QtCore.QRect(807, 20, 211, 25))
        self.tbxRefCatastral.setReadOnly(True)
        self.tbxRefCatastral.setObjectName(_fromUtf8("tbxRefCatastral"))
        self.label_32 = QtGui.QLabel(ActuacionForm)
        self.label_32.setGeometry(QtCore.QRect(700, 20, 101, 20))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.groupBox_6 = QtGui.QGroupBox(ActuacionForm)
        self.groupBox_6.setGeometry(QtCore.QRect(9, 69, 1191, 581))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.tabWidget = QtGui.QTabWidget(self.groupBox_6)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 1171, 541))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 811, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.cmbPilotes = QtGui.QComboBox(self.groupBox_3)
        self.cmbPilotes.setGeometry(QtCore.QRect(300, 38, 481, 25))
        self.cmbPilotes.setObjectName(_fromUtf8("cmbPilotes"))
        self.cmbPilotes.addItem(_fromUtf8(""))
        self.cmbPilotes.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(30, 40, 281, 19))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(840, 20, 261, 91))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_56 = QtGui.QLabel(self.groupBox_7)
        self.label_56.setGeometry(QtCore.QRect(160, 40, 31, 19))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.cmbPilotesAct = QtGui.QComboBox(self.groupBox_7)
        self.cmbPilotesAct.setGeometry(QtCore.QRect(40, 36, 91, 25))
        self.cmbPilotesAct.setObjectName(_fromUtf8("cmbPilotesAct"))
        self.cmbPilotesAct.addItem(_fromUtf8(""))
        self.cmbPilotesAct.addItem(_fromUtf8(""))
        self.cmbPilotesAct.addItem(_fromUtf8(""))
        self.cmbPilotesAct.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(30, 30, 801, 181))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.cmbBajantes = QtGui.QComboBox(self.groupBox_8)
        self.cmbBajantes.setGeometry(QtCore.QRect(170, 120, 581, 25))
        self.cmbBajantes.setObjectName(_fromUtf8("cmbBajantes"))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.cmbArquetas = QtGui.QComboBox(self.groupBox_8)
        self.cmbArquetas.setGeometry(QtCore.QRect(170, 40, 581, 25))
        self.cmbArquetas.setObjectName(_fromUtf8("cmbArquetas"))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.label_9 = QtGui.QLabel(self.groupBox_8)
        self.label_9.setGeometry(QtCore.QRect(40, 120, 231, 19))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_8 = QtGui.QLabel(self.groupBox_8)
        self.label_8.setGeometry(QtCore.QRect(40, 80, 231, 19))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setGeometry(QtCore.QRect(40, 40, 131, 19))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cmbColectores = QtGui.QComboBox(self.groupBox_8)
        self.cmbColectores.setGeometry(QtCore.QRect(170, 80, 581, 25))
        self.cmbColectores.setObjectName(_fromUtf8("cmbColectores"))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(850, 30, 251, 181))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_59 = QtGui.QLabel(self.groupBox_9)
        self.label_59.setGeometry(QtCore.QRect(130, 123, 31, 19))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.cmbColectoresAct = QtGui.QComboBox(self.groupBox_9)
        self.cmbColectoresAct.setGeometry(QtCore.QRect(40, 79, 81, 25))
        self.cmbColectoresAct.setObjectName(_fromUtf8("cmbColectoresAct"))
        self.cmbColectoresAct.addItem(_fromUtf8(""))
        self.cmbColectoresAct.addItem(_fromUtf8(""))
        self.cmbColectoresAct.addItem(_fromUtf8(""))
        self.cmbColectoresAct.addItem(_fromUtf8(""))
        self.label_57 = QtGui.QLabel(self.groupBox_9)
        self.label_57.setGeometry(QtCore.QRect(130, 44, 31, 19))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.cmbArquetasAct = QtGui.QComboBox(self.groupBox_9)
        self.cmbArquetasAct.setGeometry(QtCore.QRect(40, 40, 81, 25))
        self.cmbArquetasAct.setObjectName(_fromUtf8("cmbArquetasAct"))
        self.cmbArquetasAct.addItem(_fromUtf8(""))
        self.cmbArquetasAct.addItem(_fromUtf8(""))
        self.cmbArquetasAct.addItem(_fromUtf8(""))
        self.cmbArquetasAct.addItem(_fromUtf8(""))
        self.cmbBajantesAct = QtGui.QComboBox(self.groupBox_9)
        self.cmbBajantesAct.setGeometry(QtCore.QRect(40, 119, 81, 25))
        self.cmbBajantesAct.setObjectName(_fromUtf8("cmbBajantesAct"))
        self.cmbBajantesAct.addItem(_fromUtf8(""))
        self.cmbBajantesAct.addItem(_fromUtf8(""))
        self.cmbBajantesAct.addItem(_fromUtf8(""))
        self.cmbBajantesAct.addItem(_fromUtf8(""))
        self.label_58 = QtGui.QLabel(self.groupBox_9)
        self.label_58.setGeometry(QtCore.QRect(130, 83, 31, 19))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.Estructuras = QtGui.QWidget()
        self.Estructuras.setObjectName(_fromUtf8("Estructuras"))
        self.groupBox_4 = QtGui.QGroupBox(self.Estructuras)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 821, 91))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(30, 36, 231, 19))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.cmbForjados = QtGui.QComboBox(self.groupBox_4)
        self.cmbForjados.setGeometry(QtCore.QRect(190, 36, 591, 25))
        self.cmbForjados.setObjectName(_fromUtf8("cmbForjados"))
        self.cmbForjados.addItem(_fromUtf8(""))
        self.cmbForjados.addItem(_fromUtf8(""))
        self.groupBox_10 = QtGui.QGroupBox(self.Estructuras)
        self.groupBox_10.setGeometry(QtCore.QRect(850, 20, 231, 91))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.label_2 = QtGui.QLabel(self.groupBox_10)
        self.label_2.setGeometry(QtCore.QRect(140, 40, 31, 19))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cmbForjadosAct = QtGui.QComboBox(self.groupBox_10)
        self.cmbForjadosAct.setGeometry(QtCore.QRect(50, 36, 81, 25))
        self.cmbForjadosAct.setObjectName(_fromUtf8("cmbForjadosAct"))
        self.cmbForjadosAct.addItem(_fromUtf8(""))
        self.cmbForjadosAct.addItem(_fromUtf8(""))
        self.cmbForjadosAct.addItem(_fromUtf8(""))
        self.cmbForjadosAct.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.Estructuras, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 20, 1111, 161))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_14.setGeometry(QtCore.QRect(20, 30, 841, 111))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.cmbGrietas = QtGui.QComboBox(self.groupBox_14)
        self.cmbGrietas.setGeometry(QtCore.QRect(260, 70, 561, 25))
        self.cmbGrietas.setObjectName(_fromUtf8("cmbGrietas"))
        self.cmbGrietas.addItem(_fromUtf8(""))
        self.cmbGrietas.addItem(_fromUtf8(""))
        self.cmbGrietas.addItem(_fromUtf8(""))
        self.label_18 = QtGui.QLabel(self.groupBox_14)
        self.label_18.setGeometry(QtCore.QRect(30, 72, 241, 19))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.cmbFisuras = QtGui.QComboBox(self.groupBox_14)
        self.cmbFisuras.setGeometry(QtCore.QRect(260, 30, 561, 25))
        self.cmbFisuras.setObjectName(_fromUtf8("cmbFisuras"))
        self.cmbFisuras.addItem(_fromUtf8(""))
        self.cmbFisuras.addItem(_fromUtf8(""))
        self.label_33 = QtGui.QLabel(self.groupBox_14)
        self.label_33.setGeometry(QtCore.QRect(30, 32, 231, 19))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.groupBox_15 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_15.setGeometry(QtCore.QRect(870, 30, 191, 111))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.label_4 = QtGui.QLabel(self.groupBox_15)
        self.label_4.setGeometry(QtCore.QRect(120, 74, 31, 19))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_15)
        self.label_3.setGeometry(QtCore.QRect(120, 34, 31, 19))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cmbGrietasAct = QtGui.QComboBox(self.groupBox_15)
        self.cmbGrietasAct.setGeometry(QtCore.QRect(30, 70, 81, 25))
        self.cmbGrietasAct.setObjectName(_fromUtf8("cmbGrietasAct"))
        self.cmbGrietasAct.addItem(_fromUtf8(""))
        self.cmbGrietasAct.addItem(_fromUtf8(""))
        self.cmbGrietasAct.addItem(_fromUtf8(""))
        self.cmbGrietasAct.addItem(_fromUtf8(""))
        self.cmbFisurasAct = QtGui.QComboBox(self.groupBox_15)
        self.cmbFisurasAct.setGeometry(QtCore.QRect(30, 30, 81, 25))
        self.cmbFisurasAct.setObjectName(_fromUtf8("cmbFisurasAct"))
        self.cmbFisurasAct.addItem(_fromUtf8(""))
        self.cmbFisurasAct.addItem(_fromUtf8(""))
        self.cmbFisurasAct.addItem(_fromUtf8(""))
        self.cmbFisurasAct.addItem(_fromUtf8(""))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_12.setGeometry(QtCore.QRect(20, 190, 1111, 251))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.groupBox_16 = QtGui.QGroupBox(self.groupBox_12)
        self.groupBox_16.setGeometry(QtCore.QRect(30, 30, 831, 201))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.cmbLadFisuras = QtGui.QComboBox(self.groupBox_16)
        self.cmbLadFisuras.setGeometry(QtCore.QRect(270, 30, 531, 25))
        self.cmbLadFisuras.setObjectName(_fromUtf8("cmbLadFisuras"))
        self.cmbLadFisuras.addItem(_fromUtf8(""))
        self.cmbLadFisuras.addItem(_fromUtf8(""))
        self.label_35 = QtGui.QLabel(self.groupBox_16)
        self.label_35.setGeometry(QtCore.QRect(20, 34, 231, 19))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.cmbLadGrietas = QtGui.QComboBox(self.groupBox_16)
        self.cmbLadGrietas.setGeometry(QtCore.QRect(270, 70, 531, 25))
        self.cmbLadGrietas.setObjectName(_fromUtf8("cmbLadGrietas"))
        self.cmbLadGrietas.addItem(_fromUtf8(""))
        self.cmbLadGrietas.addItem(_fromUtf8(""))
        self.cmbLadGrietas.addItem(_fromUtf8(""))
        self.cmbLadGrietas.addItem(_fromUtf8(""))
        self.cmbLadGrietas.addItem(_fromUtf8(""))
        self.cmbLadHumTecho = QtGui.QComboBox(self.groupBox_16)
        self.cmbLadHumTecho.setGeometry(QtCore.QRect(270, 150, 531, 25))
        self.cmbLadHumTecho.setObjectName(_fromUtf8("cmbLadHumTecho"))
        self.cmbLadHumTecho.addItem(_fromUtf8(""))
        self.cmbLadHumTecho.addItem(_fromUtf8(""))
        self.label_36 = QtGui.QLabel(self.groupBox_16)
        self.label_36.setGeometry(QtCore.QRect(20, 152, 261, 19))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.groupBox_16)
        self.label_37.setGeometry(QtCore.QRect(20, 112, 261, 19))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_34 = QtGui.QLabel(self.groupBox_16)
        self.label_34.setGeometry(QtCore.QRect(20, 73, 241, 19))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.cmbLadHumSuelo = QtGui.QComboBox(self.groupBox_16)
        self.cmbLadHumSuelo.setGeometry(QtCore.QRect(270, 110, 531, 25))
        self.cmbLadHumSuelo.setObjectName(_fromUtf8("cmbLadHumSuelo"))
        self.cmbLadHumSuelo.addItem(_fromUtf8(""))
        self.cmbLadHumSuelo.addItem(_fromUtf8(""))
        self.groupBox_17 = QtGui.QGroupBox(self.groupBox_12)
        self.groupBox_17.setGeometry(QtCore.QRect(870, 30, 191, 201))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.label_6 = QtGui.QLabel(self.groupBox_17)
        self.label_6.setGeometry(QtCore.QRect(120, 34, 31, 19))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cmbLadFisurasAct = QtGui.QComboBox(self.groupBox_17)
        self.cmbLadFisurasAct.setGeometry(QtCore.QRect(30, 30, 81, 25))
        self.cmbLadFisurasAct.setObjectName(_fromUtf8("cmbLadFisurasAct"))
        self.cmbLadFisurasAct.addItem(_fromUtf8(""))
        self.cmbLadFisurasAct.addItem(_fromUtf8(""))
        self.cmbLadFisurasAct.addItem(_fromUtf8(""))
        self.cmbLadFisurasAct.addItem(_fromUtf8(""))
        self.cmbLadHumTechoAct = QtGui.QComboBox(self.groupBox_17)
        self.cmbLadHumTechoAct.setGeometry(QtCore.QRect(30, 149, 81, 25))
        self.cmbLadHumTechoAct.setObjectName(_fromUtf8("cmbLadHumTechoAct"))
        self.cmbLadHumTechoAct.addItem(_fromUtf8(""))
        self.cmbLadHumTechoAct.addItem(_fromUtf8(""))
        self.cmbLadHumTechoAct.addItem(_fromUtf8(""))
        self.cmbLadHumTechoAct.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.groupBox_17)
        self.label_12.setGeometry(QtCore.QRect(120, 114, 31, 19))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_17)
        self.label_13.setGeometry(QtCore.QRect(120, 153, 31, 19))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.cmbLadHumSueloAct = QtGui.QComboBox(self.groupBox_17)
        self.cmbLadHumSueloAct.setGeometry(QtCore.QRect(30, 110, 81, 25))
        self.cmbLadHumSueloAct.setObjectName(_fromUtf8("cmbLadHumSueloAct"))
        self.cmbLadHumSueloAct.addItem(_fromUtf8(""))
        self.cmbLadHumSueloAct.addItem(_fromUtf8(""))
        self.cmbLadHumSueloAct.addItem(_fromUtf8(""))
        self.cmbLadHumSueloAct.addItem(_fromUtf8(""))
        self.cmbLadGrietasAct = QtGui.QComboBox(self.groupBox_17)
        self.cmbLadGrietasAct.setGeometry(QtCore.QRect(30, 70, 81, 25))
        self.cmbLadGrietasAct.setObjectName(_fromUtf8("cmbLadGrietasAct"))
        self.cmbLadGrietasAct.addItem(_fromUtf8(""))
        self.cmbLadGrietasAct.addItem(_fromUtf8(""))
        self.cmbLadGrietasAct.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.groupBox_17)
        self.label_10.setGeometry(QtCore.QRect(120, 74, 31, 19))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 40, 1111, 241))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.groupBox_18 = QtGui.QGroupBox(self.groupBox_13)
        self.groupBox_18.setGeometry(QtCore.QRect(30, 37, 841, 181))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.cmbIntFisuras = QtGui.QComboBox(self.groupBox_18)
        self.cmbIntFisuras.setGeometry(QtCore.QRect(230, 30, 561, 25))
        self.cmbIntFisuras.setObjectName(_fromUtf8("cmbIntFisuras"))
        self.cmbIntFisuras.addItem(_fromUtf8(""))
        self.cmbIntFisuras.addItem(_fromUtf8(""))
        self.label_38 = QtGui.QLabel(self.groupBox_18)
        self.label_38.setGeometry(QtCore.QRect(30, 80, 201, 19))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_41 = QtGui.QLabel(self.groupBox_18)
        self.label_41.setGeometry(QtCore.QRect(30, 129, 231, 19))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.cmbHumSuelo = QtGui.QComboBox(self.groupBox_18)
        self.cmbHumSuelo.setGeometry(QtCore.QRect(230, 125, 561, 25))
        self.cmbHumSuelo.setObjectName(_fromUtf8("cmbHumSuelo"))
        self.cmbHumSuelo.addItem(_fromUtf8(""))
        self.cmbHumSuelo.addItem(_fromUtf8(""))
        self.label_39 = QtGui.QLabel(self.groupBox_18)
        self.label_39.setGeometry(QtCore.QRect(30, 34, 231, 19))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.cmbIntGrietas = QtGui.QComboBox(self.groupBox_18)
        self.cmbIntGrietas.setGeometry(QtCore.QRect(230, 78, 561, 25))
        self.cmbIntGrietas.setObjectName(_fromUtf8("cmbIntGrietas"))
        self.cmbIntGrietas.addItem(_fromUtf8(""))
        self.cmbIntGrietas.addItem(_fromUtf8(""))
        self.cmbIntGrietas.addItem(_fromUtf8(""))
        self.groupBox_19 = QtGui.QGroupBox(self.groupBox_13)
        self.groupBox_19.setGeometry(QtCore.QRect(890, 37, 181, 181))
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.cmbIntGrietasAct = QtGui.QComboBox(self.groupBox_19)
        self.cmbIntGrietasAct.setGeometry(QtCore.QRect(30, 77, 81, 25))
        self.cmbIntGrietasAct.setObjectName(_fromUtf8("cmbIntGrietasAct"))
        self.cmbIntGrietasAct.addItem(_fromUtf8(""))
        self.cmbIntGrietasAct.addItem(_fromUtf8(""))
        self.cmbIntGrietasAct.addItem(_fromUtf8(""))
        self.label_15 = QtGui.QLabel(self.groupBox_19)
        self.label_15.setGeometry(QtCore.QRect(120, 81, 31, 19))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_19)
        self.label_16.setGeometry(QtCore.QRect(120, 129, 31, 19))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.cmbIntFisurasAct = QtGui.QComboBox(self.groupBox_19)
        self.cmbIntFisurasAct.setGeometry(QtCore.QRect(30, 30, 81, 25))
        self.cmbIntFisurasAct.setObjectName(_fromUtf8("cmbIntFisurasAct"))
        self.cmbIntFisurasAct.addItem(_fromUtf8(""))
        self.cmbIntFisurasAct.addItem(_fromUtf8(""))
        self.cmbIntFisurasAct.addItem(_fromUtf8(""))
        self.cmbIntFisurasAct.addItem(_fromUtf8(""))
        self.label_14 = QtGui.QLabel(self.groupBox_19)
        self.label_14.setGeometry(QtCore.QRect(120, 34, 31, 19))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.cmbHumSueloAct = QtGui.QComboBox(self.groupBox_19)
        self.cmbHumSueloAct.setGeometry(QtCore.QRect(30, 125, 81, 25))
        self.cmbHumSueloAct.setObjectName(_fromUtf8("cmbHumSueloAct"))
        self.cmbHumSueloAct.addItem(_fromUtf8(""))
        self.cmbHumSueloAct.addItem(_fromUtf8(""))
        self.cmbHumSueloAct.addItem(_fromUtf8(""))
        self.cmbHumSueloAct.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupCubInc = QtGui.QGroupBox(self.tab_4)
        self.groupCubInc.setGeometry(QtCore.QRect(20, 260, 1121, 231))
        self.groupCubInc.setObjectName(_fromUtf8("groupCubInc"))
        self.groupBox_22 = QtGui.QGroupBox(self.groupCubInc)
        self.groupBox_22.setGeometry(QtCore.QRect(20, 30, 881, 191))
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.cmbCubIncCompleta = QtGui.QComboBox(self.groupBox_22)
        self.cmbCubIncCompleta.setGeometry(QtCore.QRect(321, 30, 541, 25))
        self.cmbCubIncCompleta.setObjectName(_fromUtf8("cmbCubIncCompleta"))
        self.cmbCubIncCompleta.addItem(_fromUtf8(""))
        self.cmbCubIncCompleta.addItem(_fromUtf8(""))
        self.cmbCubIncCompleta.addItem(_fromUtf8(""))
        self.label_46 = QtGui.QLabel(self.groupBox_22)
        self.label_46.setGeometry(QtCore.QRect(20, 69, 201, 19))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.cmbCubIncRemates = QtGui.QComboBox(self.groupBox_22)
        self.cmbCubIncRemates.setGeometry(QtCore.QRect(321, 109, 541, 25))
        self.cmbCubIncRemates.setObjectName(_fromUtf8("cmbCubIncRemates"))
        self.cmbCubIncRemates.addItem(_fromUtf8(""))
        self.cmbCubIncRemates.addItem(_fromUtf8(""))
        self.cmbCubIncEncParamVer = QtGui.QComboBox(self.groupBox_22)
        self.cmbCubIncEncParamVer.setGeometry(QtCore.QRect(321, 146, 541, 25))
        self.cmbCubIncEncParamVer.setObjectName(_fromUtf8("cmbCubIncEncParamVer"))
        self.cmbCubIncEncParamVer.addItem(_fromUtf8(""))
        self.cmbCubIncEncParamVer.addItem(_fromUtf8(""))
        self.cmbCubIncFaldon = QtGui.QComboBox(self.groupBox_22)
        self.cmbCubIncFaldon.setGeometry(QtCore.QRect(321, 69, 541, 25))
        self.cmbCubIncFaldon.setObjectName(_fromUtf8("cmbCubIncFaldon"))
        self.cmbCubIncFaldon.addItem(_fromUtf8(""))
        self.cmbCubIncFaldon.addItem(_fromUtf8(""))
        self.label_49 = QtGui.QLabel(self.groupBox_22)
        self.label_49.setGeometry(QtCore.QRect(20, 146, 311, 19))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_48 = QtGui.QLabel(self.groupBox_22)
        self.label_48.setGeometry(QtCore.QRect(20, 109, 221, 19))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_47 = QtGui.QLabel(self.groupBox_22)
        self.label_47.setGeometry(QtCore.QRect(20, 30, 231, 19))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.groupBox_23 = QtGui.QGroupBox(self.groupCubInc)
        self.groupBox_23.setGeometry(QtCore.QRect(930, 29, 181, 191))
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.label_60 = QtGui.QLabel(self.groupBox_23)
        self.label_60.setGeometry(QtCore.QRect(110, 35, 31, 19))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.label_62 = QtGui.QLabel(self.groupBox_23)
        self.label_62.setGeometry(QtCore.QRect(110, 114, 31, 19))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.cmbCubIncFaldonAct = QtGui.QComboBox(self.groupBox_23)
        self.cmbCubIncFaldonAct.setGeometry(QtCore.QRect(20, 70, 81, 25))
        self.cmbCubIncFaldonAct.setObjectName(_fromUtf8("cmbCubIncFaldonAct"))
        self.cmbCubIncFaldonAct.addItem(_fromUtf8(""))
        self.cmbCubIncFaldonAct.addItem(_fromUtf8(""))
        self.label_61 = QtGui.QLabel(self.groupBox_23)
        self.label_61.setGeometry(QtCore.QRect(110, 74, 31, 19))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.cmbCubIncCompletaAct = QtGui.QComboBox(self.groupBox_23)
        self.cmbCubIncCompletaAct.setGeometry(QtCore.QRect(20, 31, 81, 25))
        self.cmbCubIncCompletaAct.setObjectName(_fromUtf8("cmbCubIncCompletaAct"))
        self.cmbCubIncCompletaAct.addItem(_fromUtf8(""))
        self.cmbCubIncCompletaAct.addItem(_fromUtf8(""))
        self.label_63 = QtGui.QLabel(self.groupBox_23)
        self.label_63.setGeometry(QtCore.QRect(110, 151, 31, 19))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.cmbCubIncEncParamVerAct = QtGui.QComboBox(self.groupBox_23)
        self.cmbCubIncEncParamVerAct.setGeometry(QtCore.QRect(20, 147, 81, 25))
        self.cmbCubIncEncParamVerAct.setObjectName(_fromUtf8("cmbCubIncEncParamVerAct"))
        self.cmbCubIncEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubIncEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubIncEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubIncEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubIncRematesAct = QtGui.QComboBox(self.groupBox_23)
        self.cmbCubIncRematesAct.setGeometry(QtCore.QRect(20, 110, 81, 25))
        self.cmbCubIncRematesAct.setObjectName(_fromUtf8("cmbCubIncRematesAct"))
        self.cmbCubIncRematesAct.addItem(_fromUtf8(""))
        self.cmbCubIncRematesAct.addItem(_fromUtf8(""))
        self.cmbCubIncRematesAct.addItem(_fromUtf8(""))
        self.cmbCubIncRematesAct.addItem(_fromUtf8(""))
        self.groupCubHor = QtGui.QGroupBox(self.tab_4)
        self.groupCubHor.setGeometry(QtCore.QRect(20, 30, 1121, 221))
        self.groupCubHor.setObjectName(_fromUtf8("groupCubHor"))
        self.groupBox_20 = QtGui.QGroupBox(self.groupCubHor)
        self.groupBox_20.setGeometry(QtCore.QRect(20, 29, 881, 181))
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.cmbCubHorEncCazoletas = QtGui.QComboBox(self.groupBox_20)
        self.cmbCubHorEncCazoletas.setGeometry(QtCore.QRect(320, 134, 541, 25))
        self.cmbCubHorEncCazoletas.setObjectName(_fromUtf8("cmbCubHorEncCazoletas"))
        self.cmbCubHorEncCazoletas.addItem(_fromUtf8(""))
        self.cmbCubHorEncCazoletas.addItem(_fromUtf8(""))
        self.cmbCubHorFaldon = QtGui.QComboBox(self.groupBox_20)
        self.cmbCubHorFaldon.setGeometry(QtCore.QRect(320, 63, 541, 25))
        self.cmbCubHorFaldon.setObjectName(_fromUtf8("cmbCubHorFaldon"))
        self.cmbCubHorFaldon.addItem(_fromUtf8(""))
        self.cmbCubHorFaldon.addItem(_fromUtf8(""))
        self.label_53 = QtGui.QLabel(self.groupBox_20)
        self.label_53.setGeometry(QtCore.QRect(20, 29, 231, 19))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_55 = QtGui.QLabel(self.groupBox_20)
        self.label_55.setGeometry(QtCore.QRect(20, 102, 331, 19))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.cmbCubHorEncParamVer = QtGui.QComboBox(self.groupBox_20)
        self.cmbCubHorEncParamVer.setGeometry(QtCore.QRect(320, 100, 541, 25))
        self.cmbCubHorEncParamVer.setObjectName(_fromUtf8("cmbCubHorEncParamVer"))
        self.cmbCubHorEncParamVer.addItem(_fromUtf8(""))
        self.cmbCubHorEncParamVer.addItem(_fromUtf8(""))
        self.label_54 = QtGui.QLabel(self.groupBox_20)
        self.label_54.setGeometry(QtCore.QRect(20, 138, 221, 19))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.cmbCubHorCom = QtGui.QComboBox(self.groupBox_20)
        self.cmbCubHorCom.setGeometry(QtCore.QRect(320, 26, 541, 25))
        self.cmbCubHorCom.setObjectName(_fromUtf8("cmbCubHorCom"))
        self.cmbCubHorCom.addItem(_fromUtf8(""))
        self.cmbCubHorCom.addItem(_fromUtf8(""))
        self.cmbCubHorCom.addItem(_fromUtf8(""))
        self.label_52 = QtGui.QLabel(self.groupBox_20)
        self.label_52.setGeometry(QtCore.QRect(20, 65, 201, 19))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.groupBox_21 = QtGui.QGroupBox(self.groupCubHor)
        self.groupBox_21.setGeometry(QtCore.QRect(930, 29, 181, 181))
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.label_42 = QtGui.QLabel(self.groupBox_21)
        self.label_42.setGeometry(QtCore.QRect(110, 30, 31, 19))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.cmbCubHorComAct = QtGui.QComboBox(self.groupBox_21)
        self.cmbCubHorComAct.setGeometry(QtCore.QRect(20, 26, 81, 25))
        self.cmbCubHorComAct.setObjectName(_fromUtf8("cmbCubHorComAct"))
        self.cmbCubHorComAct.addItem(_fromUtf8(""))
        self.cmbCubHorComAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncParamVerAct = QtGui.QComboBox(self.groupBox_21)
        self.cmbCubHorEncParamVerAct.setGeometry(QtCore.QRect(20, 100, 81, 25))
        self.cmbCubHorEncParamVerAct.setObjectName(_fromUtf8("cmbCubHorEncParamVerAct"))
        self.cmbCubHorEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncParamVerAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncParamVerAct.addItem(_fromUtf8(""))
        self.label_45 = QtGui.QLabel(self.groupBox_21)
        self.label_45.setGeometry(QtCore.QRect(110, 138, 31, 19))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_43 = QtGui.QLabel(self.groupBox_21)
        self.label_43.setGeometry(QtCore.QRect(110, 67, 31, 19))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.cmbCubHorEncCazoletasAct = QtGui.QComboBox(self.groupBox_21)
        self.cmbCubHorEncCazoletasAct.setGeometry(QtCore.QRect(20, 134, 81, 25))
        self.cmbCubHorEncCazoletasAct.setObjectName(_fromUtf8("cmbCubHorEncCazoletasAct"))
        self.cmbCubHorEncCazoletasAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncCazoletasAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncCazoletasAct.addItem(_fromUtf8(""))
        self.cmbCubHorEncCazoletasAct.addItem(_fromUtf8(""))
        self.label_44 = QtGui.QLabel(self.groupBox_21)
        self.label_44.setGeometry(QtCore.QRect(110, 104, 31, 19))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.cmbCubHorFaldonAct = QtGui.QComboBox(self.groupBox_21)
        self.cmbCubHorFaldonAct.setGeometry(QtCore.QRect(20, 63, 81, 25))
        self.cmbCubHorFaldonAct.setObjectName(_fromUtf8("cmbCubHorFaldonAct"))
        self.cmbCubHorFaldonAct.addItem(_fromUtf8(""))
        self.cmbCubHorFaldonAct.addItem(_fromUtf8(""))
        self.cmbCubHorFaldonAct.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.Instalaciones = QtGui.QWidget()
        self.Instalaciones.setObjectName(_fromUtf8("Instalaciones"))
        self.groupBox = QtGui.QGroupBox(self.Instalaciones)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 1131, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_24 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_24.setGeometry(QtCore.QRect(19, 30, 861, 111))
        self.groupBox_24.setObjectName(_fromUtf8("groupBox_24"))
        self.cmbRadiadores = QtGui.QComboBox(self.groupBox_24)
        self.cmbRadiadores.setGeometry(QtCore.QRect(270, 70, 561, 25))
        self.cmbRadiadores.setObjectName(_fromUtf8("cmbRadiadores"))
        self.cmbRadiadores.addItem(_fromUtf8(""))
        self.cmbRadiadores.addItem(_fromUtf8(""))
        self.label_119 = QtGui.QLabel(self.groupBox_24)
        self.label_119.setGeometry(QtCore.QRect(20, 70, 171, 19))
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.cmbClimatizacion = QtGui.QComboBox(self.groupBox_24)
        self.cmbClimatizacion.setGeometry(QtCore.QRect(270, 30, 561, 25))
        self.cmbClimatizacion.setObjectName(_fromUtf8("cmbClimatizacion"))
        self.cmbClimatizacion.addItem(_fromUtf8(""))
        self.cmbClimatizacion.addItem(_fromUtf8(""))
        self.label_116 = QtGui.QLabel(self.groupBox_24)
        self.label_116.setGeometry(QtCore.QRect(20, 30, 321, 19))
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.groupBox_25 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_25.setGeometry(QtCore.QRect(899, 30, 181, 111))
        self.groupBox_25.setObjectName(_fromUtf8("groupBox_25"))
        self.label_122 = QtGui.QLabel(self.groupBox_25)
        self.label_122.setGeometry(QtCore.QRect(110, 74, 31, 19))
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.cmbClimatizacionAct = QtGui.QComboBox(self.groupBox_25)
        self.cmbClimatizacionAct.setGeometry(QtCore.QRect(20, 30, 81, 25))
        self.cmbClimatizacionAct.setObjectName(_fromUtf8("cmbClimatizacionAct"))
        self.cmbClimatizacionAct.addItem(_fromUtf8(""))
        self.cmbClimatizacionAct.addItem(_fromUtf8(""))
        self.label_115 = QtGui.QLabel(self.groupBox_25)
        self.label_115.setGeometry(QtCore.QRect(110, 34, 31, 19))
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.cmbRadiadoresAct = QtGui.QComboBox(self.groupBox_25)
        self.cmbRadiadoresAct.setGeometry(QtCore.QRect(20, 70, 81, 25))
        self.cmbRadiadoresAct.setObjectName(_fromUtf8("cmbRadiadoresAct"))
        self.cmbRadiadoresAct.addItem(_fromUtf8(""))
        self.cmbRadiadoresAct.addItem(_fromUtf8(""))
        self.groupBox_5 = QtGui.QGroupBox(self.Instalaciones)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 180, 1131, 271))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.groupBox_26 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_26.setGeometry(QtCore.QRect(19, 29, 861, 231))
        self.groupBox_26.setObjectName(_fromUtf8("groupBox_26"))
        self.label_20 = QtGui.QLabel(self.groupBox_26)
        self.label_20.setGeometry(QtCore.QRect(20, 30, 211, 19))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.cmbTomaCorriente = QtGui.QComboBox(self.groupBox_26)
        self.cmbTomaCorriente.setGeometry(QtCore.QRect(270, 151, 561, 25))
        self.cmbTomaCorriente.setObjectName(_fromUtf8("cmbTomaCorriente"))
        self.cmbTomaCorriente.addItem(_fromUtf8(""))
        self.cmbTomaCorriente.addItem(_fromUtf8(""))
        self.cmbCircuitos = QtGui.QComboBox(self.groupBox_26)
        self.cmbCircuitos.setGeometry(QtCore.QRect(270, 30, 561, 25))
        self.cmbCircuitos.setObjectName(_fromUtf8("cmbCircuitos"))
        self.cmbCircuitos.addItem(_fromUtf8(""))
        self.cmbCircuitos.addItem(_fromUtf8(""))
        self.label_26 = QtGui.QLabel(self.groupBox_26)
        self.label_26.setGeometry(QtCore.QRect(20, 151, 221, 19))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.cmbPuntosLuz = QtGui.QComboBox(self.groupBox_26)
        self.cmbPuntosLuz.setGeometry(QtCore.QRect(270, 110, 561, 25))
        self.cmbPuntosLuz.setObjectName(_fromUtf8("cmbPuntosLuz"))
        self.cmbPuntosLuz.addItem(_fromUtf8(""))
        self.cmbPuntosLuz.addItem(_fromUtf8(""))
        self.cmbConductorPuestaTierra = QtGui.QComboBox(self.groupBox_26)
        self.cmbConductorPuestaTierra.setGeometry(QtCore.QRect(270, 192, 561, 25))
        self.cmbConductorPuestaTierra.setObjectName(_fromUtf8("cmbConductorPuestaTierra"))
        self.cmbConductorPuestaTierra.addItem(_fromUtf8(""))
        self.cmbConductorPuestaTierra.addItem(_fromUtf8(""))
        self.label_21 = QtGui.QLabel(self.groupBox_26)
        self.label_21.setGeometry(QtCore.QRect(20, 70, 211, 19))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.cmbLineasYDerivaciones = QtGui.QComboBox(self.groupBox_26)
        self.cmbLineasYDerivaciones.setGeometry(QtCore.QRect(270, 70, 561, 25))
        self.cmbLineasYDerivaciones.setObjectName(_fromUtf8("cmbLineasYDerivaciones"))
        self.cmbLineasYDerivaciones.addItem(_fromUtf8(""))
        self.cmbLineasYDerivaciones.addItem(_fromUtf8(""))
        self.label_27 = QtGui.QLabel(self.groupBox_26)
        self.label_27.setGeometry(QtCore.QRect(20, 192, 271, 19))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_22 = QtGui.QLabel(self.groupBox_26)
        self.label_22.setGeometry(QtCore.QRect(20, 110, 231, 19))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.groupBox_27 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_27.setGeometry(QtCore.QRect(899, 29, 181, 231))
        self.groupBox_27.setObjectName(_fromUtf8("groupBox_27"))
        self.label_64 = QtGui.QLabel(self.groupBox_27)
        self.label_64.setGeometry(QtCore.QRect(110, 35, 31, 19))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_65 = QtGui.QLabel(self.groupBox_27)
        self.label_65.setGeometry(QtCore.QRect(110, 75, 31, 19))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.label_68 = QtGui.QLabel(self.groupBox_27)
        self.label_68.setGeometry(QtCore.QRect(110, 195, 31, 19))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.cmbConductorPuestaTierraAct = QtGui.QComboBox(self.groupBox_27)
        self.cmbConductorPuestaTierraAct.setGeometry(QtCore.QRect(20, 191, 81, 25))
        self.cmbConductorPuestaTierraAct.setObjectName(_fromUtf8("cmbConductorPuestaTierraAct"))
        self.cmbConductorPuestaTierraAct.addItem(_fromUtf8(""))
        self.cmbConductorPuestaTierraAct.addItem(_fromUtf8(""))
        self.cmbConductorPuestaTierraAct.addItem(_fromUtf8(""))
        self.cmbConductorPuestaTierraAct.addItem(_fromUtf8(""))
        self.cmbTomaCorrienteAct = QtGui.QComboBox(self.groupBox_27)
        self.cmbTomaCorrienteAct.setGeometry(QtCore.QRect(20, 151, 81, 25))
        self.cmbTomaCorrienteAct.setObjectName(_fromUtf8("cmbTomaCorrienteAct"))
        self.cmbTomaCorrienteAct.addItem(_fromUtf8(""))
        self.cmbTomaCorrienteAct.addItem(_fromUtf8(""))
        self.cmbTomaCorrienteAct.addItem(_fromUtf8(""))
        self.cmbTomaCorrienteAct.addItem(_fromUtf8(""))
        self.cmbCircuitosAct = QtGui.QComboBox(self.groupBox_27)
        self.cmbCircuitosAct.setGeometry(QtCore.QRect(20, 31, 81, 25))
        self.cmbCircuitosAct.setObjectName(_fromUtf8("cmbCircuitosAct"))
        self.cmbCircuitosAct.addItem(_fromUtf8(""))
        self.cmbCircuitosAct.addItem(_fromUtf8(""))
        self.cmbCircuitosAct.addItem(_fromUtf8(""))
        self.cmbCircuitosAct.addItem(_fromUtf8(""))
        self.label_67 = QtGui.QLabel(self.groupBox_27)
        self.label_67.setGeometry(QtCore.QRect(110, 155, 31, 19))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_66 = QtGui.QLabel(self.groupBox_27)
        self.label_66.setGeometry(QtCore.QRect(110, 115, 31, 19))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.cmbPuntosLuzAct = QtGui.QComboBox(self.groupBox_27)
        self.cmbPuntosLuzAct.setGeometry(QtCore.QRect(20, 111, 81, 25))
        self.cmbPuntosLuzAct.setObjectName(_fromUtf8("cmbPuntosLuzAct"))
        self.cmbPuntosLuzAct.addItem(_fromUtf8(""))
        self.cmbPuntosLuzAct.addItem(_fromUtf8(""))
        self.cmbPuntosLuzAct.addItem(_fromUtf8(""))
        self.cmbPuntosLuzAct.addItem(_fromUtf8(""))
        self.cmbLineasYDerivacionesAct = QtGui.QComboBox(self.groupBox_27)
        self.cmbLineasYDerivacionesAct.setGeometry(QtCore.QRect(20, 71, 81, 25))
        self.cmbLineasYDerivacionesAct.setObjectName(_fromUtf8("cmbLineasYDerivacionesAct"))
        self.cmbLineasYDerivacionesAct.addItem(_fromUtf8(""))
        self.cmbLineasYDerivacionesAct.addItem(_fromUtf8(""))
        self.cmbLineasYDerivacionesAct.addItem(_fromUtf8(""))
        self.cmbLineasYDerivacionesAct.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.Instalaciones, _fromUtf8(""))
        self.InstalacionesII = QtGui.QWidget()
        self.InstalacionesII.setObjectName(_fromUtf8("InstalacionesII"))
        self.groupBox_2 = QtGui.QGroupBox(self.InstalacionesII)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 1111, 301))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.groupBox_28 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_28.setGeometry(QtCore.QRect(19, 30, 841, 251))
        self.groupBox_28.setObjectName(_fromUtf8("groupBox_28"))
        self.cmbCanalizacionesCal = QtGui.QComboBox(self.groupBox_28)
        self.cmbCanalizacionesCal.setGeometry(QtCore.QRect(280, 40, 541, 25))
        self.cmbCanalizacionesCal.setObjectName(_fromUtf8("cmbCanalizacionesCal"))
        self.cmbCanalizacionesCal.addItem(_fromUtf8(""))
        self.cmbCanalizacionesCal.addItem(_fromUtf8(""))
        self.cmbCanalizacionesCal.addItem(_fromUtf8(""))
        self.label_30 = QtGui.QLabel(self.groupBox_28)
        self.label_30.setGeometry(QtCore.QRect(20, 207, 191, 19))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_25 = QtGui.QLabel(self.groupBox_28)
        self.label_25.setGeometry(QtCore.QRect(20, 165, 191, 19))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_23 = QtGui.QLabel(self.groupBox_28)
        self.label_23.setGeometry(QtCore.QRect(20, 83, 191, 19))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.cmbSanitarios = QtGui.QComboBox(self.groupBox_28)
        self.cmbSanitarios.setGeometry(QtCore.QRect(280, 165, 541, 25))
        self.cmbSanitarios.setObjectName(_fromUtf8("cmbSanitarios"))
        self.cmbSanitarios.addItem(_fromUtf8(""))
        self.cmbSanitarios.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFria = QtGui.QComboBox(self.groupBox_28)
        self.cmbCanalizacionesAguaFria.setGeometry(QtCore.QRect(280, 123, 541, 25))
        self.cmbCanalizacionesAguaFria.setObjectName(_fromUtf8("cmbCanalizacionesAguaFria"))
        self.cmbCanalizacionesAguaFria.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFria.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFria.addItem(_fromUtf8(""))
        self.label_28 = QtGui.QLabel(self.groupBox_28)
        self.label_28.setGeometry(QtCore.QRect(20, 40, 261, 19))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.groupBox_28)
        self.label_29.setGeometry(QtCore.QRect(20, 123, 211, 19))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.cmbTermos = QtGui.QComboBox(self.groupBox_28)
        self.cmbTermos.setGeometry(QtCore.QRect(280, 207, 541, 25))
        self.cmbTermos.setObjectName(_fromUtf8("cmbTermos"))
        self.cmbTermos.addItem(_fromUtf8(""))
        self.cmbTermos.addItem(_fromUtf8(""))
        self.cmbTermos.addItem(_fromUtf8(""))
        self.cmbDesagues = QtGui.QComboBox(self.groupBox_28)
        self.cmbDesagues.setGeometry(QtCore.QRect(280, 83, 541, 25))
        self.cmbDesagues.setObjectName(_fromUtf8("cmbDesagues"))
        self.cmbDesagues.addItem(_fromUtf8(""))
        self.cmbDesagues.addItem(_fromUtf8(""))
        self.groupBox_29 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_29.setGeometry(QtCore.QRect(880, 29, 191, 251))
        self.groupBox_29.setObjectName(_fromUtf8("groupBox_29"))
        self.label_74 = QtGui.QLabel(self.groupBox_29)
        self.label_74.setGeometry(QtCore.QRect(110, 213, 31, 19))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.label_70 = QtGui.QLabel(self.groupBox_29)
        self.label_70.setGeometry(QtCore.QRect(110, 89, 31, 19))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.label_69 = QtGui.QLabel(self.groupBox_29)
        self.label_69.setGeometry(QtCore.QRect(110, 45, 31, 19))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.label_73 = QtGui.QLabel(self.groupBox_29)
        self.label_73.setGeometry(QtCore.QRect(110, 170, 31, 19))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.cmbCanalizacionesAguaFriaAct = QtGui.QComboBox(self.groupBox_29)
        self.cmbCanalizacionesAguaFriaAct.setGeometry(QtCore.QRect(20, 125, 81, 25))
        self.cmbCanalizacionesAguaFriaAct.setObjectName(_fromUtf8("cmbCanalizacionesAguaFriaAct"))
        self.cmbCanalizacionesAguaFriaAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFriaAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFriaAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesAguaFriaAct.addItem(_fromUtf8(""))
        self.cmbSanitariosAct = QtGui.QComboBox(self.groupBox_29)
        self.cmbSanitariosAct.setGeometry(QtCore.QRect(20, 166, 81, 25))
        self.cmbSanitariosAct.setObjectName(_fromUtf8("cmbSanitariosAct"))
        self.cmbSanitariosAct.addItem(_fromUtf8(""))
        self.cmbSanitariosAct.addItem(_fromUtf8(""))
        self.cmbSanitariosAct.addItem(_fromUtf8(""))
        self.cmbSanitariosAct.addItem(_fromUtf8(""))
        self.label_71 = QtGui.QLabel(self.groupBox_29)
        self.label_71.setGeometry(QtCore.QRect(110, 129, 31, 19))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.cmbTermosAct = QtGui.QComboBox(self.groupBox_29)
        self.cmbTermosAct.setGeometry(QtCore.QRect(20, 209, 81, 25))
        self.cmbTermosAct.setObjectName(_fromUtf8("cmbTermosAct"))
        self.cmbTermosAct.addItem(_fromUtf8(""))
        self.cmbTermosAct.addItem(_fromUtf8(""))
        self.cmbTermosAct.addItem(_fromUtf8(""))
        self.cmbTermosAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesCalAct = QtGui.QComboBox(self.groupBox_29)
        self.cmbCanalizacionesCalAct.setGeometry(QtCore.QRect(20, 41, 81, 25))
        self.cmbCanalizacionesCalAct.setObjectName(_fromUtf8("cmbCanalizacionesCalAct"))
        self.cmbCanalizacionesCalAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesCalAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesCalAct.addItem(_fromUtf8(""))
        self.cmbCanalizacionesCalAct.addItem(_fromUtf8(""))
        self.cmbDesaguesAct = QtGui.QComboBox(self.groupBox_29)
        self.cmbDesaguesAct.setGeometry(QtCore.QRect(20, 85, 81, 25))
        self.cmbDesaguesAct.setObjectName(_fromUtf8("cmbDesaguesAct"))
        self.cmbDesaguesAct.addItem(_fromUtf8(""))
        self.cmbDesaguesAct.addItem(_fromUtf8(""))
        self.cmbDesaguesAct.addItem(_fromUtf8(""))
        self.cmbDesaguesAct.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.InstalacionesII, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_30 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_30.setGeometry(QtCore.QRect(30, 30, 861, 151))
        self.groupBox_30.setObjectName(_fromUtf8("groupBox_30"))
        self.label_19 = QtGui.QLabel(self.groupBox_30)
        self.label_19.setGeometry(QtCore.QRect(30, 43, 231, 19))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.cmbCarpLigera = QtGui.QComboBox(self.groupBox_30)
        self.cmbCarpLigera.setGeometry(QtCore.QRect(200, 43, 631, 25))
        self.cmbCarpLigera.setObjectName(_fromUtf8("cmbCarpLigera"))
        self.cmbCarpLigera.addItem(_fromUtf8(""))
        self.cmbCarpLigera.addItem(_fromUtf8(""))
        self.cmbCarpLigera.addItem(_fromUtf8(""))
        self.cmbCarpLigera.addItem(_fromUtf8(""))
        self.label_40 = QtGui.QLabel(self.groupBox_30)
        self.label_40.setGeometry(QtCore.QRect(30, 90, 231, 19))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.cmbCarpMadera = QtGui.QComboBox(self.groupBox_30)
        self.cmbCarpMadera.setGeometry(QtCore.QRect(200, 90, 631, 25))
        self.cmbCarpMadera.setObjectName(_fromUtf8("cmbCarpMadera"))
        self.cmbCarpMadera.addItem(_fromUtf8(""))
        self.cmbCarpMadera.addItem(_fromUtf8(""))
        self.cmbCarpMadera.addItem(_fromUtf8(""))
        self.cmbCarpMadera.addItem(_fromUtf8(""))
        self.groupBox_31 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_31.setGeometry(QtCore.QRect(910, 30, 191, 151))
        self.groupBox_31.setObjectName(_fromUtf8("groupBox_31"))
        self.label_75 = QtGui.QLabel(self.groupBox_31)
        self.label_75.setGeometry(QtCore.QRect(120, 48, 31, 19))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.cmbCarpLigeraAct = QtGui.QComboBox(self.groupBox_31)
        self.cmbCarpLigeraAct.setGeometry(QtCore.QRect(30, 44, 81, 25))
        self.cmbCarpLigeraAct.setObjectName(_fromUtf8("cmbCarpLigeraAct"))
        self.cmbCarpLigeraAct.addItem(_fromUtf8(""))
        self.cmbCarpLigeraAct.addItem(_fromUtf8(""))
        self.cmbCarpLigeraAct.addItem(_fromUtf8(""))
        self.cmbCarpLigeraAct.addItem(_fromUtf8(""))
        self.label_78 = QtGui.QLabel(self.groupBox_31)
        self.label_78.setGeometry(QtCore.QRect(120, 94, 31, 19))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.cmbCarpMaderaAct = QtGui.QComboBox(self.groupBox_31)
        self.cmbCarpMaderaAct.setGeometry(QtCore.QRect(30, 90, 81, 25))
        self.cmbCarpMaderaAct.setObjectName(_fromUtf8("cmbCarpMaderaAct"))
        self.cmbCarpMaderaAct.addItem(_fromUtf8(""))
        self.cmbCarpMaderaAct.addItem(_fromUtf8(""))
        self.cmbCarpMaderaAct.addItem(_fromUtf8(""))
        self.cmbCarpMaderaAct.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.groupBox_32 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_32.setGeometry(QtCore.QRect(50, 30, 761, 221))
        self.groupBox_32.setObjectName(_fromUtf8("groupBox_32"))
        self.cmbAscensores = QtGui.QComboBox(self.groupBox_32)
        self.cmbAscensores.setGeometry(QtCore.QRect(260, 177, 471, 25))
        self.cmbAscensores.setObjectName(_fromUtf8("cmbAscensores"))
        self.cmbAscensores.addItem(_fromUtf8(""))
        self.cmbAscensores.addItem(_fromUtf8(""))
        self.cmbRampa = QtGui.QComboBox(self.groupBox_32)
        self.cmbRampa.setGeometry(QtCore.QRect(260, 83, 471, 25))
        self.cmbRampa.setObjectName(_fromUtf8("cmbRampa"))
        self.cmbRampa.addItem(_fromUtf8(""))
        self.cmbRampa.addItem(_fromUtf8(""))
        self.cmbEscalera = QtGui.QComboBox(self.groupBox_32)
        self.cmbEscalera.setGeometry(QtCore.QRect(260, 38, 471, 25))
        self.cmbEscalera.setObjectName(_fromUtf8("cmbEscalera"))
        self.cmbEscalera.addItem(_fromUtf8(""))
        self.cmbEscalera.addItem(_fromUtf8(""))
        self.cmbEscalera.addItem(_fromUtf8(""))
        self.label_24 = QtGui.QLabel(self.groupBox_32)
        self.label_24.setGeometry(QtCore.QRect(30, 42, 181, 19))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.cmbPortero = QtGui.QComboBox(self.groupBox_32)
        self.cmbPortero.setGeometry(QtCore.QRect(260, 130, 471, 25))
        self.cmbPortero.setObjectName(_fromUtf8("cmbPortero"))
        self.cmbPortero.addItem(_fromUtf8(""))
        self.cmbPortero.addItem(_fromUtf8(""))
        self.label_72 = QtGui.QLabel(self.groupBox_32)
        self.label_72.setGeometry(QtCore.QRect(30, 134, 331, 19))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.label = QtGui.QLabel(self.groupBox_32)
        self.label.setGeometry(QtCore.QRect(30, 179, 181, 19))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_50 = QtGui.QLabel(self.groupBox_32)
        self.label_50.setGeometry(QtCore.QRect(30, 87, 341, 19))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.groupBox_33 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_33.setGeometry(QtCore.QRect(830, 30, 211, 221))
        self.groupBox_33.setObjectName(_fromUtf8("groupBox_33"))
        self.cmbAscensoresAct = QtGui.QComboBox(self.groupBox_33)
        self.cmbAscensoresAct.setGeometry(QtCore.QRect(30, 177, 121, 25))
        self.cmbAscensoresAct.setObjectName(_fromUtf8("cmbAscensoresAct"))
        self.cmbAscensoresAct.addItem(_fromUtf8(""))
        self.cmbAscensoresAct.addItem(_fromUtf8(""))
        self.cmbEscaleraAct = QtGui.QComboBox(self.groupBox_33)
        self.cmbEscaleraAct.setGeometry(QtCore.QRect(30, 39, 121, 25))
        self.cmbEscaleraAct.setObjectName(_fromUtf8("cmbEscaleraAct"))
        self.cmbEscaleraAct.addItem(_fromUtf8(""))
        self.cmbEscaleraAct.addItem(_fromUtf8(""))
        self.cmbRampaAct = QtGui.QComboBox(self.groupBox_33)
        self.cmbRampaAct.setGeometry(QtCore.QRect(30, 84, 121, 25))
        self.cmbRampaAct.setObjectName(_fromUtf8("cmbRampaAct"))
        self.cmbRampaAct.addItem(_fromUtf8(""))
        self.cmbRampaAct.addItem(_fromUtf8(""))
        self.cmbPorteroAct = QtGui.QComboBox(self.groupBox_33)
        self.cmbPorteroAct.setGeometry(QtCore.QRect(30, 130, 121, 25))
        self.cmbPorteroAct.setObjectName(_fromUtf8("cmbPorteroAct"))
        self.cmbPorteroAct.addItem(_fromUtf8(""))
        self.cmbPorteroAct.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.horizontalLayoutWidget = QtGui.QWidget(ActuacionForm)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(860, 660, 331, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.btnAccept = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnAccept.setDefault(True)
        self.btnAccept.setObjectName(_fromUtf8("btnAccept"))
        self.horizontalLayout.addWidget(self.btnAccept)

        self.retranslateUi(ActuacionForm)
        self.tabWidget.setCurrentIndex(9)
        QtCore.QMetaObject.connectSlotsByName(ActuacionForm)

    def retranslateUi(self, ActuacionForm):
        ActuacionForm.setWindowTitle(_translate("ActuacionForm", "Herevea", None))
        self.label_31.setText(_translate("ActuacionForm", "Direccion", None))
        self.label_32.setText(_translate("ActuacionForm", "Ref. Catastral", None))
        self.groupBox_6.setTitle(_translate("ActuacionForm", "Intervenciones de rehabilitación", None))
        self.groupBox_3.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.cmbPilotes.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbPilotes.setItemText(1, _translate("ActuacionForm", "Recalce de zapata mediante micropilotes", None))
        self.label_5.setText(_translate("ActuacionForm", "Reparación con micropilotes", None))
        self.groupBox_7.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_56.setText(_translate("ActuacionForm", "%", None))
        self.cmbPilotesAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbPilotesAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbPilotesAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbPilotesAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ActuacionForm", "Cimentaciones", None))
        self.groupBox_8.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.cmbBajantes.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbBajantes.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición en polipropileno", None))
        self.cmbBajantes.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición en fibrocemento NT", None))
        self.cmbArquetas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbArquetas.setItemText(1, _translate("ActuacionForm", "Reparación de impermeabilización", None))
        self.cmbArquetas.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.cmbArquetas.setItemText(3, _translate("ActuacionForm", "Arqueta nueva (% de incremento en inst. existente)", None))
        self.label_9.setText(_translate("ActuacionForm", "Bajantes", None))
        self.label_8.setText(_translate("ActuacionForm", "Colectores", None))
        self.label_7.setText(_translate("ActuacionForm", "Arquetas", None))
        self.cmbColectores.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbColectores.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición en polietileno", None))
        self.cmbColectores.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición en hormigón", None))
        self.cmbColectores.setItemText(3, _translate("ActuacionForm", "Sustitución y reposición en fibrocemento NT", None))
        self.groupBox_9.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_59.setText(_translate("ActuacionForm", "%", None))
        self.cmbColectoresAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbColectoresAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbColectoresAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbColectoresAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_57.setText(_translate("ActuacionForm", "%", None))
        self.cmbArquetasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbArquetasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbArquetasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbArquetasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbBajantesAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbBajantesAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbBajantesAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbBajantesAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_58.setText(_translate("ActuacionForm", "%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ActuacionForm", "Saneamiento", None))
        self.groupBox_4.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.label_11.setText(_translate("ActuacionForm", "Forjados", None))
        self.cmbForjados.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbForjados.setItemText(1, _translate("ActuacionForm", "Reparación capa compresión", None))
        self.groupBox_10.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_2.setText(_translate("ActuacionForm", "%", None))
        self.cmbForjadosAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbForjadosAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbForjadosAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbForjadosAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Estructuras), _translate("ActuacionForm", "Estructuras", None))
        self.groupBox_11.setTitle(_translate("ActuacionForm", "Distr. Tabiquería (Particiones)", None))
        self.groupBox_14.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.cmbGrietas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbGrietas.setItemText(1, _translate("ActuacionForm", "Reparación grietas en superficie ≤60%", None))
        self.cmbGrietas.setItemText(2, _translate("ActuacionForm", "Reparación grietas en superficie >60% (sustitución y reposición)", None))
        self.label_18.setText(_translate("ActuacionForm", "Grietas", None))
        self.cmbFisuras.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbFisuras.setItemText(1, _translate("ActuacionForm", "Reparación de fisuras", None))
        self.label_33.setText(_translate("ActuacionForm", "Fisuras", None))
        self.groupBox_15.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_4.setText(_translate("ActuacionForm", "%", None))
        self.label_3.setText(_translate("ActuacionForm", "%", None))
        self.cmbGrietasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbGrietasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbGrietasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbGrietasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbFisurasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbFisurasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbFisurasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbFisurasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.groupBox_12.setTitle(_translate("ActuacionForm", "Cerramientos de Ladrillo", None))
        self.groupBox_16.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.cmbLadFisuras.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbLadFisuras.setItemText(1, _translate("ActuacionForm", "Reparación de fisuras", None))
        self.label_35.setText(_translate("ActuacionForm", "Fisuras", None))
        self.cmbLadGrietas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbLadGrietas.setItemText(1, _translate("ActuacionForm", "Reparación grietas en superficie ≤60%", None))
        self.cmbLadGrietas.setItemText(2, _translate("ActuacionForm", "Reparación grietas (>60% superf. fach.). Rehab.energ. ext. Fach. Revest. continuo, aisl. EPS", None))
        self.cmbLadGrietas.setItemText(3, _translate("ActuacionForm", "Reparación grietas (>60% superf. fach.). Rehab.energ. ext. Fach. Ventilada, aisl. EPS", None))
        self.cmbLadGrietas.setItemText(4, _translate("ActuacionForm", "Reparación grietas (>60% superf. fach.). Rehab.energ. ext. Fach. Ventilada, aisl. lana oveja", None))
        self.cmbLadHumTecho.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbLadHumTecho.setItemText(1, _translate("ActuacionForm", "Reparación humedades filtraciones encuentro de forjado con cerramiento", None))
        self.label_36.setText(_translate("ActuacionForm", "Humedades en techo", None))
        self.label_37.setText(_translate("ActuacionForm", "Humedades en suelo", None))
        self.label_34.setText(_translate("ActuacionForm", "Grietas", None))
        self.cmbLadHumSuelo.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbLadHumSuelo.setItemText(1, _translate("ActuacionForm", "Reparación humedades capilaridad", None))
        self.groupBox_17.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_6.setText(_translate("ActuacionForm", "%", None))
        self.cmbLadFisurasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbLadFisurasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbLadFisurasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbLadFisurasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbLadHumTechoAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbLadHumTechoAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbLadHumTechoAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbLadHumTechoAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_12.setText(_translate("ActuacionForm", "%", None))
        self.label_13.setText(_translate("ActuacionForm", "%", None))
        self.cmbLadHumSueloAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbLadHumSueloAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbLadHumSueloAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbLadHumSueloAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbLadGrietasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbLadGrietasAct.setItemText(1, _translate("ActuacionForm", "hasta 60", None))
        self.cmbLadGrietasAct.setItemText(2, _translate("ActuacionForm", "61 a 100", None))
        self.label_10.setText(_translate("ActuacionForm", "%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ActuacionForm", "Albañilería I", None))
        self.groupBox_13.setTitle(_translate("ActuacionForm", "Fábricas Interiores de Ladrillo", None))
        self.groupBox_18.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.cmbIntFisuras.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbIntFisuras.setItemText(1, _translate("ActuacionForm", "Reparación de fisuras", None))
        self.label_38.setText(_translate("ActuacionForm", "Grietas", None))
        self.label_41.setText(_translate("ActuacionForm", "Humedades suelo", None))
        self.cmbHumSuelo.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbHumSuelo.setItemText(1, _translate("ActuacionForm", "Reparación humedades capilaridad", None))
        self.label_39.setText(_translate("ActuacionForm", "Fisuras", None))
        self.cmbIntGrietas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbIntGrietas.setItemText(1, _translate("ActuacionForm", "Reparación grietas en superficie ≤60%", None))
        self.cmbIntGrietas.setItemText(2, _translate("ActuacionForm", "Reparación grietas en superficie >60% (sustitución y reposición)", None))
        self.groupBox_19.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbIntGrietasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbIntGrietasAct.setItemText(1, _translate("ActuacionForm", "hasta 60", None))
        self.cmbIntGrietasAct.setItemText(2, _translate("ActuacionForm", "61 a 100", None))
        self.label_15.setText(_translate("ActuacionForm", "%", None))
        self.label_16.setText(_translate("ActuacionForm", "%", None))
        self.cmbIntFisurasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbIntFisurasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbIntFisurasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbIntFisurasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_14.setText(_translate("ActuacionForm", "%", None))
        self.cmbHumSueloAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbHumSueloAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbHumSueloAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbHumSueloAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("ActuacionForm", "Albañilería II", None))
        self.groupCubInc.setTitle(_translate("ActuacionForm", "Cubiertas inclinadas", None))
        self.groupBox_22.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.cmbCubIncCompleta.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubIncCompleta.setItemText(1, _translate("ActuacionForm", "Reparación faldón (superf.>60%). Sustitución y reposición faldón completo. Rehab. energ. aislm. plancha EPS", None))
        self.cmbCubIncCompleta.setItemText(2, _translate("ActuacionForm", "Reparación faldón (superf.>60%). Sustitución y reposición faldón completo. Rehab. energ. aislm. lana de oveja", None))
        self.label_46.setText(_translate("ActuacionForm", "Faldón", None))
        self.cmbCubIncRemates.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubIncRemates.setItemText(1, _translate("ActuacionForm", "Reparación remates", None))
        self.cmbCubIncEncParamVer.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubIncEncParamVer.setItemText(1, _translate("ActuacionForm", "Reparación encuentros paramentos verticales", None))
        self.cmbCubIncFaldon.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubIncFaldon.setItemText(1, _translate("ActuacionForm", "Reparación faldón ≤60%", None))
        self.label_49.setText(_translate("ActuacionForm", "Encuentros paramentos verticales", None))
        self.label_48.setText(_translate("ActuacionForm", "Remates", None))
        self.label_47.setText(_translate("ActuacionForm", "Completa", None))
        self.groupBox_23.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_60.setText(_translate("ActuacionForm", "%", None))
        self.label_62.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubIncFaldonAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubIncFaldonAct.setItemText(1, _translate("ActuacionForm", "hasta 60", None))
        self.label_61.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubIncCompletaAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubIncCompletaAct.setItemText(1, _translate("ActuacionForm", "61 a 100", None))
        self.label_63.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubIncEncParamVerAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubIncEncParamVerAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCubIncEncParamVerAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCubIncEncParamVerAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbCubIncRematesAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubIncRematesAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCubIncRematesAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCubIncRematesAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.groupCubHor.setTitle(_translate("ActuacionForm", "Cubiertas horizontales", None))
        self.groupBox_20.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.cmbCubHorEncCazoletas.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubHorEncCazoletas.setItemText(1, _translate("ActuacionForm", "Reparación encuentros cazoletas", None))
        self.cmbCubHorFaldon.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubHorFaldon.setItemText(1, _translate("ActuacionForm", "Reparación faldón ≤60%", None))
        self.label_53.setText(_translate("ActuacionForm", "Completa", None))
        self.label_55.setText(_translate("ActuacionForm", "Encuentros paramentos verticales", None))
        self.cmbCubHorEncParamVer.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubHorEncParamVer.setItemText(1, _translate("ActuacionForm", "Reparación encuentros paramentos verticales", None))
        self.label_54.setText(_translate("ActuacionForm", "Encuentros cazoletas", None))
        self.cmbCubHorCom.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCubHorCom.setItemText(1, _translate("ActuacionForm", "Reparación faldón (superf.>60%). Sustitución y reposición faldón completo. Rehab. energ. aislm. plancha EPS", None))
        self.cmbCubHorCom.setItemText(2, _translate("ActuacionForm", "Reparación faldón (superf.>60%). Sustitución y reposición faldón completo. Rehab. energ. aislm. lana de oveja", None))
        self.label_52.setText(_translate("ActuacionForm", "Faldón", None))
        self.groupBox_21.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_42.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubHorComAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubHorComAct.setItemText(1, _translate("ActuacionForm", "61 a 100", None))
        self.cmbCubHorEncParamVerAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubHorEncParamVerAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCubHorEncParamVerAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCubHorEncParamVerAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_45.setText(_translate("ActuacionForm", "%", None))
        self.label_43.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubHorEncCazoletasAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubHorEncCazoletasAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCubHorEncCazoletasAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCubHorEncCazoletasAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_44.setText(_translate("ActuacionForm", "%", None))
        self.cmbCubHorFaldonAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCubHorFaldonAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCubHorFaldonAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ActuacionForm", "Cubiertas", None))
        self.groupBox.setTitle(_translate("ActuacionForm", "Climatización", None))
        self.groupBox_24.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.cmbRadiadores.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbRadiadores.setItemText(1, _translate("ActuacionForm", "Nueva instalación", None))
        self.label_119.setText(_translate("ActuacionForm", "Radiadores", None))
        self.cmbClimatizacion.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbClimatizacion.setItemText(1, _translate("ActuacionForm", "Nueva instalación", None))
        self.label_116.setText(_translate("ActuacionForm", "Aparatos Climatización", None))
        self.groupBox_25.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_122.setText(_translate("ActuacionForm", "%", None))
        self.cmbClimatizacionAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbClimatizacionAct.setItemText(1, _translate("ActuacionForm", "100", None))
        self.label_115.setText(_translate("ActuacionForm", "%", None))
        self.cmbRadiadoresAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbRadiadoresAct.setItemText(1, _translate("ActuacionForm", "100", None))
        self.groupBox_5.setTitle(_translate("ActuacionForm", "Electricidad", None))
        self.groupBox_26.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.label_20.setText(_translate("ActuacionForm", "Circuitos", None))
        self.cmbTomaCorriente.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbTomaCorriente.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.cmbCircuitos.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCircuitos.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.label_26.setText(_translate("ActuacionForm", "Toma de corriente", None))
        self.cmbPuntosLuz.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbPuntosLuz.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.cmbConductorPuestaTierra.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbConductorPuestaTierra.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.label_21.setText(_translate("ActuacionForm", "Líneas y derivaciones", None))
        self.cmbLineasYDerivaciones.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbLineasYDerivaciones.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.label_27.setText(_translate("ActuacionForm", "Conductor de puesta a tierra", None))
        self.label_22.setText(_translate("ActuacionForm", "Puntos de luz", None))
        self.groupBox_27.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_64.setText(_translate("ActuacionForm", "%", None))
        self.label_65.setText(_translate("ActuacionForm", "%", None))
        self.label_68.setText(_translate("ActuacionForm", "%", None))
        self.cmbConductorPuestaTierraAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbConductorPuestaTierraAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbConductorPuestaTierraAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbConductorPuestaTierraAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbTomaCorrienteAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbTomaCorrienteAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbTomaCorrienteAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbTomaCorrienteAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbCircuitosAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCircuitosAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCircuitosAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCircuitosAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_67.setText(_translate("ActuacionForm", "%", None))
        self.label_66.setText(_translate("ActuacionForm", "%", None))
        self.cmbPuntosLuzAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbPuntosLuzAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbPuntosLuzAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbPuntosLuzAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbLineasYDerivacionesAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbLineasYDerivacionesAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbLineasYDerivacionesAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbLineasYDerivacionesAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Instalaciones), _translate("ActuacionForm", "Instalaciones I", None))
        self.groupBox_2.setTitle(_translate("ActuacionForm", "Fontanería", None))
        self.groupBox_28.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.cmbCanalizacionesCal.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesCal.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición en cobre", None))
        self.cmbCanalizacionesCal.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición en polietileno", None))
        self.label_30.setText(_translate("ActuacionForm", "Termos/calentadores", None))
        self.label_25.setText(_translate("ActuacionForm", "Aparatos sanitarios", None))
        self.label_23.setText(_translate("ActuacionForm", "Desagües", None))
        self.cmbSanitarios.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbSanitarios.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.cmbCanalizacionesAguaFria.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCanalizacionesAguaFria.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición en cobre", None))
        self.cmbCanalizacionesAguaFria.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición en polietileno", None))
        self.label_28.setText(_translate("ActuacionForm", "Canalizaciones agua caliente", None))
        self.label_29.setText(_translate("ActuacionForm", "Canalizaciones agua fría", None))
        self.cmbTermos.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbTermos.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición con energa solar térmica apoyo con gas", None))
        self.cmbTermos.setItemText(2, _translate("ActuacionForm", "Sustitución y reposición con energía solar térmica apoyo con electricidad", None))
        self.cmbDesagues.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbDesagues.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición", None))
        self.groupBox_29.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_74.setText(_translate("ActuacionForm", "%", None))
        self.label_70.setText(_translate("ActuacionForm", "%", None))
        self.label_69.setText(_translate("ActuacionForm", "%", None))
        self.label_73.setText(_translate("ActuacionForm", "%", None))
        self.cmbCanalizacionesAguaFriaAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCanalizacionesAguaFriaAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCanalizacionesAguaFriaAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCanalizacionesAguaFriaAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbSanitariosAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbSanitariosAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbSanitariosAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbSanitariosAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_71.setText(_translate("ActuacionForm", "%", None))
        self.cmbTermosAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbTermosAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbTermosAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbTermosAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbCanalizacionesCalAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCanalizacionesCalAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCanalizacionesCalAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCanalizacionesCalAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.cmbDesaguesAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbDesaguesAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbDesaguesAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbDesaguesAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InstalacionesII), _translate("ActuacionForm", "Instalaciones II", None))
        self.groupBox_30.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.label_19.setText(_translate("ActuacionForm", "Carpintería Ligera", None))
        self.cmbCarpLigera.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCarpLigera.setItemText(1, _translate("ActuacionForm", "Ventana abatible+Aluminio RPT+vidrio doble acristalamiento", None))
        self.cmbCarpLigera.setItemText(2, _translate("ActuacionForm", "Ventana abatible+Aluminio RPT+vidrio bajo emisivo", None))
        self.cmbCarpLigera.setItemText(3, _translate("ActuacionForm", "Ventana abatible+Aluminio RPT+vidrio control solar", None))
        self.label_40.setText(_translate("ActuacionForm", "Carpintería Madera", None))
        self.cmbCarpMadera.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbCarpMadera.setItemText(1, _translate("ActuacionForm", "Ventana abatible+Madera+vidrio doble acristalamiento", None))
        self.cmbCarpMadera.setItemText(2, _translate("ActuacionForm", "Ventana abatible+Madera+vidrio bajo emisivo", None))
        self.cmbCarpMadera.setItemText(3, _translate("ActuacionForm", "Ventana abatible+Madera+vidrio control solar", None))
        self.groupBox_31.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.label_75.setText(_translate("ActuacionForm", "%", None))
        self.cmbCarpLigeraAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCarpLigeraAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCarpLigeraAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCarpLigeraAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.label_78.setText(_translate("ActuacionForm", "%", None))
        self.cmbCarpMaderaAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbCarpMaderaAct.setItemText(1, _translate("ActuacionForm", "1 a 30", None))
        self.cmbCarpMaderaAct.setItemText(2, _translate("ActuacionForm", "31 a 60", None))
        self.cmbCarpMaderaAct.setItemText(3, _translate("ActuacionForm", "61 a 100", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("ActuacionForm", "Carpintería y elem. de seguridad y protección", None))
        self.groupBox_32.setTitle(_translate("ActuacionForm", "Actuaciones", None))
        self.cmbAscensores.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbAscensores.setItemText(1, _translate("ActuacionForm", "Nueva instalación", None))
        self.cmbRampa.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbRampa.setItemText(1, _translate("ActuacionForm", "Instalación de rampa", None))
        self.cmbEscalera.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbEscalera.setItemText(1, _translate("ActuacionForm", "Sustitución y reposición de escalera en zonas comunes", None))
        self.cmbEscalera.setItemText(2, _translate("ActuacionForm", "Rectificación de peldañeado de escalera en zonas comunes", None))
        self.label_24.setText(_translate("ActuacionForm", "Escalera", None))
        self.cmbPortero.setItemText(0, _translate("ActuacionForm", "No hay actuaciones", None))
        self.cmbPortero.setItemText(1, _translate("ActuacionForm", "Nueva instalación", None))
        self.label_72.setText(_translate("ActuacionForm", "Portero electrónico", None))
        self.label.setText(_translate("ActuacionForm", "Ascensor", None))
        self.label_50.setText(_translate("ActuacionForm", "Rampa minusválidos", None))
        self.groupBox_33.setTitle(_translate("ActuacionForm", "Grado de actuación", None))
        self.cmbAscensoresAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbAscensoresAct.setItemText(1, _translate("ActuacionForm", "100", None))
        self.cmbEscaleraAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbEscaleraAct.setItemText(1, _translate("ActuacionForm", "100", None))
        self.cmbRampaAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbRampaAct.setItemText(1, _translate("ActuacionForm", "100", None))
        self.cmbPorteroAct.setItemText(0, _translate("ActuacionForm", "0", None))
        self.cmbPorteroAct.setItemText(1, _translate("ActuacionForm", "100", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("ActuacionForm", "Accesibilidad", None))
        self.pushButton.setText(_translate("ActuacionForm", "< Atrás", None))
        self.btnAccept.setText(_translate("ActuacionForm", "Calculo de Huella Ecológica", None))

