# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Jun 17 00:38:45 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, direccion, numcatastro):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1278, 894)
        #self.centralWidget = QtGui.QWidget(MainWindow)
        #self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.cmbTipoVivienda = QtGui.QComboBox(self.centralWidget)
        self.cmbTipoVivienda.setGeometry(QtCore.QRect(950, 30, 211, 25))
        self.cmbTipoVivienda.setObjectName(_fromUtf8("cmbTipoVivienda"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(809, 30, 131, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 621, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 101, 19))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cmbExcavaciones = QtGui.QComboBox(self.groupBox)
        self.cmbExcavaciones.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbExcavaciones.setObjectName(_fromUtf8("cmbExcavaciones"))
        self.cmbExcavaciones.addItem(_fromUtf8(""))
        self.cmbExcavaciones.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 101, 19))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cmbRellenos = QtGui.QComboBox(self.groupBox)
        self.cmbRellenos.setGeometry(QtCore.QRect(250, 60, 351, 25))
        self.cmbRellenos.setObjectName(_fromUtf8("cmbRellenos"))
        self.cmbRellenos.addItem(_fromUtf8(""))
        self.cmbRellenos.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 141, 19))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cmbTransporteTierras = QtGui.QComboBox(self.groupBox)
        self.cmbTransporteTierras.setGeometry(QtCore.QRect(250, 90, 351, 25))
        self.cmbTransporteTierras.setObjectName(_fromUtf8("cmbTransporteTierras"))
        self.cmbTransporteTierras.addItem(_fromUtf8(""))
        self.cmbTransporteTierras.addItem(_fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 621, 101))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 101, 19))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cmbEncofrados = QtGui.QComboBox(self.groupBox_2)
        self.cmbEncofrados.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbEncofrados.setObjectName(_fromUtf8("cmbEncofrados"))
        self.cmbEncofrados.addItem(_fromUtf8(""))
        self.cmbEncofrados.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 231, 19))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cmbHormigones = QtGui.QComboBox(self.groupBox_2)
        self.cmbHormigones.setGeometry(QtCore.QRect(250, 60, 351, 25))
        self.cmbHormigones.setObjectName(_fromUtf8("cmbHormigones"))
        self.cmbHormigones.addItem(_fromUtf8(""))
        self.cmbHormigones.addItem(_fromUtf8(""))
        self.cmbHormigones.addItem(_fromUtf8(""))
        self.groupBox_3 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 300, 621, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 101, 19))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cmbArquetas = QtGui.QComboBox(self.groupBox_3)
        self.cmbArquetas.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbArquetas.setObjectName(_fromUtf8("cmbArquetas"))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.addItem(_fromUtf8(""))
        self.cmbArquetas.setItemText(2, _fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 231, 19))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cmbColectores = QtGui.QComboBox(self.groupBox_3)
        self.cmbColectores.setGeometry(QtCore.QRect(250, 60, 351, 25))
        self.cmbColectores.setObjectName(_fromUtf8("cmbColectores"))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.cmbColectores.addItem(_fromUtf8(""))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 231, 19))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.cmbBajantes = QtGui.QComboBox(self.groupBox_3)
        self.cmbBajantes.setGeometry(QtCore.QRect(250, 90, 351, 25))
        self.cmbBajantes.setObjectName(_fromUtf8("cmbBajantes"))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.cmbBajantes.addItem(_fromUtf8(""))
        self.groupBox_4 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 430, 621, 101))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 101, 19))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.cmbEncofrados_2 = QtGui.QComboBox(self.groupBox_4)
        self.cmbEncofrados_2.setGeometry(QtCore.QRect(250, 60, 351, 25))
        self.cmbEncofrados_2.setObjectName(_fromUtf8("cmbEncofrados_2"))
        self.cmbEncofrados_2.addItem(_fromUtf8(""))
        self.cmbEncofrados_2.addItem(_fromUtf8(""))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 231, 19))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.cmbForjados = QtGui.QComboBox(self.groupBox_4)
        self.cmbForjados.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbForjados.setObjectName(_fromUtf8("cmbForjados"))
        self.cmbForjados.addItem(_fromUtf8(""))
        self.cmbForjados.addItem(_fromUtf8(""))
        self.groupBox_5 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 530, 621, 101))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(20, 60, 201, 19))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.cmbCubiertasI = QtGui.QComboBox(self.groupBox_5)
        self.cmbCubiertasI.setGeometry(QtCore.QRect(250, 60, 351, 25))
        self.cmbCubiertasI.setObjectName(_fromUtf8("cmbCubiertasI"))
        self.cmbCubiertasI.addItem(_fromUtf8(""))
        self.cmbCubiertasI.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(20, 30, 231, 19))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.cmbCubiertasH = QtGui.QComboBox(self.groupBox_5)
        self.cmbCubiertasH.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbCubiertasH.setObjectName(_fromUtf8("cmbCubiertasH"))
        self.cmbCubiertasH.addItem(_fromUtf8(""))
        self.cmbCubiertasH.addItem(_fromUtf8(""))
        self.groupBox_6 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_6.setGeometry(QtCore.QRect(640, 460, 621, 101))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(20, 60, 201, 19))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.cmbPinturasInt = QtGui.QComboBox(self.groupBox_6)
        self.cmbPinturasInt.setGeometry(QtCore.QRect(250, 60, 351, 25))
        self.cmbPinturasInt.setObjectName(_fromUtf8("cmbPinturasInt"))
        self.cmbPinturasInt.addItem(_fromUtf8(""))
        self.cmbPinturasInt.addItem(_fromUtf8(""))
        self.label_15 = QtGui.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(20, 30, 231, 19))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.cmbPinturasExt = QtGui.QComboBox(self.groupBox_6)
        self.cmbPinturasExt.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbPinturasExt.setObjectName(_fromUtf8("cmbPinturasExt"))
        self.cmbPinturasExt.addItem(_fromUtf8(""))
        self.cmbPinturasExt.addItem(_fromUtf8(""))
        self.groupBox_7 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_7.setGeometry(QtCore.QRect(640, 70, 621, 101))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(20, 30, 201, 19))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.cmbAislamientosAc = QtGui.QComboBox(self.groupBox_7)
        self.cmbAislamientosAc.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbAislamientosAc.setObjectName(_fromUtf8("cmbAislamientosAc"))
        self.cmbAislamientosAc.addItem(_fromUtf8(""))
        self.cmbAislamientosAc.addItem(_fromUtf8(""))
        self.cmbAislamientosAc.addItem(_fromUtf8(""))
        self.cmbAislamientosAc.addItem(_fromUtf8(""))
        self.label_17 = QtGui.QLabel(self.groupBox_7)
        self.label_17.setGeometry(QtCore.QRect(20, 60, 231, 19))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.cmbAislamientosTerm = QtGui.QComboBox(self.groupBox_7)
        self.cmbAislamientosTerm.setGeometry(QtCore.QRect(250, 60, 351, 25))
        self.cmbAislamientosTerm.setObjectName(_fromUtf8("cmbAislamientosTerm"))
        self.cmbAislamientosTerm.addItem(_fromUtf8(""))
        self.cmbAislamientosTerm.addItem(_fromUtf8(""))
        self.cmbAislamientosTerm.addItem(_fromUtf8(""))
        self.groupBox_8 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_8.setGeometry(QtCore.QRect(640, 390, 621, 71))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_19 = QtGui.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(20, 30, 231, 19))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.cmbBarandillas = QtGui.QComboBox(self.groupBox_8)
        self.cmbBarandillas.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbBarandillas.setObjectName(_fromUtf8("cmbBarandillas"))
        self.cmbBarandillas.addItem(_fromUtf8(""))
        self.cmbBarandillas.addItem(_fromUtf8(""))
        self.groupBox_9 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 630, 621, 181))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_20 = QtGui.QLabel(self.groupBox_9)
        self.label_20.setGeometry(QtCore.QRect(20, 30, 171, 19))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.cmbLineas = QtGui.QComboBox(self.groupBox_9)
        self.cmbLineas.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbLineas.setObjectName(_fromUtf8("cmbLineas"))
        self.cmbLineas.addItem(_fromUtf8(""))
        self.cmbLineas.addItem(_fromUtf8(""))
        self.label_21 = QtGui.QLabel(self.groupBox_9)
        self.label_21.setGeometry(QtCore.QRect(20, 60, 211, 19))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.cmbCanalizacionesC = QtGui.QComboBox(self.groupBox_9)
        self.cmbCanalizacionesC.setGeometry(QtCore.QRect(250, 60, 351, 25))
        self.cmbCanalizacionesC.setObjectName(_fromUtf8("cmbCanalizacionesC"))
        self.cmbCanalizacionesC.addItem(_fromUtf8(""))
        self.cmbCanalizacionesC.addItem(_fromUtf8(""))
        self.label_22 = QtGui.QLabel(self.groupBox_9)
        self.label_22.setGeometry(QtCore.QRect(20, 90, 191, 19))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.cmbCanalizacionesF = QtGui.QComboBox(self.groupBox_9)
        self.cmbCanalizacionesF.setGeometry(QtCore.QRect(250, 90, 351, 25))
        self.cmbCanalizacionesF.setObjectName(_fromUtf8("cmbCanalizacionesF"))
        self.cmbCanalizacionesF.addItem(_fromUtf8(""))
        self.cmbCanalizacionesF.addItem(_fromUtf8(""))
        self.label_26 = QtGui.QLabel(self.groupBox_9)
        self.label_26.setGeometry(QtCore.QRect(20, 120, 191, 19))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.cmbAparatosSanitarios = QtGui.QComboBox(self.groupBox_9)
        self.cmbAparatosSanitarios.setGeometry(QtCore.QRect(250, 120, 351, 25))
        self.cmbAparatosSanitarios.setObjectName(_fromUtf8("cmbAparatosSanitarios"))
        self.cmbAparatosSanitarios.addItem(_fromUtf8(""))
        self.cmbAparatosSanitarios.addItem(_fromUtf8(""))
        self.label_27 = QtGui.QLabel(self.groupBox_9)
        self.label_27.setGeometry(QtCore.QRect(20, 150, 191, 19))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.cmbTermos = QtGui.QComboBox(self.groupBox_9)
        self.cmbTermos.setGeometry(QtCore.QRect(250, 150, 351, 25))
        self.cmbTermos.setObjectName(_fromUtf8("cmbTermos"))
        self.cmbTermos.addItem(_fromUtf8(""))
        self.cmbTermos.addItem(_fromUtf8(""))
        self.groupBox_10 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_10.setGeometry(QtCore.QRect(640, 170, 621, 221))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.label_23 = QtGui.QLabel(self.groupBox_10)
        self.label_23.setGeometry(QtCore.QRect(20, 30, 101, 19))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.cmbAlicatados = QtGui.QComboBox(self.groupBox_10)
        self.cmbAlicatados.setGeometry(QtCore.QRect(250, 30, 351, 25))
        self.cmbAlicatados.setObjectName(_fromUtf8("cmbAlicatados"))
        self.cmbAlicatados.addItem(_fromUtf8(""))
        self.cmbAlicatados.addItem(_fromUtf8(""))
        self.label_24 = QtGui.QLabel(self.groupBox_10)
        self.label_24.setGeometry(QtCore.QRect(20, 60, 231, 19))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.cmbChapados = QtGui.QComboBox(self.groupBox_10)
        self.cmbChapados.setGeometry(QtCore.QRect(250, 60, 351, 25))
        self.cmbChapados.setObjectName(_fromUtf8("cmbChapados"))
        self.cmbChapados.addItem(_fromUtf8(""))
        self.cmbChapados.addItem(_fromUtf8(""))
        self.cmbChapados.addItem(_fromUtf8(""))
        self.cmbChapados.addItem(_fromUtf8(""))
        self.label_25 = QtGui.QLabel(self.groupBox_10)
        self.label_25.setGeometry(QtCore.QRect(20, 90, 231, 19))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.cmbGuarnecidos = QtGui.QComboBox(self.groupBox_10)
        self.cmbGuarnecidos.setGeometry(QtCore.QRect(250, 90, 351, 25))
        self.cmbGuarnecidos.setObjectName(_fromUtf8("cmbGuarnecidos"))
        self.cmbGuarnecidos.addItem(_fromUtf8(""))
        self.cmbGuarnecidos.addItem(_fromUtf8(""))
        self.cmbSolados = QtGui.QComboBox(self.groupBox_10)
        self.cmbSolados.setGeometry(QtCore.QRect(250, 120, 351, 25))
        self.cmbSolados.setObjectName(_fromUtf8("cmbSolados"))
        self.cmbSolados.addItem(_fromUtf8(""))
        self.cmbSolados.addItem(_fromUtf8(""))
        self.cmbSolados.addItem(_fromUtf8(""))
        self.cmbSolados.addItem(_fromUtf8(""))
        self.cmbSolados.addItem(_fromUtf8(""))
        self.cmbSolados.addItem(_fromUtf8(""))
        self.cmbSolados.addItem(_fromUtf8(""))
        self.cmbSolados.addItem(_fromUtf8(""))
        self.label_28 = QtGui.QLabel(self.groupBox_10)
        self.label_28.setGeometry(QtCore.QRect(20, 120, 231, 19))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.cmbTechos = QtGui.QComboBox(self.groupBox_10)
        self.cmbTechos.setGeometry(QtCore.QRect(250, 150, 351, 25))
        self.cmbTechos.setObjectName(_fromUtf8("cmbTechos"))
        self.cmbTechos.addItem(_fromUtf8(""))
        self.cmbTechos.addItem(_fromUtf8(""))
        self.label_29 = QtGui.QLabel(self.groupBox_10)
        self.label_29.setGeometry(QtCore.QRect(20, 150, 231, 19))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.groupBox_10)
        self.label_30.setGeometry(QtCore.QRect(20, 180, 231, 19))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.cmbRemates = QtGui.QComboBox(self.groupBox_10)
        self.cmbRemates.setGeometry(QtCore.QRect(250, 180, 351, 25))
        self.cmbRemates.setObjectName(_fromUtf8("cmbRemates"))
        self.cmbRemates.addItem(_fromUtf8(""))
        self.cmbRemates.addItem(_fromUtf8(""))
        self.cmbRemates.addItem(_fromUtf8(""))
        self.cmbRemates.addItem(_fromUtf8(""))
        self.label_31 = QtGui.QLabel(self.centralWidget)
        self.label_31.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.tbxDireccion = QtGui.QLineEdit(self.centralWidget)
        self.tbxDireccion.setGeometry(QtCore.QRect(96, 30, 321, 25))
        self.tbxDireccion.setReadOnly(True)
        self.tbxDireccion.setObjectName(_fromUtf8("tbxDireccion"))
        self.label_32 = QtGui.QLabel(self.centralWidget)
        self.label_32.setGeometry(QtCore.QRect(450, 30, 101, 20))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.tbxRefCatastral = QtGui.QLineEdit(self.centralWidget)
        self.tbxRefCatastral.setGeometry(QtCore.QRect(557, 30, 211, 25))
        self.tbxRefCatastral.setReadOnly(True)
        self.tbxRefCatastral.setObjectName(_fromUtf8("tbxRefCatastral"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.tbxRefCatastral = numcatastro
        self.tbxDireccion = direccion
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Tipo de vivienda", None))
        self.groupBox.setTitle(_translate("MainWindow", "Excavaciones", None))
        self.label_2.setText(_translate("MainWindow", "Excavaciones", None))
        self.cmbExcavaciones.setItemText(0, _translate("MainWindow", "Pala", None))
        self.cmbExcavaciones.setItemText(1, _translate("MainWindow", "Retroexcavadora", None))
        self.label_3.setText(_translate("MainWindow", "Relleno", None))
        self.cmbRellenos.setItemText(0, _translate("MainWindow", "Medios manuales", None))
        self.cmbRellenos.setItemText(1, _translate("MainWindow", "Medios mec�nicos", None))
        self.label_4.setText(_translate("MainWindow", "Transporte tierras", None))
        self.cmbTransporteTierras.setItemText(0, _translate("MainWindow", "Medios manuales", None))
        self.cmbTransporteTierras.setItemText(1, _translate("MainWindow", "Medios mec�nicos", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Cimentaciones", None))
        self.label_5.setText(_translate("MainWindow", "Encofrados", None))
        self.cmbEncofrados.setItemText(0, _translate("MainWindow", "Madera", None))
        self.cmbEncofrados.setItemText(1, _translate("MainWindow", "Met�lico", None))
        self.label_6.setText(_translate("MainWindow", "Hormigones armados zapatas", None))
        self.cmbHormigones.setItemText(0, _translate("MainWindow", "Vertido manual", None))
        self.cmbHormigones.setItemText(1, _translate("MainWindow", "Vertido gr�a", None))
        self.cmbHormigones.setItemText(2, _translate("MainWindow", "Vertido bomba", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Saneamiento", None))
        self.label_7.setText(_translate("MainWindow", "Arquetas", None))
        self.cmbArquetas.setItemText(0, _translate("MainWindow", "In situ", None))
        self.cmbArquetas.setItemText(1, _translate("MainWindow", "Prefabricadas", None))
        self.label_8.setText(_translate("MainWindow", "Colectores", None))
        self.cmbColectores.setItemText(0, _translate("MainWindow", "PVC", None))
        self.cmbColectores.setItemText(1, _translate("MainWindow", "Hormig�n", None))
        self.cmbColectores.setItemText(2, _translate("MainWindow", "Fibrocemento", None))
        self.label_9.setText(_translate("MainWindow", "Bajantes", None))
        self.cmbBajantes.setItemText(0, _translate("MainWindow", "PVC", None))
        self.cmbBajantes.setItemText(1, _translate("MainWindow", "Cinc", None))
        self.cmbBajantes.setItemText(2, _translate("MainWindow", "Acero", None))
        self.cmbBajantes.setItemText(3, _translate("MainWindow", "Acero galvanizado", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Estructuras", None))
        self.label_10.setText(_translate("MainWindow", "Encofrados", None))
        self.cmbEncofrados_2.setItemText(0, _translate("MainWindow", "Madera", None))
        self.cmbEncofrados_2.setItemText(1, _translate("MainWindow", "Met�lico", None))
        self.label_11.setText(_translate("MainWindow", "Forjados", None))
        self.cmbForjados.setItemText(0, _translate("MainWindow", "Bobadillas cer�micas", None))
        self.cmbForjados.setItemText(1, _translate("MainWindow", "Bobadillas cemento", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Cubiertas", None))
        self.label_12.setText(_translate("MainWindow", "Cubiertas inclinadas", None))
        self.cmbCubiertasI.setItemText(0, _translate("MainWindow", "Teja cer�mica", None))
        self.cmbCubiertasI.setItemText(1, _translate("MainWindow", "Teja mortero cemento", None))
        self.label_13.setText(_translate("MainWindow", "Cubiertas horizontales", None))
        self.cmbCubiertasH.setItemText(0, _translate("MainWindow", "Transitable", None))
        self.cmbCubiertasH.setItemText(1, _translate("MainWindow", "No transitable", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Pinturas", None))
        self.label_14.setText(_translate("MainWindow", "Pinturas interiores", None))
        self.cmbPinturasInt.setItemText(0, _translate("MainWindow", "Pintura pl�stica lisa", None))
        self.cmbPinturasInt.setItemText(1, _translate("MainWindow", "Pintura al temple liso", None))
        self.label_15.setText(_translate("MainWindow", "Pinturas exteriores", None))
        self.cmbPinturasExt.setItemText(0, _translate("MainWindow", "Pintura elast�mera lisa", None))
        self.cmbPinturasExt.setItemText(1, _translate("MainWindow", "Pintura a la cal", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Aislamientos", None))
        self.label_16.setText(_translate("MainWindow", "Aislamientos Ac�sticos", None))
        self.cmbAislamientosAc.setItemText(0, _translate("MainWindow", "Fibra de vidrio", None))
        self.cmbAislamientosAc.setItemText(1, _translate("MainWindow", "Poliestireno", None))
        self.cmbAislamientosAc.setItemText(2, _translate("MainWindow", "Polietileno", None))
        self.cmbAislamientosAc.setItemText(3, _translate("MainWindow", "Sint�tico de alta densidad", None))
        self.label_17.setText(_translate("MainWindow", "Aislamientos T�rmicos", None))
        self.cmbAislamientosTerm.setItemText(0, _translate("MainWindow", "Fibra de vidrio", None))
        self.cmbAislamientosTerm.setItemText(1, _translate("MainWindow", "Poliestireno", None))
        self.cmbAislamientosTerm.setItemText(2, _translate("MainWindow", "Lana mineral", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Carpinter�a y elementos de seguridad y protecci�n", None))
        self.label_19.setText(_translate("MainWindow", "Barandillas", None))
        self.cmbBarandillas.setItemText(0, _translate("MainWindow", "Acero", None))
        self.cmbBarandillas.setItemText(1, _translate("MainWindow", "Alum. anodizado", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Instalaciones", None))
        self.label_20.setText(_translate("MainWindow", "Lineas y derivaciones", None))
        self.cmbLineas.setItemText(0, _translate("MainWindow", "F�brica", None))
        self.cmbLineas.setItemText(1, _translate("MainWindow", "PVC", None))
        self.label_21.setText(_translate("MainWindow", "Canalizaciones Agua Caliente", None))
        self.cmbCanalizacionesC.setItemText(0, _translate("MainWindow", "Cobre", None))
        self.cmbCanalizacionesC.setItemText(1, _translate("MainWindow", "Acero galvanizado", None))
        self.label_22.setText(_translate("MainWindow", "Canalizaciones Agua Fr�a", None))
        self.cmbCanalizacionesF.setItemText(0, _translate("MainWindow", "Cobre", None))
        self.cmbCanalizacionesF.setItemText(1, _translate("MainWindow", "Acero galvanizado", None))
        self.label_26.setText(_translate("MainWindow", "Aparatos sanitarios", None))
        self.cmbAparatosSanitarios.setItemText(0, _translate("MainWindow", "Porcelana", None))
        self.cmbAparatosSanitarios.setItemText(1, _translate("MainWindow", "Acero", None))
        self.label_27.setText(_translate("MainWindow", "Termos/calentadores", None))
        self.cmbTermos.setItemText(0, _translate("MainWindow", "El�ctrico", None))
        self.cmbTermos.setItemText(1, _translate("MainWindow", "Gas", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Revestimientos", None))
        self.label_23.setText(_translate("MainWindow", "Alicatados", None))
        self.cmbAlicatados.setItemText(0, _translate("MainWindow", "Con adhesivo", None))
        self.cmbAlicatados.setItemText(1, _translate("MainWindow", "Con mortero", None))
        self.label_24.setText(_translate("MainWindow", "Chapados", None))
        self.cmbChapados.setItemText(0, _translate("MainWindow", "Piedra artificial", None))
        self.cmbChapados.setItemText(1, _translate("MainWindow", "Piedra caliza", None))
        self.cmbChapados.setItemText(2, _translate("MainWindow", "Granito", None))
        self.cmbChapados.setItemText(3, _translate("MainWindow", "M�rmol", None))
        self.label_25.setText(_translate("MainWindow", "Guarnecidos", None))
        self.cmbGuarnecidos.setItemText(0, _translate("MainWindow", "Yeso", None))
        self.cmbGuarnecidos.setItemText(1, _translate("MainWindow", "Escayola", None))
        self.cmbSolados.setItemText(0, _translate("MainWindow", "Cer�mica", None))
        self.cmbSolados.setItemText(1, _translate("MainWindow", "Gres", None))
        self.cmbSolados.setItemText(2, _translate("MainWindow", "Baldosa hidr�ulica", None))
        self.cmbSolados.setItemText(3, _translate("MainWindow", "Tarima", None))
        self.cmbSolados.setItemText(4, _translate("MainWindow", "M�rmol", None))
        self.cmbSolados.setItemText(5, _translate("MainWindow", "Piedra caliza", None))
        self.cmbSolados.setItemText(6, _translate("MainWindow", "Granito", None))
        self.cmbSolados.setItemText(7, _translate("MainWindow", "Terrazo", None))
        self.label_28.setText(_translate("MainWindow", "Solados", None))
        self.cmbTechos.setItemText(0, _translate("MainWindow", "Fij. Ca�as", None))
        self.cmbTechos.setItemText(1, _translate("MainWindow", "Fij. Met�lica", None))
        self.label_29.setText(_translate("MainWindow", "Techos", None))
        self.label_30.setText(_translate("MainWindow", "Remates", None))
        self.cmbRemates.setItemText(0, _translate("MainWindow", "Baldosa cer�mica", None))
        self.cmbRemates.setItemText(1, _translate("MainWindow", "M�rmol", None))
        self.cmbRemates.setItemText(2, _translate("MainWindow", "Piedra c�liza", None))
        self.cmbRemates.setItemText(3, _translate("MainWindow", "Madera", None))
        self.label_31.setText(_translate("MainWindow", "Direccion", None))
        self.label_32.setText(_translate("MainWindow", "Ref. Catastral", None))