# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ResultForm.ui'
#
# Created: Mon Oct 26 23:58:52 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ResultForm(object):
    def setupUi(self, ResultForm):
        ResultForm.setObjectName(_fromUtf8("ResultForm"))
        ResultForm.resize(1100, 590)
        ResultForm.setMinimumSize(QtCore.QSize(1100, 590))
        ResultForm.setMaximumSize(QtCore.QSize(1100, 590))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Herevea.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ResultForm.setWindowIcon(icon)
        self.tbxDireccion = QtGui.QLineEdit(ResultForm)
        self.tbxDireccion.setGeometry(QtCore.QRect(100, 20, 461, 25))
        self.tbxDireccion.setReadOnly(True)
        self.tbxDireccion.setObjectName(_fromUtf8("tbxDireccion"))
        self.label_32 = QtGui.QLabel(ResultForm)
        self.label_32.setGeometry(QtCore.QRect(580, 23, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.tbxRefCatastral = QtGui.QLineEdit(ResultForm)
        self.tbxRefCatastral.setGeometry(QtCore.QRect(710, 20, 211, 25))
        self.tbxRefCatastral.setReadOnly(True)
        self.tbxRefCatastral.setObjectName(_fromUtf8("tbxRefCatastral"))
        self.label_31 = QtGui.QLabel(ResultForm)
        self.label_31.setGeometry(QtCore.QRect(13, 20, 101, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.tabWidget = QtGui.QTabWidget(ResultForm)
        self.tabWidget.setGeometry(QtCore.QRect(13, 70, 1071, 441))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabHERehTotal = QtGui.QTableWidget(self.tab)
        self.tabHERehTotal.setGeometry(QtCore.QRect(200, 30, 671, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.tabHERehTotal.setFont(font)
        self.tabHERehTotal.setStyleSheet(_fromUtf8(""))
        self.tabHERehTotal.setFrameShape(QtGui.QFrame.NoFrame)
        self.tabHERehTotal.setAlternatingRowColors(True)
        self.tabHERehTotal.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tabHERehTotal.setShowGrid(False)
        self.tabHERehTotal.setGridStyle(QtCore.Qt.NoPen)
        self.tabHERehTotal.setObjectName(_fromUtf8("tabHERehTotal"))
        self.tabHERehTotal.setColumnCount(2)
        self.tabHERehTotal.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tabHERehTotal.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabHERehTotal.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabHERehTotal.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.tabHERehTotal.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.tabHERehTotal.setItem(0, 1, item)
        self.tabHERehTotal.horizontalHeader().setDefaultSectionSize(250)
        self.tabHERehTotal.horizontalHeader().setStretchLastSection(True)
        self.tabHERehTotal.verticalHeader().setDefaultSectionSize(40)
        self.tabHERehTotal.verticalHeader().setStretchLastSection(True)
        self.chartHEParcial = PlotWidget(self.tab)
        self.chartHEParcial.setGeometry(QtCore.QRect(20, 180, 501, 181))
        self.chartHEParcial.setObjectName(_fromUtf8("chartHEParcial"))
        self.pieChart = GraphicsView(self.tab)
        self.pieChart.setGeometry(QtCore.QRect(590, 180, 281, 201))
        self.pieChart.setObjectName(_fromUtf8("pieChart"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(540, 140, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(170, 140, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayoutWidget = QtGui.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(859, 170, 237, 242))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(20, 0))
        self.label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet(_fromUtf8("background-color: rgb(102, 153, 0);"))
        self.label_4.setFrameShape(QtGui.QFrame.Box)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(20, 0))
        self.label_5.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgb(236, 118, 124);"))
        self.label_5.setFrameShape(QtGui.QFrame.Box)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(20, 0))
        self.label_8.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_8.setStyleSheet(_fromUtf8("background-color: rgb(255, 192, 0);"))
        self.label_8.setFrameShape(QtGui.QFrame.Box)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(20, 0))
        self.label_10.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_10.setStyleSheet(_fromUtf8("background-color: rgb(71, 75, 120);"))
        self.label_10.setFrameShape(QtGui.QFrame.Box)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(20, 0))
        self.label_12.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_12.setStyleSheet(_fromUtf8("background-color: rgb(23, 193, 0);"))
        self.label_12.setFrameShape(QtGui.QFrame.Box)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_13)
        self.label_14 = QtGui.QLabel(self.formLayoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(20, 0))
        self.label_14.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgb(45, 162, 191);"))
        self.label_14.setFrameShape(QtGui.QFrame.Box)
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.label_15)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(20, 0))
        self.label_16.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_16.setStyleSheet(_fromUtf8("background-color: rgb(57, 199, 157);"))
        self.label_16.setFrameShape(QtGui.QFrame.Box)
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtGui.QLabel(self.formLayoutWidget)
        self.label_17.setMinimumSize(QtCore.QSize(20, 0))
        self.label_17.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_17.setStyleSheet(_fromUtf8("background-color: rgb(235, 100, 27);"))
        self.label_17.setFrameShape(QtGui.QFrame.Box)
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.label_18)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabHEDemConsTotal = QtGui.QTableWidget(self.tab_2)
        self.tabHEDemConsTotal.setGeometry(QtCore.QRect(150, 40, 751, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.tabHEDemConsTotal.setFont(font)
        self.tabHEDemConsTotal.setStyleSheet(_fromUtf8(""))
        self.tabHEDemConsTotal.setFrameShape(QtGui.QFrame.NoFrame)
        self.tabHEDemConsTotal.setAlternatingRowColors(True)
        self.tabHEDemConsTotal.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tabHEDemConsTotal.setShowGrid(False)
        self.tabHEDemConsTotal.setGridStyle(QtCore.Qt.NoPen)
        self.tabHEDemConsTotal.setObjectName(_fromUtf8("tabHEDemConsTotal"))
        self.tabHEDemConsTotal.setColumnCount(2)
        self.tabHEDemConsTotal.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tabHEDemConsTotal.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabHEDemConsTotal.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabHEDemConsTotal.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabHEDemConsTotal.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tabHEDemConsTotal.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tabHEDemConsTotal.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tabHEDemConsTotal.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tabHEDemConsTotal.setItem(1, 1, item)
        self.tabHEDemConsTotal.horizontalHeader().setCascadingSectionResizes(True)
        self.tabHEDemConsTotal.horizontalHeader().setDefaultSectionSize(250)
        self.tabHEDemConsTotal.horizontalHeader().setStretchLastSection(True)
        self.tabHEDemConsTotal.verticalHeader().setCascadingSectionResizes(True)
        self.tabHEDemConsTotal.verticalHeader().setDefaultSectionSize(40)
        self.tabHEDemConsTotal.verticalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabPEMDemCons = QtGui.QTableWidget(self.tab_4)
        self.tabPEMDemCons.setGeometry(QtCore.QRect(260, 40, 481, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.tabPEMDemCons.setFont(font)
        self.tabPEMDemCons.setStyleSheet(_fromUtf8(""))
        self.tabPEMDemCons.setFrameShape(QtGui.QFrame.NoFrame)
        self.tabPEMDemCons.setAlternatingRowColors(True)
        self.tabPEMDemCons.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tabPEMDemCons.setShowGrid(False)
        self.tabPEMDemCons.setGridStyle(QtCore.Qt.NoPen)
        self.tabPEMDemCons.setObjectName(_fromUtf8("tabPEMDemCons"))
        self.tabPEMDemCons.setColumnCount(1)
        self.tabPEMDemCons.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tabPEMDemCons.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabPEMDemCons.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabPEMDemCons.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabPEMDemCons.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tabPEMDemCons.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tabPEMDemCons.setItem(2, 0, item)
        self.tabPEMDemCons.horizontalHeader().setCascadingSectionResizes(True)
        self.tabPEMDemCons.horizontalHeader().setDefaultSectionSize(250)
        self.tabPEMDemCons.horizontalHeader().setStretchLastSection(True)
        self.tabPEMDemCons.verticalHeader().setCascadingSectionResizes(True)
        self.tabPEMDemCons.verticalHeader().setDefaultSectionSize(40)
        self.tabPEMDemCons.verticalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabPEMComp = QtGui.QTableWidget(self.tab_5)
        self.tabPEMComp.setGeometry(QtCore.QRect(50, 40, 961, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.tabPEMComp.setFont(font)
        self.tabPEMComp.setStyleSheet(_fromUtf8(""))
        self.tabPEMComp.setFrameShape(QtGui.QFrame.NoFrame)
        self.tabPEMComp.setAlternatingRowColors(True)
        self.tabPEMComp.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tabPEMComp.setShowGrid(False)
        self.tabPEMComp.setGridStyle(QtCore.Qt.NoPen)
        self.tabPEMComp.setObjectName(_fromUtf8("tabPEMComp"))
        self.tabPEMComp.setColumnCount(2)
        self.tabPEMComp.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tabPEMComp.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabPEMComp.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabPEMComp.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabPEMComp.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tabPEMComp.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tabPEMComp.setItem(1, 0, item)
        self.tabPEMComp.horizontalHeader().setCascadingSectionResizes(True)
        self.tabPEMComp.horizontalHeader().setDefaultSectionSize(250)
        self.tabPEMComp.horizontalHeader().setStretchLastSection(True)
        self.tabPEMComp.verticalHeader().setCascadingSectionResizes(True)
        self.tabPEMComp.verticalHeader().setDefaultSectionSize(40)
        self.tabPEMComp.verticalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.layoutWidget = QtGui.QWidget(ResultForm)
        self.layoutWidget.setGeometry(QtCore.QRect(706, 530, 373, 36))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.btnReport = QtGui.QPushButton(self.layoutWidget)
        self.btnReport.setObjectName(_fromUtf8("btnReport"))
        self.horizontalLayout.addWidget(self.btnReport)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ResultForm)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ResultForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ResultForm.reject)
        QtCore.QMetaObject.connectSlotsByName(ResultForm)

    def retranslateUi(self, ResultForm):
        ResultForm.setWindowTitle(_translate("ResultForm", "Herevea", None))
        self.label_32.setText(_translate("ResultForm", "Ref. Catastral", None))
        self.label_31.setText(_translate("ResultForm", "Direccion", None))
        item = self.tabHERehTotal.verticalHeaderItem(0)
        item.setText(_translate("ResultForm", "Rehabilitación", None))
        item = self.tabHERehTotal.horizontalHeaderItem(0)
        item.setText(_translate("ResultForm", "Huella Ecológica (hag/m2)", None))
        item = self.tabHERehTotal.horizontalHeaderItem(1)
        item.setText(_translate("ResultForm", "Huella Ecológica total (hag)", None))
        __sortingEnabled = self.tabHERehTotal.isSortingEnabled()
        self.tabHERehTotal.setSortingEnabled(False)
        self.tabHERehTotal.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("ResultForm", "Impactos de Huella Ecológica de la Energía (%)", None))
        self.label_2.setText(_translate("ResultForm", "Huella Ecológica Parcial (hag)", None))
        self.label_3.setText(_translate("ResultForm", "Maquinaria", None))
        self.label_6.setText(_translate("ResultForm", "Electricidad", None))
        self.label_7.setText(_translate("ResultForm", "Agua", None))
        self.label_9.setText(_translate("ResultForm", "Alimentos", None))
        self.label_11.setText(_translate("ResultForm", "Movilidad", None))
        self.label_13.setText(_translate("ResultForm", "RSU", None))
        self.label_15.setText(_translate("ResultForm", "Materiales", None))
        self.label_18.setText(_translate("ResultForm", "RCD", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ResultForm", "Huella Ecológica rehabilitación", None))
        item = self.tabHEDemConsTotal.verticalHeaderItem(0)
        item.setText(_translate("ResultForm", "Demolición", None))
        item = self.tabHEDemConsTotal.verticalHeaderItem(1)
        item.setText(_translate("ResultForm", "Nueva Construcción", None))
        item = self.tabHEDemConsTotal.horizontalHeaderItem(0)
        item.setText(_translate("ResultForm", "Huella Ecológica (hag/m2)", None))
        item = self.tabHEDemConsTotal.horizontalHeaderItem(1)
        item.setText(_translate("ResultForm", "Huella Ecológica total (hag)", None))
        __sortingEnabled = self.tabHEDemConsTotal.isSortingEnabled()
        self.tabHEDemConsTotal.setSortingEnabled(False)
        item = self.tabHEDemConsTotal.item(0, 0)
        item.setText(_translate("ResultForm", "0", None))
        item = self.tabHEDemConsTotal.item(0, 1)
        item.setText(_translate("ResultForm", "0", None))
        item = self.tabHEDemConsTotal.item(1, 0)
        item.setText(_translate("ResultForm", "0", None))
        item = self.tabHEDemConsTotal.item(1, 1)
        item.setText(_translate("ResultForm", "0", None))
        self.tabHEDemConsTotal.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ResultForm", "Huella Ecológica demolición y construcción", None))
        item = self.tabPEMDemCons.verticalHeaderItem(0)
        item.setText(_translate("ResultForm", "Rehabilitación", None))
        item = self.tabPEMDemCons.verticalHeaderItem(1)
        item.setText(_translate("ResultForm", "Demolición", None))
        item = self.tabPEMDemCons.verticalHeaderItem(2)
        item.setText(_translate("ResultForm", "Nueva Construcción", None))
        item = self.tabPEMDemCons.horizontalHeaderItem(0)
        item.setText(_translate("ResultForm", "PEM (€)", None))
        __sortingEnabled = self.tabPEMDemCons.isSortingEnabled()
        self.tabPEMDemCons.setSortingEnabled(False)
        item = self.tabPEMDemCons.item(1, 0)
        item.setText(_translate("ResultForm", "0", None))
        item = self.tabPEMDemCons.item(2, 0)
        item.setText(_translate("ResultForm", "0", None))
        self.tabPEMDemCons.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ResultForm", "Evaluación económica de rehabilitación, demolición y nueva construcción", None))
        item = self.tabPEMComp.verticalHeaderItem(0)
        item.setText(_translate("ResultForm", "Rehabilitación", None))
        item = self.tabPEMComp.verticalHeaderItem(1)
        item.setText(_translate("ResultForm", "Demolición y nueva construcción", None))
        item = self.tabPEMComp.horizontalHeaderItem(0)
        item.setText(_translate("ResultForm", "PEM (€)", None))
        item = self.tabPEMComp.horizontalHeaderItem(1)
        item.setText(_translate("ResultForm", "Huella Ecológica total (hag)", None))
        __sortingEnabled = self.tabPEMComp.isSortingEnabled()
        self.tabPEMComp.setSortingEnabled(False)
        item = self.tabPEMComp.item(0, 0)
        item.setText(_translate("ResultForm", "0", None))
        item = self.tabPEMComp.item(1, 0)
        item.setText(_translate("ResultForm", "0", None))
        self.tabPEMComp.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("ResultForm", "Comparativa económica y ambiental", None))
        self.pushButton.setText(_translate("ResultForm", "< Atrás", None))
        self.btnReport.setText(_translate("ResultForm", "Generar Informe", None))

from pyqtgraph import GraphicsView, PlotWidget
