# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SeleccionForm.ui'
#
# Created: Fri Sep 25 19:43:33 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SeleccionForm(object):
    def setupUi(self, SeleccionForm):
        SeleccionForm.setObjectName(_fromUtf8("SeleccionForm"))
        SeleccionForm.resize(751, 650)
        SeleccionForm.setMinimumSize(QtCore.QSize(751, 0))
        SeleccionForm.setMaximumSize(QtCore.QSize(751, 920))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Herevea.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SeleccionForm.setWindowIcon(icon)
        self.label = QtGui.QLabel(SeleccionForm)
        self.label.setGeometry(QtCore.QRect(60, 20, 631, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(SeleccionForm)
        self.groupBox.setGeometry(QtCore.QRect(40, 100, 671, 481))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_33 = QtGui.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(33, 52, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.groupBox)
        self.label_34.setGeometry(QtCore.QRect(34, 102, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.cmbProvincia = QtGui.QComboBox(self.groupBox)
        self.cmbProvincia.setGeometry(QtCore.QRect(190, 50, 391, 25))
        self.cmbProvincia.setObjectName(_fromUtf8("cmbProvincia"))
        self.cmbMunicipio = QtGui.QComboBox(self.groupBox)
        self.cmbMunicipio.setGeometry(QtCore.QRect(190, 100, 391, 25))
        self.cmbMunicipio.setObjectName(_fromUtf8("cmbMunicipio"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 390, 631, 71))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.tbxLat = QtGui.QLineEdit(self.groupBox_3)
        self.tbxLat.setGeometry(QtCore.QRect(100, 21, 171, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.tbxLat.setFont(font)
        self.tbxLat.setReadOnly(False)
        self.tbxLat.setObjectName(_fromUtf8("tbxLat"))
        self.label_35 = QtGui.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(30, 24, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.groupBox_3)
        self.label_36.setGeometry(QtCore.QRect(310, 23, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.tbxLong = QtGui.QLineEdit(self.groupBox_3)
        self.tbxLong.setGeometry(QtCore.QRect(400, 20, 171, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.tbxLong.setFont(font)
        self.tbxLong.setReadOnly(False)
        self.tbxLong.setObjectName(_fromUtf8("tbxLong"))
        self.radMapa = QtGui.QRadioButton(self.groupBox)
        self.radMapa.setGeometry(QtCore.QRect(36, 168, 631, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.radMapa.setFont(font)
        self.radMapa.setChecked(True)
        self.radMapa.setObjectName(_fromUtf8("radMapa"))
        self.radCoordenadas = QtGui.QRadioButton(self.groupBox)
        self.radCoordenadas.setEnabled(True)
        self.radCoordenadas.setGeometry(QtCore.QRect(38, 352, 371, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.radCoordenadas.setFont(font)
        self.radCoordenadas.setObjectName(_fromUtf8("radCoordenadas"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 257, 631, 71))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tbxRefCatastral = QtGui.QLineEdit(self.groupBox_2)
        self.tbxRefCatastral.setGeometry(QtCore.QRect(220, 21, 351, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.tbxRefCatastral.setFont(font)
        self.tbxRefCatastral.setReadOnly(False)
        self.tbxRefCatastral.setObjectName(_fromUtf8("tbxRefCatastral"))
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(30, 24, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.radCatastro = QtGui.QRadioButton(self.groupBox)
        self.radCatastro.setEnabled(True)
        self.radCatastro.setGeometry(QtCore.QRect(38, 219, 611, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.radCatastro.setFont(font)
        self.radCatastro.setObjectName(_fromUtf8("radCatastro"))
        self.horizontalLayoutWidget = QtGui.QWidget(SeleccionForm)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(458, 595, 235, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAccept = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnAccept.setDefault(True)
        self.btnAccept.setObjectName(_fromUtf8("btnAccept"))
        self.horizontalLayout.addWidget(self.btnAccept)
        self.btnCancel = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout.addWidget(self.btnCancel)

        self.retranslateUi(SeleccionForm)
        QtCore.QMetaObject.connectSlotsByName(SeleccionForm)

    def retranslateUi(self, SeleccionForm):
        SeleccionForm.setWindowTitle(_translate("SeleccionForm", "Herevea", None))
        self.label.setText(_translate("SeleccionForm", "Para iniciar el análisis introduza la localización de la parcela y elija un método de selección", None))
        self.groupBox.setTitle(_translate("SeleccionForm", "Localización de la parcela", None))
        self.label_33.setText(_translate("SeleccionForm", "Provincia", None))
        self.label_34.setText(_translate("SeleccionForm", "Municipio", None))
        self.label_35.setText(_translate("SeleccionForm", "Latitud", None))
        self.label_36.setText(_translate("SeleccionForm", "Longitud", None))
        self.radMapa.setText(_translate("SeleccionForm", "Selección manual de la parcela en el mapa", None))
        self.radCoordenadas.setText(_translate("SeleccionForm", "Selección mediante coordenadas", None))
        self.label_32.setText(_translate("SeleccionForm", "Referencia Catastral", None))
        self.radCatastro.setText(_translate("SeleccionForm", "Selección mediante información catastral", None))
        self.btnAccept.setText(_translate("SeleccionForm", "Aceptar", None))
        self.btnCancel.setText(_translate("SeleccionForm", "Cancelar", None))

