# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SeleccionForm.ui'
#
# Created: Sat Sep 19 19:51:50 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SeleccionForm(object):
    def setupUi(self, SeleccionForm):
        SeleccionForm.setObjectName(_fromUtf8("SeleccionForm"))
        SeleccionForm.resize(751, 650)
        SeleccionForm.setMinimumSize(QtCore.QSize(751, 0))
        SeleccionForm.setMaximumSize(QtCore.QSize(751, 920))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Herevea.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SeleccionForm.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(SeleccionForm)
        self.buttonBox.setGeometry(QtCore.QRect(350, 590, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label = QtGui.QLabel(SeleccionForm)
        self.label.setGeometry(QtCore.QRect(60, 20, 631, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(SeleccionForm)
        self.groupBox.setGeometry(QtCore.QRect(60, 100, 631, 141))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_33 = QtGui.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(33, 47, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.groupBox)
        self.label_34.setGeometry(QtCore.QRect(34, 87, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.cmbProvincia = QtGui.QComboBox(self.groupBox)
        self.cmbProvincia.setGeometry(QtCore.QRect(190, 45, 391, 25))
        self.cmbProvincia.setObjectName(_fromUtf8("cmbProvincia"))
        self.cmbMunicipio = QtGui.QComboBox(self.groupBox)
        self.cmbMunicipio.setGeometry(QtCore.QRect(190, 85, 391, 25))
        self.cmbMunicipio.setObjectName(_fromUtf8("cmbMunicipio"))
        self.radCatastro = QtGui.QRadioButton(SeleccionForm)
        self.radCatastro.setEnabled(True)
        self.radCatastro.setGeometry(QtCore.QRect(78, 321, 611, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.radCatastro.setFont(font)
        self.radCatastro.setObjectName(_fromUtf8("radCatastro"))
        self.radMapa = QtGui.QRadioButton(SeleccionForm)
        self.radMapa.setGeometry(QtCore.QRect(76, 270, 631, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.radMapa.setFont(font)
        self.radMapa.setChecked(True)
        self.radMapa.setObjectName(_fromUtf8("radMapa"))
        self.groupBox_2 = QtGui.QGroupBox(SeleccionForm)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 359, 631, 71))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tbxRefCatastral = QtGui.QLineEdit(self.groupBox_2)
        self.tbxRefCatastral.setGeometry(QtCore.QRect(220, 21, 351, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.tbxRefCatastral.setFont(font)
        self.tbxRefCatastral.setReadOnly(False)
        self.tbxRefCatastral.setObjectName(_fromUtf8("tbxRefCatastral"))
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(30, 24, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.radCoordenadas = QtGui.QRadioButton(SeleccionForm)
        self.radCoordenadas.setEnabled(True)
        self.radCoordenadas.setGeometry(QtCore.QRect(78, 454, 371, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.radCoordenadas.setFont(font)
        self.radCoordenadas.setObjectName(_fromUtf8("radCoordenadas"))
        self.groupBox_3 = QtGui.QGroupBox(SeleccionForm)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(60, 492, 631, 71))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.tbxLat = QtGui.QLineEdit(self.groupBox_3)
        self.tbxLat.setGeometry(QtCore.QRect(100, 21, 171, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.tbxLat.setFont(font)
        self.tbxLat.setReadOnly(False)
        self.tbxLat.setObjectName(_fromUtf8("tbxLat"))
        self.label_35 = QtGui.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(30, 24, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.groupBox_3)
        self.label_36.setGeometry(QtCore.QRect(310, 23, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.tbxLong = QtGui.QLineEdit(self.groupBox_3)
        self.tbxLong.setGeometry(QtCore.QRect(400, 20, 171, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        self.tbxLong.setFont(font)
        self.tbxLong.setReadOnly(False)
        self.tbxLong.setObjectName(_fromUtf8("tbxLong"))

        self.retranslateUi(SeleccionForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SeleccionForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SeleccionForm.reject)
        QtCore.QMetaObject.connectSlotsByName(SeleccionForm)

    def retranslateUi(self, SeleccionForm):
        SeleccionForm.setWindowTitle(_translate("SeleccionForm", "Herevea", None))
        self.label.setText(_translate("SeleccionForm", "Para iniciar el análisis introduza los datos catastrales de la parcela o seleccione la parcela en el mapa:", None))
        self.groupBox.setTitle(_translate("SeleccionForm", "Localización de la parcela", None))
        self.label_33.setText(_translate("SeleccionForm", "Provincia", None))
        self.label_34.setText(_translate("SeleccionForm", "Municipio", None))
        self.radCatastro.setText(_translate("SeleccionForm", "Selección mediante información catastral", None))
        self.radMapa.setText(_translate("SeleccionForm", "Selección manual de la parcela en el mapa", None))
        self.label_32.setText(_translate("SeleccionForm", "Referencia Catastral", None))
        self.radCoordenadas.setText(_translate("SeleccionForm", "Selección mediante coordenadas", None))
        self.label_35.setText(_translate("SeleccionForm", "Latitud", None))
        self.label_36.setText(_translate("SeleccionForm", "Longitud", None))

